// Code generated by tools/gen. DO NOT EDIT.

package oapi

import (
	"fmt"

	artifact "go.emeland.io/modelsrv/pkg/model/artifact"

	iam "go.emeland.io/modelsrv/pkg/model/iam"

	mdlcap "go.emeland.io/modelsrv/pkg/model/capacity"

	mdlctx "go.emeland.io/modelsrv/pkg/model/context"

	model "go.emeland.io/modelsrv/pkg/model"

	node "go.emeland.io/modelsrv/pkg/model/node"

	uuid "github.com/google/uuid"
)

// ContextTypeFromDto builds a domain ContextType from a wire DTO.
func ContextTypeFromDto(m model.Model, o *ContextType) (mdlctx.ContextType, error) {
	if o == nil {
		return nil, fmt.Errorf("nil context type")
	}
	id := uuid.UUID(o.ContextTypeId)
	v := mdlctx.NewContextType(id)
	v.SetDisplayName(o.DisplayName)
	if o.Description != nil {
		v.SetDescription(*o.Description)
	}
	MergeAnnotationsFromDto(v.GetAnnotations(), o.Annotations)
	return v, nil
}

// NodeTypeFromDto builds a domain NodeType from a wire DTO.
func NodeTypeFromDto(m model.Model, o *NodeType) (node.NodeType, error) {
	if o == nil {
		return nil, fmt.Errorf("nil node type")
	}
	id := uuid.UUID(o.NodeTypeId)
	v := node.NewNodeType(id)
	v.SetDisplayName(o.DisplayName)
	if o.Description != nil {
		v.SetDescription(*o.Description)
	}
	MergeAnnotationsFromDto(v.GetAnnotations(), o.Annotations)
	return v, nil
}

// OrgUnitFromDto builds a domain OrgUnit from a wire DTO.
func OrgUnitFromDto(m model.Model, o *OrgUnit) (iam.OrgUnit, error) {
	if o == nil {
		return nil, fmt.Errorf("nil organizational unit")
	}
	id := uuid.UUID(o.OrgUnitId)
	v := iam.NewOrgUnit(id)
	v.SetDisplayName(o.DisplayName)
	if o.Description != nil {
		v.SetDescription(*o.Description)
	}
	MergeAnnotationsFromDto(v.GetAnnotations(), o.Annotations)
	return v, nil
}

// GroupFromDto builds a domain Group from a wire DTO.
func GroupFromDto(m model.Model, o *Group) (iam.Group, error) {
	if o == nil {
		return nil, fmt.Errorf("nil group")
	}
	id := uuid.UUID(o.GroupId)
	v := iam.NewGroup(id)
	v.SetDisplayName(o.DisplayName)
	if o.Description != nil {
		v.SetDescription(*o.Description)
	}
	MergeAnnotationsFromDto(v.GetAnnotations(), o.Annotations)
	return v, nil
}

// IdentityFromDto builds a domain Identity from a wire DTO.
func IdentityFromDto(m model.Model, o *Identity) (iam.Identity, error) {
	if o == nil {
		return nil, fmt.Errorf("nil identity")
	}
	id := uuid.UUID(o.IdentityId)
	v := iam.NewIdentity(id)
	v.SetDisplayName(o.DisplayName)
	if o.Description != nil {
		v.SetDescription(*o.Description)
	}
	MergeAnnotationsFromDto(v.GetAnnotations(), o.Annotations)
	return v, nil
}

// ArtifactFromDto builds a domain Artifact from a wire DTO.
func ArtifactFromDto(m model.Model, o *Artifact) (artifact.Artifact, error) {
	if o == nil {
		return nil, fmt.Errorf("nil artifact")
	}
	id := uuid.UUID(o.ArtifactId)
	v := artifact.NewArtifact(id)
	v.SetDisplayName(o.DisplayName)
	if o.Description != nil {
		v.SetDescription(*o.Description)
	}
	if o.Hash != nil {
		v.SetHash(*o.Hash)
	}
	MergeAnnotationsFromDto(v.GetAnnotations(), o.Annotations)
	return v, nil
}

// CapacityResourceTypeFromDto builds a domain CapacityResourceType from a wire DTO.
func CapacityResourceTypeFromDto(m model.Model, o *CapacityResourceType) (mdlcap.CapacityResourceType, error) {
	if o == nil {
		return nil, fmt.Errorf("nil capacity resource type")
	}
	id := uuid.UUID(o.CapacityResourceTypeId)
	v := mdlcap.NewCapacityResourceType(id)
	v.SetDisplayName(o.DisplayName)
	if o.Description != nil {
		v.SetDescription(*o.Description)
	}
	MergeAnnotationsFromDto(v.GetAnnotations(), o.Annotations)
	return v, nil
}
