// Code generated by tools/gen. DO NOT EDIT.

package oapi

import (
	"context"
	"fmt"

	"go.emeland.io/modelsrv/pkg/authz"
	"go.emeland.io/modelsrv/pkg/events"
)

// GetLandscapeContextTypes implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeContextTypes(ctx context.Context, request GetLandscapeContextTypesRequestObject) (GetLandscapeContextTypesResponseObject, error) {
	items, err := a.Backend.GetContextTypes()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.ContextTypeResource, items)
	}
	return GetLandscapeContextTypes200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/contextTypes", items)), nil
}

// GetLandscapeContextTypesContextTypeId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeContextTypesContextTypeId(ctx context.Context, request GetLandscapeContextTypesContextTypeIdRequestObject) (GetLandscapeContextTypesContextTypeIdResponseObject, error) {
	item := a.Backend.GetContextTypeById(request.ContextTypeId)
	if item == nil {
		msg := fmt.Sprintf("context type %s not found", request.ContextTypeId.String())
		return GetLandscapeContextTypesContextTypeId404JSONResponse(msg), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.ContextTypeResource, item) {
		msg := fmt.Sprintf("context type %s not found", request.ContextTypeId.String())
		return GetLandscapeContextTypesContextTypeId404JSONResponse(msg), nil
	}
	return GetLandscapeContextTypesContextTypeId200JSONResponse(ContextTypeToDto(item)), nil
}

// GetLandscapeContexts implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeContexts(ctx context.Context, request GetLandscapeContextsRequestObject) (GetLandscapeContextsResponseObject, error) {
	items, err := a.Backend.GetContexts()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.ContextResource, items)
	}
	return GetLandscapeContexts200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/contexts", items)), nil
}

// GetLandscapeContextsContextId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeContextsContextId(ctx context.Context, request GetLandscapeContextsContextIdRequestObject) (GetLandscapeContextsContextIdResponseObject, error) {
	item := a.Backend.GetContextById(request.ContextId)
	if item == nil {
		msg := fmt.Sprintf("context %s not found", request.ContextId.String())
		return GetLandscapeContextsContextId404JSONResponse(msg), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.ContextResource, item) {
		msg := fmt.Sprintf("context %s not found", request.ContextId.String())
		return GetLandscapeContextsContextId404JSONResponse(msg), nil
	}
	return GetLandscapeContextsContextId200JSONResponse(ContextToDto(item)), nil
}

// GetLandscapeSystems implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeSystems(ctx context.Context, request GetLandscapeSystemsRequestObject) (GetLandscapeSystemsResponseObject, error) {
	items, err := a.Backend.GetSystems()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.SystemResource, items)
	}
	return GetLandscapeSystems200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/systems", items)), nil
}

// GetLandscapeSystemsSystemId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeSystemsSystemId(ctx context.Context, request GetLandscapeSystemsSystemIdRequestObject) (GetLandscapeSystemsSystemIdResponseObject, error) {
	item := a.Backend.GetSystemById(request.SystemId)
	if item == nil {
		msg := fmt.Sprintf("system %s not found", request.SystemId.String())
		return GetLandscapeSystemsSystemId404JSONResponse(msg), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.SystemResource, item) {
		msg := fmt.Sprintf("system %s not found", request.SystemId.String())
		return GetLandscapeSystemsSystemId404JSONResponse(msg), nil
	}
	return GetLandscapeSystemsSystemId200JSONResponse(SystemToDto(item)), nil
}

// GetLandscapeNodeTypes implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeNodeTypes(ctx context.Context, request GetLandscapeNodeTypesRequestObject) (GetLandscapeNodeTypesResponseObject, error) {
	items, err := a.Backend.GetNodeTypes()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.NodeTypeResource, items)
	}
	return GetLandscapeNodeTypes200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/nodeTypes", items)), nil
}

// GetLandscapeNodeTypesNodeTypeId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeNodeTypesNodeTypeId(ctx context.Context, request GetLandscapeNodeTypesNodeTypeIdRequestObject) (GetLandscapeNodeTypesNodeTypeIdResponseObject, error) {
	item := a.Backend.GetNodeTypeById(request.NodeTypeId)
	if item == nil {
		msg := fmt.Sprintf("node type %s not found", request.NodeTypeId.String())
		return GetLandscapeNodeTypesNodeTypeId404JSONResponse(msg), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.NodeTypeResource, item) {
		msg := fmt.Sprintf("node type %s not found", request.NodeTypeId.String())
		return GetLandscapeNodeTypesNodeTypeId404JSONResponse(msg), nil
	}
	return GetLandscapeNodeTypesNodeTypeId200JSONResponse(NodeTypeToDto(item)), nil
}

// GetLandscapeFindingTypes implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeFindingTypes(ctx context.Context, request GetLandscapeFindingTypesRequestObject) (GetLandscapeFindingTypesResponseObject, error) {
	items, err := a.Backend.GetFindingTypes()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.FindingTypeResource, items)
	}
	return GetLandscapeFindingTypes200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/findingTypes", items)), nil
}

// GetLandscapeFindingTypesFindingTypeId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeFindingTypesFindingTypeId(ctx context.Context, request GetLandscapeFindingTypesFindingTypeIdRequestObject) (GetLandscapeFindingTypesFindingTypeIdResponseObject, error) {
	item := a.Backend.GetFindingTypeById(request.FindingTypeId)
	if item == nil {
		msg := fmt.Sprintf("finding type %s not found", request.FindingTypeId.String())
		return GetLandscapeFindingTypesFindingTypeId404JSONResponse(msg), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.FindingTypeResource, item) {
		msg := fmt.Sprintf("finding type %s not found", request.FindingTypeId.String())
		return GetLandscapeFindingTypesFindingTypeId404JSONResponse(msg), nil
	}
	return GetLandscapeFindingTypesFindingTypeId200JSONResponse(FindingTypeToDto(item)), nil
}

// GetLandscapeApiInstances implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeApiInstances(ctx context.Context, request GetLandscapeApiInstancesRequestObject) (GetLandscapeApiInstancesResponseObject, error) {
	items, err := a.Backend.GetApiInstances()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.APIInstanceResource, items)
	}
	return GetLandscapeApiInstances200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/api-instances", items)), nil
}

// GetLandscapeApiInstancesApiInstanceId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeApiInstancesApiInstanceId(ctx context.Context, request GetLandscapeApiInstancesApiInstanceIdRequestObject) (GetLandscapeApiInstancesApiInstanceIdResponseObject, error) {
	item := a.Backend.GetApiInstanceById(request.ApiInstanceId)
	if item == nil {
		msg := fmt.Sprintf("api instance %s not found", request.ApiInstanceId.String())
		return GetLandscapeApiInstancesApiInstanceId404JSONResponse(msg), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.APIInstanceResource, item) {
		msg := fmt.Sprintf("api instance %s not found", request.ApiInstanceId.String())
		return GetLandscapeApiInstancesApiInstanceId404JSONResponse(msg), nil
	}
	return GetLandscapeApiInstancesApiInstanceId200JSONResponse(ApiInstanceToDto(item)), nil
}

// GetLandscapeApis implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeApis(ctx context.Context, request GetLandscapeApisRequestObject) (GetLandscapeApisResponseObject, error) {
	items, err := a.Backend.GetApis()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.APIResource, items)
	}
	return GetLandscapeApis200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/apis", items)), nil
}

// GetLandscapeApisApiId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeApisApiId(ctx context.Context, request GetLandscapeApisApiIdRequestObject) (GetLandscapeApisApiIdResponseObject, error) {
	item := a.Backend.GetApiById(request.ApiId)
	if item == nil {
		msg := fmt.Sprintf("api %s not found", request.ApiId.String())
		return GetLandscapeApisApiId404JSONResponse(msg), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.APIResource, item) {
		msg := fmt.Sprintf("api %s not found", request.ApiId.String())
		return GetLandscapeApisApiId404JSONResponse(msg), nil
	}
	return GetLandscapeApisApiId200JSONResponse(APIToDto(item)), nil
}

// GetLandscapeComponents implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeComponents(ctx context.Context, request GetLandscapeComponentsRequestObject) (GetLandscapeComponentsResponseObject, error) {
	items, err := a.Backend.GetComponents()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.ComponentResource, items)
	}
	return GetLandscapeComponents200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/components", items)), nil
}

// GetLandscapeComponentsComponentId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeComponentsComponentId(ctx context.Context, request GetLandscapeComponentsComponentIdRequestObject) (GetLandscapeComponentsComponentIdResponseObject, error) {
	item := a.Backend.GetComponentById(request.ComponentId)
	if item == nil {
		msg := fmt.Sprintf("component %s not found", request.ComponentId.String())
		return GetLandscapeComponentsComponentId404JSONResponse(msg), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.ComponentResource, item) {
		msg := fmt.Sprintf("component %s not found", request.ComponentId.String())
		return GetLandscapeComponentsComponentId404JSONResponse(msg), nil
	}
	return GetLandscapeComponentsComponentId200JSONResponse(ComponentToDto(item)), nil
}

// GetLandscapeSystemInstances implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeSystemInstances(ctx context.Context, request GetLandscapeSystemInstancesRequestObject) (GetLandscapeSystemInstancesResponseObject, error) {
	items, err := a.Backend.GetSystemInstances()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.SystemInstanceResource, items)
	}
	return GetLandscapeSystemInstances200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/system-instances", items)), nil
}

// GetLandscapeSystemInstancesSystemInstanceId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeSystemInstancesSystemInstanceId(ctx context.Context, request GetLandscapeSystemInstancesSystemInstanceIdRequestObject) (GetLandscapeSystemInstancesSystemInstanceIdResponseObject, error) {
	item := a.Backend.GetSystemInstanceById(request.SystemInstanceId)
	if item == nil {
		msg := fmt.Sprintf("system instance %s not found", request.SystemInstanceId.String())
		return GetLandscapeSystemInstancesSystemInstanceId404JSONResponse(msg), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.SystemInstanceResource, item) {
		msg := fmt.Sprintf("system instance %s not found", request.SystemInstanceId.String())
		return GetLandscapeSystemInstancesSystemInstanceId404JSONResponse(msg), nil
	}
	return GetLandscapeSystemInstancesSystemInstanceId200JSONResponse(SystemInstanceToDto(item)), nil
}

// GetLandscapeComponentInstances implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeComponentInstances(ctx context.Context, request GetLandscapeComponentInstancesRequestObject) (GetLandscapeComponentInstancesResponseObject, error) {
	items, err := a.Backend.GetComponentInstances()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.ComponentInstanceResource, items)
	}
	return GetLandscapeComponentInstances200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/component-instances", items)), nil
}

// GetLandscapeComponentInstancesComponentInstanceId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeComponentInstancesComponentInstanceId(ctx context.Context, request GetLandscapeComponentInstancesComponentInstanceIdRequestObject) (GetLandscapeComponentInstancesComponentInstanceIdResponseObject, error) {
	item := a.Backend.GetComponentInstanceById(request.ComponentInstanceId)
	if item == nil {
		msg := fmt.Sprintf("componentInstance %s not found", request.ComponentInstanceId.String())
		return GetLandscapeComponentInstancesComponentInstanceId404JSONResponse(msg), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.ComponentInstanceResource, item) {
		msg := fmt.Sprintf("componentInstance %s not found", request.ComponentInstanceId.String())
		return GetLandscapeComponentInstancesComponentInstanceId404JSONResponse(msg), nil
	}
	return GetLandscapeComponentInstancesComponentInstanceId200JSONResponse(ComponentInstanceToDto(item)), nil
}

// GetLandscapeOrgUnits implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeOrgUnits(ctx context.Context, request GetLandscapeOrgUnitsRequestObject) (GetLandscapeOrgUnitsResponseObject, error) {
	items, err := a.Backend.GetOrgUnits()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.OrgUnitResource, items)
	}
	return GetLandscapeOrgUnits200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/orgUnits", items)), nil
}

// GetLandscapeOrgUnitsOrgUnitId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeOrgUnitsOrgUnitId(ctx context.Context, request GetLandscapeOrgUnitsOrgUnitIdRequestObject) (GetLandscapeOrgUnitsOrgUnitIdResponseObject, error) {
	item := a.Backend.GetOrgUnitById(request.OrgUnitId)
	if item == nil {
		msg := fmt.Sprintf("organizational unit %s not found", request.OrgUnitId.String())
		return GetLandscapeOrgUnitsOrgUnitId404JSONResponse(ErrorString(msg)), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.OrgUnitResource, item) {
		msg := fmt.Sprintf("organizational unit %s not found", request.OrgUnitId.String())
		return GetLandscapeOrgUnitsOrgUnitId404JSONResponse(ErrorString(msg)), nil
	}
	return GetLandscapeOrgUnitsOrgUnitId200JSONResponse(OrgUnitToDto(item)), nil
}

// GetLandscapeGroups implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeGroups(ctx context.Context, request GetLandscapeGroupsRequestObject) (GetLandscapeGroupsResponseObject, error) {
	items, err := a.Backend.GetGroups()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.GroupResource, items)
	}
	return GetLandscapeGroups200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/groups", items)), nil
}

// GetLandscapeGroupsGroupId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeGroupsGroupId(ctx context.Context, request GetLandscapeGroupsGroupIdRequestObject) (GetLandscapeGroupsGroupIdResponseObject, error) {
	item := a.Backend.GetGroupById(request.GroupId)
	if item == nil {
		msg := fmt.Sprintf("group %s not found", request.GroupId.String())
		return GetLandscapeGroupsGroupId404JSONResponse(ErrorString(msg)), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.GroupResource, item) {
		msg := fmt.Sprintf("group %s not found", request.GroupId.String())
		return GetLandscapeGroupsGroupId404JSONResponse(ErrorString(msg)), nil
	}
	return GetLandscapeGroupsGroupId200JSONResponse(GroupToDto(item)), nil
}

// GetLandscapeIdentities implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeIdentities(ctx context.Context, request GetLandscapeIdentitiesRequestObject) (GetLandscapeIdentitiesResponseObject, error) {
	items, err := a.Backend.GetIdentities()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.IdentityResource, items)
	}
	return GetLandscapeIdentities200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/identities", items)), nil
}

// GetLandscapeIdentitiesIdentityId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeIdentitiesIdentityId(ctx context.Context, request GetLandscapeIdentitiesIdentityIdRequestObject) (GetLandscapeIdentitiesIdentityIdResponseObject, error) {
	item := a.Backend.GetIdentityById(request.IdentityId)
	if item == nil {
		msg := fmt.Sprintf("identity %s not found", request.IdentityId.String())
		return GetLandscapeIdentitiesIdentityId404JSONResponse(ErrorString(msg)), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.IdentityResource, item) {
		msg := fmt.Sprintf("identity %s not found", request.IdentityId.String())
		return GetLandscapeIdentitiesIdentityId404JSONResponse(ErrorString(msg)), nil
	}
	return GetLandscapeIdentitiesIdentityId200JSONResponse(IdentityToDto(item)), nil
}

// GetLandscapePermissionSpecs implements [StrictServerInterface].
func (a *ApiServer) GetLandscapePermissionSpecs(ctx context.Context, request GetLandscapePermissionSpecsRequestObject) (GetLandscapePermissionSpecsResponseObject, error) {
	items, err := a.Backend.GetPermissionSpecs()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.PermissionSpecResource, items)
	}
	return GetLandscapePermissionSpecs200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/permissionSpecs", items)), nil
}

// GetLandscapePermissionSpecsPermissionSpecId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapePermissionSpecsPermissionSpecId(ctx context.Context, request GetLandscapePermissionSpecsPermissionSpecIdRequestObject) (GetLandscapePermissionSpecsPermissionSpecIdResponseObject, error) {
	item := a.Backend.GetPermissionSpecById(request.PermissionSpecId)
	if item == nil {
		msg := fmt.Sprintf("permission specification %s not found", request.PermissionSpecId.String())
		return GetLandscapePermissionSpecsPermissionSpecId404JSONResponse(ErrorString(msg)), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.PermissionSpecResource, item) {
		msg := fmt.Sprintf("permission specification %s not found", request.PermissionSpecId.String())
		return GetLandscapePermissionSpecsPermissionSpecId404JSONResponse(ErrorString(msg)), nil
	}
	return GetLandscapePermissionSpecsPermissionSpecId200JSONResponse(PermissionSpecToDto(item)), nil
}

// GetLandscapeRoleSpecs implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeRoleSpecs(ctx context.Context, request GetLandscapeRoleSpecsRequestObject) (GetLandscapeRoleSpecsResponseObject, error) {
	items, err := a.Backend.GetRoleSpecs()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.RoleSpecResource, items)
	}
	return GetLandscapeRoleSpecs200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/roleSpecs", items)), nil
}

// GetLandscapeRoleSpecsRoleSpecId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeRoleSpecsRoleSpecId(ctx context.Context, request GetLandscapeRoleSpecsRoleSpecIdRequestObject) (GetLandscapeRoleSpecsRoleSpecIdResponseObject, error) {
	item := a.Backend.GetRoleSpecById(request.RoleSpecId)
	if item == nil {
		msg := fmt.Sprintf("role specification %s not found", request.RoleSpecId.String())
		return GetLandscapeRoleSpecsRoleSpecId404JSONResponse(ErrorString(msg)), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.RoleSpecResource, item) {
		msg := fmt.Sprintf("role specification %s not found", request.RoleSpecId.String())
		return GetLandscapeRoleSpecsRoleSpecId404JSONResponse(ErrorString(msg)), nil
	}
	return GetLandscapeRoleSpecsRoleSpecId200JSONResponse(RoleSpecToDto(item)), nil
}

// GetLandscapePermissions implements [StrictServerInterface].
func (a *ApiServer) GetLandscapePermissions(ctx context.Context, request GetLandscapePermissionsRequestObject) (GetLandscapePermissionsResponseObject, error) {
	items, err := a.Backend.GetPermissions()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.PermissionResource, items)
	}
	return GetLandscapePermissions200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/permissions", items)), nil
}

// GetLandscapePermissionsPermissionId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapePermissionsPermissionId(ctx context.Context, request GetLandscapePermissionsPermissionIdRequestObject) (GetLandscapePermissionsPermissionIdResponseObject, error) {
	item := a.Backend.GetPermissionById(request.PermissionId)
	if item == nil {
		msg := fmt.Sprintf("permission %s not found", request.PermissionId.String())
		return GetLandscapePermissionsPermissionId404JSONResponse(ErrorString(msg)), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.PermissionResource, item) {
		msg := fmt.Sprintf("permission %s not found", request.PermissionId.String())
		return GetLandscapePermissionsPermissionId404JSONResponse(ErrorString(msg)), nil
	}
	return GetLandscapePermissionsPermissionId200JSONResponse(PermissionToDto(item)), nil
}

// GetLandscapeRoles implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeRoles(ctx context.Context, request GetLandscapeRolesRequestObject) (GetLandscapeRolesResponseObject, error) {
	items, err := a.Backend.GetRoles()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.RoleResource, items)
	}
	return GetLandscapeRoles200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/roles", items)), nil
}

// GetLandscapeRolesRoleId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeRolesRoleId(ctx context.Context, request GetLandscapeRolesRoleIdRequestObject) (GetLandscapeRolesRoleIdResponseObject, error) {
	item := a.Backend.GetRoleById(request.RoleId)
	if item == nil {
		msg := fmt.Sprintf("role %s not found", request.RoleId.String())
		return GetLandscapeRolesRoleId404JSONResponse(ErrorString(msg)), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.RoleResource, item) {
		msg := fmt.Sprintf("role %s not found", request.RoleId.String())
		return GetLandscapeRolesRoleId404JSONResponse(ErrorString(msg)), nil
	}
	return GetLandscapeRolesRoleId200JSONResponse(RoleToDto(item)), nil
}

// GetLandscapeBindings implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeBindings(ctx context.Context, request GetLandscapeBindingsRequestObject) (GetLandscapeBindingsResponseObject, error) {
	items, err := a.Backend.GetBindings()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.BindingResource, items)
	}
	return GetLandscapeBindings200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/bindings", items)), nil
}

// GetLandscapeBindingsBindingId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeBindingsBindingId(ctx context.Context, request GetLandscapeBindingsBindingIdRequestObject) (GetLandscapeBindingsBindingIdResponseObject, error) {
	item := a.Backend.GetBindingById(request.BindingId)
	if item == nil {
		msg := fmt.Sprintf("binding %s not found", request.BindingId.String())
		return GetLandscapeBindingsBindingId404JSONResponse(ErrorString(msg)), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.BindingResource, item) {
		msg := fmt.Sprintf("binding %s not found", request.BindingId.String())
		return GetLandscapeBindingsBindingId404JSONResponse(ErrorString(msg)), nil
	}
	return GetLandscapeBindingsBindingId200JSONResponse(BindingToDto(item)), nil
}

// GetLandscapeArtifacts implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeArtifacts(ctx context.Context, request GetLandscapeArtifactsRequestObject) (GetLandscapeArtifactsResponseObject, error) {
	items, err := a.Backend.GetArtifacts()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.ArtifactResource, items)
	}
	return GetLandscapeArtifacts200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/artifacts", items)), nil
}

// GetLandscapeArtifactsArtifactId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeArtifactsArtifactId(ctx context.Context, request GetLandscapeArtifactsArtifactIdRequestObject) (GetLandscapeArtifactsArtifactIdResponseObject, error) {
	item := a.Backend.GetArtifactById(request.ArtifactId)
	if item == nil {
		msg := fmt.Sprintf("artifact %s not found", request.ArtifactId.String())
		return GetLandscapeArtifactsArtifactId404JSONResponse(ErrorString(msg)), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.ArtifactResource, item) {
		msg := fmt.Sprintf("artifact %s not found", request.ArtifactId.String())
		return GetLandscapeArtifactsArtifactId404JSONResponse(ErrorString(msg)), nil
	}
	return GetLandscapeArtifactsArtifactId200JSONResponse(ArtifactToDto(item)), nil
}

// GetLandscapeArtifactInstances implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeArtifactInstances(ctx context.Context, request GetLandscapeArtifactInstancesRequestObject) (GetLandscapeArtifactInstancesResponseObject, error) {
	items, err := a.Backend.GetArtifactInstances()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.ArtifactInstanceResource, items)
	}
	return GetLandscapeArtifactInstances200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/artifactInstances", items)), nil
}

// GetLandscapeArtifactInstancesArtifactInstanceId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeArtifactInstancesArtifactInstanceId(ctx context.Context, request GetLandscapeArtifactInstancesArtifactInstanceIdRequestObject) (GetLandscapeArtifactInstancesArtifactInstanceIdResponseObject, error) {
	item := a.Backend.GetArtifactInstanceById(request.ArtifactInstanceId)
	if item == nil {
		msg := fmt.Sprintf("artifact instance %s not found", request.ArtifactInstanceId.String())
		return GetLandscapeArtifactInstancesArtifactInstanceId404JSONResponse(ErrorString(msg)), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.ArtifactInstanceResource, item) {
		msg := fmt.Sprintf("artifact instance %s not found", request.ArtifactInstanceId.String())
		return GetLandscapeArtifactInstancesArtifactInstanceId404JSONResponse(ErrorString(msg)), nil
	}
	return GetLandscapeArtifactInstancesArtifactInstanceId200JSONResponse(ArtifactInstanceToDto(item)), nil
}

// GetLandscapeProducts implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeProducts(ctx context.Context, request GetLandscapeProductsRequestObject) (GetLandscapeProductsResponseObject, error) {
	items, err := a.Backend.GetProducts()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.ProductResource, items)
	}
	return GetLandscapeProducts200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/products", items)), nil
}

// GetLandscapeProductsProductId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeProductsProductId(ctx context.Context, request GetLandscapeProductsProductIdRequestObject) (GetLandscapeProductsProductIdResponseObject, error) {
	item := a.Backend.GetProductById(request.ProductId)
	if item == nil {
		msg := fmt.Sprintf("product %s not found", request.ProductId.String())
		return GetLandscapeProductsProductId404JSONResponse(ErrorString(msg)), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.ProductResource, item) {
		msg := fmt.Sprintf("product %s not found", request.ProductId.String())
		return GetLandscapeProductsProductId404JSONResponse(ErrorString(msg)), nil
	}
	return GetLandscapeProductsProductId200JSONResponse(ProductToDto(item)), nil
}

// GetLandscapeFilterRules implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeFilterRules(ctx context.Context, request GetLandscapeFilterRulesRequestObject) (GetLandscapeFilterRulesResponseObject, error) {
	items, err := a.Backend.GetFilterRules()
	if err != nil {
		return nil, err
	}
	return GetLandscapeFilterRules200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/filter-rules", items)), nil
}

// GetLandscapeFilterRulesRuleId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeFilterRulesRuleId(ctx context.Context, request GetLandscapeFilterRulesRuleIdRequestObject) (GetLandscapeFilterRulesRuleIdResponseObject, error) {
	item := a.Backend.GetFilterRuleById(request.RuleId)
	if item == nil {
		msg := fmt.Sprintf("filter rule %s not found", request.RuleId.String())
		return GetLandscapeFilterRulesRuleId404JSONResponse(msg), nil
	}
	return GetLandscapeFilterRulesRuleId200JSONResponse(FilterRuleToDto(item)), nil
}

// GetLandscapeMergeRules implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeMergeRules(ctx context.Context, request GetLandscapeMergeRulesRequestObject) (GetLandscapeMergeRulesResponseObject, error) {
	items, err := a.Backend.GetMergeRules()
	if err != nil {
		return nil, err
	}
	return GetLandscapeMergeRules200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/merge-rules", items)), nil
}

// GetLandscapeMergeRulesRuleId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeMergeRulesRuleId(ctx context.Context, request GetLandscapeMergeRulesRuleIdRequestObject) (GetLandscapeMergeRulesRuleIdResponseObject, error) {
	item := a.Backend.GetMergeRuleById(request.RuleId)
	if item == nil {
		msg := fmt.Sprintf("merge rule %s not found", request.RuleId.String())
		return GetLandscapeMergeRulesRuleId404JSONResponse(msg), nil
	}
	return GetLandscapeMergeRulesRuleId200JSONResponse(MergeRuleToDto(item)), nil
}

// GetLandscapeCapabilities implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeCapabilities(ctx context.Context, request GetLandscapeCapabilitiesRequestObject) (GetLandscapeCapabilitiesResponseObject, error) {
	items, err := a.Backend.GetCapabilities()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.CapabilityResource, items)
	}
	return GetLandscapeCapabilities200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/capabilities", items)), nil
}

// GetLandscapeCapabilitiesCapabilityId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeCapabilitiesCapabilityId(ctx context.Context, request GetLandscapeCapabilitiesCapabilityIdRequestObject) (GetLandscapeCapabilitiesCapabilityIdResponseObject, error) {
	item := a.Backend.GetCapabilityById(request.CapabilityId)
	if item == nil {
		msg := fmt.Sprintf("capability %s not found", request.CapabilityId.String())
		return GetLandscapeCapabilitiesCapabilityId404JSONResponse(msg), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.CapabilityResource, item) {
		msg := fmt.Sprintf("capability %s not found", request.CapabilityId.String())
		return GetLandscapeCapabilitiesCapabilityId404JSONResponse(msg), nil
	}
	return GetLandscapeCapabilitiesCapabilityId200JSONResponse(CapabilityToDto(item)), nil
}

// GetLandscapeParameters implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeParameters(ctx context.Context, request GetLandscapeParametersRequestObject) (GetLandscapeParametersResponseObject, error) {
	items, err := a.Backend.GetParameters()
	if err != nil {
		return nil, err
	}
	if a.Authz != nil {
		principal := authz.PrincipalFromCtx(ctx)
		items = authz.FilterVisible(a.Authz, principal, events.ParameterResource, items)
	}
	return GetLandscapeParameters200JSONResponse(buildInstanceList(a.BaseURL, "/landscape/parameters", items)), nil
}

// GetLandscapeParametersParameterId implements [StrictServerInterface].
func (a *ApiServer) GetLandscapeParametersParameterId(ctx context.Context, request GetLandscapeParametersParameterIdRequestObject) (GetLandscapeParametersParameterIdResponseObject, error) {
	item := a.Backend.GetParameterById(request.ParameterId)
	if item == nil {
		msg := fmt.Sprintf("parameter %s not found", request.ParameterId.String())
		return GetLandscapeParametersParameterId404JSONResponse(msg), nil
	}
	if a.Authz != nil && !a.Authz.CanSee(authz.PrincipalFromCtx(ctx), events.ParameterResource, item) {
		msg := fmt.Sprintf("parameter %s not found", request.ParameterId.String())
		return GetLandscapeParametersParameterId404JSONResponse(msg), nil
	}
	return GetLandscapeParametersParameterId200JSONResponse(ParameterToDto(item)), nil
}
