// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// API defines model for API.
type API struct {
	// Annotations A set of key-value pairs for storing additional metadata about the API instance.
	Annotations *[]Annotation `json:"annotations,omitempty"`

	// ApiId An UUID that uniquely identifies the API. It should be generated and assigned when the API is created and must remain constant throughout the API's lifecycle. The field is optional in some contexts, such as when creating a new API where the ID may be generated by the system itself.
	ApiId *openapi_types.UUID `json:"apiId,omitempty"`

	// Description A brief description of the API's purpose and functionality.
	Description *string `json:"description,omitempty"`

	// DisplayName The human-readable name of the API.
	DisplayName string `json:"displayName"`

	// System The UUID of the system that provides this API.
	System *openapi_types.UUID `json:"system,omitempty"`

	// Type The type of the API (e.g., OpenAPI, gRPC, GraphQL). If the type is unknown, it should be set to "Unknown". If the type does not fit any predefined categories, it should be set to "Other". In such cases, additional details about the API type should be provided in the description field.
	Type interface{} `json:"type"`

	// Version Version information for all objects in the EmELand model.
	Version *Version `json:"version,omitempty"`
}

// Annotation Represents a key-value pair used for annotating systems and other entities in the EmELand model.
type Annotation struct {
	// Key The key of the annotation. It serves as the identifier for the annotation entry.
	Key string `json:"key"`

	// Value The value associated with the annotation key. It provides additional information or metadata related to the key.
	Value string `json:"value"`
}

// ApiInstance defines model for ApiInstance.
type ApiInstance struct {
	// Annotations A set of key-value pairs for storing additional metadata about the API instance.
	Annotations *[]Annotation `json:"annotations,omitempty"`

	// Api The UUID of the API that this instance realizes. This can be left empty if the API resource has not been created yet, but will trigger an entry in the finding list.
	Api *openapi_types.UUID `json:"api,omitempty"`

	// ApiInstanceId An UUID that uniquely identifies the API instance. It should be generated and assigned when the instance is created and must remain constant throughout the instance's lifecycle. The field is optional in some contexts, such as when creating a new instance where the ID may be generated by the system itself.
	ApiInstanceId openapi_types.UUID `json:"apiInstanceId"`

	// DisplayName The human-readable name of the API instance.
	DisplayName string `json:"displayName"`

	// SystemInstance The UUID of the system instance that contains this API instance. This can be left empty if the SystemInstance resource has not been created yet, but will trigger an entry in the finding list.
	SystemInstance *openapi_types.UUID `json:"systemInstance,omitempty"`
}

// Component defines model for Component.
type Component struct {
	// Annotations A set of key-value pairs for storing additional metadata about the component.
	Annotations *[]Annotation `json:"annotations,omitempty"`

	// ComponentId An UUID that uniquely identifies the component. It should be generated and assigned when the component is created and must remain constant throughout the component's lifecycle. The field is optional in some contexts, such as when creating a new component where the ID may be generated by the system itself.
	ComponentId *openapi_types.UUID `json:"componentId,omitempty"`

	// Consumes A list of API UUIDs that this component consumes.
	Consumes *[]openapi_types.UUID `json:"consumes,omitempty"`

	// Description A brief description of the component's purpose and functionality.
	Description *string `json:"description,omitempty"`

	// DisplayName The human-readable name of the component.
	DisplayName string `json:"displayName"`

	// Provides A list of API UUIDs that this component provides.
	Provides *[]openapi_types.UUID `json:"provides,omitempty"`

	// System The UUID of the system that contains this component.
	System openapi_types.UUID `json:"system"`

	// Version Version information for all objects in the EmELand model.
	Version *Version `json:"version,omitempty"`
}

// ComponentInstance defines model for ComponentInstance.
type ComponentInstance struct {
	// Annotations A set of key-value pairs for storing additional metadata about the component instance.
	Annotations *[]Annotation `json:"annotations,omitempty"`

	// Component The UUID of the component that this instance realizes.
	Component openapi_types.UUID `json:"component"`

	// ComponentInstanceId An UUID that uniquely identifies the component instance. It should be generated and assigned when the instance is created and must remain constant throughout the instance's lifecycle. The field is optional in some contexts, such as when creating a new instance where the ID may be generated by the system itself.
	ComponentInstanceId openapi_types.UUID `json:"componentInstanceId"`

	// Consumes A list of API instance UUIDs that this component instance consumes.
	Consumes []openapi_types.UUID `json:"consumes"`

	// DisplayName The human-readable name of the component instance.
	DisplayName string `json:"displayName"`

	// Provides A list of API instance UUIDs that this component instance provides.
	Provides []openapi_types.UUID `json:"provides"`

	// SystemInstance The UUID of the system instance that contains this component instance.
	SystemInstance openapi_types.UUID `json:"systemInstance"`
}

// Finding Represents the finding of a rule violation. Rules may either be defined for semantic correctness of the model or for compliance checks against external regulations and standards.
type Finding struct {
	Description *string            `json:"description,omitempty"`
	FindingId   openapi_types.UUID `json:"findingId"`
	Resources   []ResourceRef      `json:"resources"`
	Summary     string             `json:"summary"`
}

// InstanceList defines model for InstanceList.
type InstanceList = []InstanceListItem

// InstanceListItem defines model for InstanceListItem.
type InstanceListItem struct {
	DisplayName *string             `json:"displayName,omitempty"`
	InstanceId  *openapi_types.UUID `json:"instanceId,omitempty"`
	Reference   *string             `json:"reference,omitempty"`
}

// ResourceRef defines model for ResourceRef.
type ResourceRef struct {
	Reference  *string            `json:"reference,omitempty"`
	ResourceId openapi_types.UUID `json:"resourceId"`

	// ResourceType The type of the resource referenced.
	ResourceType interface{} `json:"resourceType"`
}

// System Represents a system in the EmELand model. A system is a high-level entity that displays a complex behavior. It encapsulates various APIs and software components.
type System struct {
	// Abstract Indicates whether the system is abstract (true) or concrete (false). Abstract systems are primarily used to represent external systems that provide APIs consumed by a concrete system defined within the landscape.
	Abstract bool `json:"abstract"`

	// Annotations A set of key-value pairs for storing additional metadata about the system.
	Annotations *[]Annotation `json:"annotations,omitempty"`

	// Description A brief description of the system's purpose and functionality.
	Description *string `json:"description,omitempty"`
	DisplayName string  `json:"displayName"`

	// Parent The UUID of the parent system, if applicable. This field is optional and may be omitted if the system has no parent. It establishes a hierarchical relationship between systems.
	Parent *openapi_types.UUID `json:"parent,omitempty"`

	// SystemId An UUID that uniquely identifies the system. It should be generated and assigned when the System is created and must remain constant throughout the System's lifecycle. The field is optional in some contexts, such as when creating a new system where the ID may be generated by the system itself.
	SystemId *openapi_types.UUID `json:"systemId,omitempty"`

	// Version Version information for all objects in the EmELand model.
	Version *Version `json:"version,omitempty"`
}

// SystemInstance defines model for SystemInstance.
type SystemInstance struct {
	// Annotations A set of key-value pairs for storing additional metadata about the system instance.
	Annotations *[]Annotation `json:"annotations,omitempty"`

	// DisplayName The human-readable name of the system instance.
	DisplayName string `json:"displayName"`

	// System The UUID of the system that this instance realizes.
	System openapi_types.UUID `json:"system"`

	// SystemInstanceId An UUID that uniquely identifies the system instance. It should be generated and assigned when the instance is created and must remain constant throughout the instance's lifecycle. The field is optional in some contexts, such as when creating a new instance where the ID may be generated by the system itself.
	SystemInstanceId openapi_types.UUID `json:"systemInstanceId"`
}

// Version Version information for all objects in the EmELand model.
type Version struct {
	// AvailableFrom Timestamp indicating when this version becomes available. Format is 2006-01-02. May be in the future
	AvailableFrom *time.Time `json:"availableFrom,omitempty"`

	// DeprecatedFrom Timestamp indicating when this version is considered deprecated. Consumers should avoid using this version after this date. Format is 2006-01-02. May be in the future. Must be later than availableFrom.
	DeprecatedFrom *time.Time `json:"deprecatedFrom,omitempty"`

	// TerminatedFrom Timestamp indicating when this version is considered terminated. Consumers must not use this version after this date. Format is 2006-01-02. Must be later than deprecatedFrom.
	TerminatedFrom *time.Time `json:"terminatedFrom,omitempty"`

	// Version Structured version string (e.g., "1.0.0"). The use of semantic versioning is recommended.
	Version string `json:"version"`
}

// PostEventsRegisterJSONBody defines parameters for PostEventsRegister.
type PostEventsRegisterJSONBody struct {
	CallbackUrl *string `json:"callbackUrl,omitempty"`
}

// PostEventsRegisterJSONRequestBody defines body for PostEventsRegister for application/json ContentType.
type PostEventsRegisterJSONRequestBody PostEventsRegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /events/query/{sequenceId})
	GetEventsQuerySequenceId(w http.ResponseWriter, r *http.Request, sequenceId string)

	// (POST /events/register)
	PostEventsRegister(w http.ResponseWriter, r *http.Request)

	// (GET /landscape/api-instances)
	GetLandscapeApiInstances(w http.ResponseWriter, r *http.Request)

	// (GET /landscape/api-instances/{apiInstanceId})
	GetLandscapeApiInstancesApiInstanceId(w http.ResponseWriter, r *http.Request, apiInstanceId openapi_types.UUID)

	// (GET /landscape/apis)
	GetLandscapeApis(w http.ResponseWriter, r *http.Request)

	// (GET /landscape/apis/{apiId})
	GetLandscapeApisApiId(w http.ResponseWriter, r *http.Request, apiId openapi_types.UUID)

	// (GET /landscape/component-instances)
	GetLandscapeComponentInstances(w http.ResponseWriter, r *http.Request)

	// (GET /landscape/component-instances/{componentInstanceId})
	GetLandscapeComponentInstancesComponentInstanceId(w http.ResponseWriter, r *http.Request, componentInstanceId openapi_types.UUID)

	// (GET /landscape/components)
	GetLandscapeComponents(w http.ResponseWriter, r *http.Request)

	// (GET /landscape/components/{componentId})
	GetLandscapeComponentsComponentId(w http.ResponseWriter, r *http.Request, componentId openapi_types.UUID)

	// (GET /landscape/findings)
	GetLandscapeFindings(w http.ResponseWriter, r *http.Request)

	// (GET /landscape/findings/{findingId})
	GetLandscapeFindingsFindingId(w http.ResponseWriter, r *http.Request, findingId openapi_types.UUID)

	// (GET /landscape/system-instances)
	GetLandscapeSystemInstances(w http.ResponseWriter, r *http.Request)

	// (GET /landscape/system-instances/{systemInstanceId})
	GetLandscapeSystemInstancesSystemInstanceId(w http.ResponseWriter, r *http.Request, systemInstanceId openapi_types.UUID)

	// (GET /landscape/systems)
	GetLandscapeSystems(w http.ResponseWriter, r *http.Request)

	// (GET /landscape/systems/{systemId})
	GetLandscapeSystemsSystemId(w http.ResponseWriter, r *http.Request, systemId openapi_types.UUID)

	// (GET /test)
	GetTest(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEventsQuerySequenceId operation middleware
func (siw *ServerInterfaceWrapper) GetEventsQuerySequenceId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sequenceId" -------------
	var sequenceId string

	err = runtime.BindStyledParameterWithOptions("simple", "sequenceId", mux.Vars(r)["sequenceId"], &sequenceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sequenceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsQuerySequenceId(w, r, sequenceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsRegister operation middleware
func (siw *ServerInterfaceWrapper) PostEventsRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeApiInstances operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeApiInstances(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeApiInstances(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeApiInstancesApiInstanceId operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeApiInstancesApiInstanceId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "apiInstanceId" -------------
	var apiInstanceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "apiInstanceId", mux.Vars(r)["apiInstanceId"], &apiInstanceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiInstanceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeApiInstancesApiInstanceId(w, r, apiInstanceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeApis operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeApis(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeApis(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeApisApiId operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeApisApiId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "apiId" -------------
	var apiId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "apiId", mux.Vars(r)["apiId"], &apiId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeApisApiId(w, r, apiId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeComponentInstances operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeComponentInstances(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeComponentInstances(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeComponentInstancesComponentInstanceId operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeComponentInstancesComponentInstanceId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "componentInstanceId" -------------
	var componentInstanceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "componentInstanceId", mux.Vars(r)["componentInstanceId"], &componentInstanceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "componentInstanceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeComponentInstancesComponentInstanceId(w, r, componentInstanceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeComponents operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeComponents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeComponents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeComponentsComponentId operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeComponentsComponentId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "componentId" -------------
	var componentId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "componentId", mux.Vars(r)["componentId"], &componentId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "componentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeComponentsComponentId(w, r, componentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeFindings operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeFindings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeFindings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeFindingsFindingId operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeFindingsFindingId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "findingId" -------------
	var findingId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "findingId", mux.Vars(r)["findingId"], &findingId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "findingId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeFindingsFindingId(w, r, findingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeSystemInstances operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeSystemInstances(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeSystemInstances(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeSystemInstancesSystemInstanceId operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeSystemInstancesSystemInstanceId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "systemInstanceId" -------------
	var systemInstanceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "systemInstanceId", mux.Vars(r)["systemInstanceId"], &systemInstanceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "systemInstanceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeSystemInstancesSystemInstanceId(w, r, systemInstanceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeSystems operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeSystems(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeSystems(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLandscapeSystemsSystemId operation middleware
func (siw *ServerInterfaceWrapper) GetLandscapeSystemsSystemId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "systemId" -------------
	var systemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "systemId", mux.Vars(r)["systemId"], &systemId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "systemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLandscapeSystemsSystemId(w, r, systemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTest operation middleware
func (siw *ServerInterfaceWrapper) GetTest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/events/query/{sequenceId}", wrapper.GetEventsQuerySequenceId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/events/register", wrapper.PostEventsRegister).Methods("POST")

	r.HandleFunc(options.BaseURL+"/landscape/api-instances", wrapper.GetLandscapeApiInstances).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landscape/api-instances/{apiInstanceId}", wrapper.GetLandscapeApiInstancesApiInstanceId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landscape/apis", wrapper.GetLandscapeApis).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landscape/apis/{apiId}", wrapper.GetLandscapeApisApiId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landscape/component-instances", wrapper.GetLandscapeComponentInstances).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landscape/component-instances/{componentInstanceId}", wrapper.GetLandscapeComponentInstancesComponentInstanceId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landscape/components", wrapper.GetLandscapeComponents).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landscape/components/{componentId}", wrapper.GetLandscapeComponentsComponentId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landscape/findings", wrapper.GetLandscapeFindings).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landscape/findings/{findingId}", wrapper.GetLandscapeFindingsFindingId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landscape/system-instances", wrapper.GetLandscapeSystemInstances).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landscape/system-instances/{systemInstanceId}", wrapper.GetLandscapeSystemInstancesSystemInstanceId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landscape/systems", wrapper.GetLandscapeSystems).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landscape/systems/{systemId}", wrapper.GetLandscapeSystemsSystemId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/test", wrapper.GetTest).Methods("GET")

	return r
}

type GetEventsQuerySequenceIdRequestObject struct {
	SequenceId string `json:"sequenceId"`
}

type GetEventsQuerySequenceIdResponseObject interface {
	VisitGetEventsQuerySequenceIdResponse(w http.ResponseWriter) error
}

type GetEventsQuerySequenceId200Response struct {
}

func (response GetEventsQuerySequenceId200Response) VisitGetEventsQuerySequenceIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetEventsQuerySequenceId308Response struct {
}

func (response GetEventsQuerySequenceId308Response) VisitGetEventsQuerySequenceIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(308)
	return nil
}

type GetEventsQuerySequenceId404Response struct {
}

func (response GetEventsQuerySequenceId404Response) VisitGetEventsQuerySequenceIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostEventsRegisterRequestObject struct {
	Body *PostEventsRegisterJSONRequestBody
}

type PostEventsRegisterResponseObject interface {
	VisitPostEventsRegisterResponse(w http.ResponseWriter) error
}

type PostEventsRegister201Response struct {
}

func (response PostEventsRegister201Response) VisitPostEventsRegisterResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type GetLandscapeApiInstancesRequestObject struct {
}

type GetLandscapeApiInstancesResponseObject interface {
	VisitGetLandscapeApiInstancesResponse(w http.ResponseWriter) error
}

type GetLandscapeApiInstances200JSONResponse InstanceList

func (response GetLandscapeApiInstances200JSONResponse) VisitGetLandscapeApiInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeApiInstancesApiInstanceIdRequestObject struct {
	ApiInstanceId openapi_types.UUID `json:"apiInstanceId"`
}

type GetLandscapeApiInstancesApiInstanceIdResponseObject interface {
	VisitGetLandscapeApiInstancesApiInstanceIdResponse(w http.ResponseWriter) error
}

type GetLandscapeApiInstancesApiInstanceId200JSONResponse ApiInstance

func (response GetLandscapeApiInstancesApiInstanceId200JSONResponse) VisitGetLandscapeApiInstancesApiInstanceIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeApiInstancesApiInstanceId404Response struct {
}

func (response GetLandscapeApiInstancesApiInstanceId404Response) VisitGetLandscapeApiInstancesApiInstanceIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetLandscapeApisRequestObject struct {
}

type GetLandscapeApisResponseObject interface {
	VisitGetLandscapeApisResponse(w http.ResponseWriter) error
}

type GetLandscapeApis200JSONResponse InstanceList

func (response GetLandscapeApis200JSONResponse) VisitGetLandscapeApisResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeApisApiIdRequestObject struct {
	ApiId openapi_types.UUID `json:"apiId"`
}

type GetLandscapeApisApiIdResponseObject interface {
	VisitGetLandscapeApisApiIdResponse(w http.ResponseWriter) error
}

type GetLandscapeApisApiId200JSONResponse API

func (response GetLandscapeApisApiId200JSONResponse) VisitGetLandscapeApisApiIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeApisApiId404Response struct {
}

func (response GetLandscapeApisApiId404Response) VisitGetLandscapeApisApiIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetLandscapeComponentInstancesRequestObject struct {
}

type GetLandscapeComponentInstancesResponseObject interface {
	VisitGetLandscapeComponentInstancesResponse(w http.ResponseWriter) error
}

type GetLandscapeComponentInstances200JSONResponse InstanceList

func (response GetLandscapeComponentInstances200JSONResponse) VisitGetLandscapeComponentInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeComponentInstancesComponentInstanceIdRequestObject struct {
	ComponentInstanceId openapi_types.UUID `json:"componentInstanceId"`
}

type GetLandscapeComponentInstancesComponentInstanceIdResponseObject interface {
	VisitGetLandscapeComponentInstancesComponentInstanceIdResponse(w http.ResponseWriter) error
}

type GetLandscapeComponentInstancesComponentInstanceId200JSONResponse ComponentInstance

func (response GetLandscapeComponentInstancesComponentInstanceId200JSONResponse) VisitGetLandscapeComponentInstancesComponentInstanceIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeComponentInstancesComponentInstanceId404Response struct {
}

func (response GetLandscapeComponentInstancesComponentInstanceId404Response) VisitGetLandscapeComponentInstancesComponentInstanceIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetLandscapeComponentsRequestObject struct {
}

type GetLandscapeComponentsResponseObject interface {
	VisitGetLandscapeComponentsResponse(w http.ResponseWriter) error
}

type GetLandscapeComponents200JSONResponse []struct {
	ComponentId *openapi_types.UUID `json:"componentId,omitempty"`
	DisplayName *string             `json:"displayName,omitempty"`
	Reference   *string             `json:"reference,omitempty"`
}

func (response GetLandscapeComponents200JSONResponse) VisitGetLandscapeComponentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeComponentsComponentIdRequestObject struct {
	ComponentId openapi_types.UUID `json:"componentId"`
}

type GetLandscapeComponentsComponentIdResponseObject interface {
	VisitGetLandscapeComponentsComponentIdResponse(w http.ResponseWriter) error
}

type GetLandscapeComponentsComponentId200JSONResponse Component

func (response GetLandscapeComponentsComponentId200JSONResponse) VisitGetLandscapeComponentsComponentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeComponentsComponentId404Response struct {
}

func (response GetLandscapeComponentsComponentId404Response) VisitGetLandscapeComponentsComponentIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetLandscapeFindingsRequestObject struct {
}

type GetLandscapeFindingsResponseObject interface {
	VisitGetLandscapeFindingsResponse(w http.ResponseWriter) error
}

type GetLandscapeFindings200JSONResponse []struct {
	FindingId *openapi_types.UUID `json:"findingId,omitempty"`
	Reference *string             `json:"reference,omitempty"`
	Summary   *string             `json:"summary,omitempty"`
}

func (response GetLandscapeFindings200JSONResponse) VisitGetLandscapeFindingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeFindingsFindingIdRequestObject struct {
	FindingId openapi_types.UUID `json:"findingId"`
}

type GetLandscapeFindingsFindingIdResponseObject interface {
	VisitGetLandscapeFindingsFindingIdResponse(w http.ResponseWriter) error
}

type GetLandscapeFindingsFindingId200JSONResponse Finding

func (response GetLandscapeFindingsFindingId200JSONResponse) VisitGetLandscapeFindingsFindingIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeFindingsFindingId404Response struct {
}

func (response GetLandscapeFindingsFindingId404Response) VisitGetLandscapeFindingsFindingIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetLandscapeSystemInstancesRequestObject struct {
}

type GetLandscapeSystemInstancesResponseObject interface {
	VisitGetLandscapeSystemInstancesResponse(w http.ResponseWriter) error
}

type GetLandscapeSystemInstances200JSONResponse []struct {
	DisplayName      *string             `json:"displayName,omitempty"`
	Reference        *string             `json:"reference,omitempty"`
	SystemInstanceId *openapi_types.UUID `json:"systemInstanceId,omitempty"`
}

func (response GetLandscapeSystemInstances200JSONResponse) VisitGetLandscapeSystemInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeSystemInstancesSystemInstanceIdRequestObject struct {
	SystemInstanceId openapi_types.UUID `json:"systemInstanceId"`
}

type GetLandscapeSystemInstancesSystemInstanceIdResponseObject interface {
	VisitGetLandscapeSystemInstancesSystemInstanceIdResponse(w http.ResponseWriter) error
}

type GetLandscapeSystemInstancesSystemInstanceId200JSONResponse SystemInstance

func (response GetLandscapeSystemInstancesSystemInstanceId200JSONResponse) VisitGetLandscapeSystemInstancesSystemInstanceIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeSystemInstancesSystemInstanceId404Response struct {
}

func (response GetLandscapeSystemInstancesSystemInstanceId404Response) VisitGetLandscapeSystemInstancesSystemInstanceIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetLandscapeSystemsRequestObject struct {
}

type GetLandscapeSystemsResponseObject interface {
	VisitGetLandscapeSystemsResponse(w http.ResponseWriter) error
}

type GetLandscapeSystems200JSONResponse []struct {
	DisplayName *string             `json:"displayName,omitempty"`
	Reference   *string             `json:"reference,omitempty"`
	SystemId    *openapi_types.UUID `json:"systemId,omitempty"`
}

func (response GetLandscapeSystems200JSONResponse) VisitGetLandscapeSystemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeSystemsSystemIdRequestObject struct {
	SystemId openapi_types.UUID `json:"systemId"`
}

type GetLandscapeSystemsSystemIdResponseObject interface {
	VisitGetLandscapeSystemsSystemIdResponse(w http.ResponseWriter) error
}

type GetLandscapeSystemsSystemId200JSONResponse System

func (response GetLandscapeSystemsSystemId200JSONResponse) VisitGetLandscapeSystemsSystemIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLandscapeSystemsSystemId404Response struct {
}

func (response GetLandscapeSystemsSystemId404Response) VisitGetLandscapeSystemsSystemIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetTestRequestObject struct {
}

type GetTestResponseObject interface {
	VisitGetTestResponse(w http.ResponseWriter) error
}

type GetTest200Response struct {
}

func (response GetTest200Response) VisitGetTestResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /events/query/{sequenceId})
	GetEventsQuerySequenceId(ctx context.Context, request GetEventsQuerySequenceIdRequestObject) (GetEventsQuerySequenceIdResponseObject, error)

	// (POST /events/register)
	PostEventsRegister(ctx context.Context, request PostEventsRegisterRequestObject) (PostEventsRegisterResponseObject, error)

	// (GET /landscape/api-instances)
	GetLandscapeApiInstances(ctx context.Context, request GetLandscapeApiInstancesRequestObject) (GetLandscapeApiInstancesResponseObject, error)

	// (GET /landscape/api-instances/{apiInstanceId})
	GetLandscapeApiInstancesApiInstanceId(ctx context.Context, request GetLandscapeApiInstancesApiInstanceIdRequestObject) (GetLandscapeApiInstancesApiInstanceIdResponseObject, error)

	// (GET /landscape/apis)
	GetLandscapeApis(ctx context.Context, request GetLandscapeApisRequestObject) (GetLandscapeApisResponseObject, error)

	// (GET /landscape/apis/{apiId})
	GetLandscapeApisApiId(ctx context.Context, request GetLandscapeApisApiIdRequestObject) (GetLandscapeApisApiIdResponseObject, error)

	// (GET /landscape/component-instances)
	GetLandscapeComponentInstances(ctx context.Context, request GetLandscapeComponentInstancesRequestObject) (GetLandscapeComponentInstancesResponseObject, error)

	// (GET /landscape/component-instances/{componentInstanceId})
	GetLandscapeComponentInstancesComponentInstanceId(ctx context.Context, request GetLandscapeComponentInstancesComponentInstanceIdRequestObject) (GetLandscapeComponentInstancesComponentInstanceIdResponseObject, error)

	// (GET /landscape/components)
	GetLandscapeComponents(ctx context.Context, request GetLandscapeComponentsRequestObject) (GetLandscapeComponentsResponseObject, error)

	// (GET /landscape/components/{componentId})
	GetLandscapeComponentsComponentId(ctx context.Context, request GetLandscapeComponentsComponentIdRequestObject) (GetLandscapeComponentsComponentIdResponseObject, error)

	// (GET /landscape/findings)
	GetLandscapeFindings(ctx context.Context, request GetLandscapeFindingsRequestObject) (GetLandscapeFindingsResponseObject, error)

	// (GET /landscape/findings/{findingId})
	GetLandscapeFindingsFindingId(ctx context.Context, request GetLandscapeFindingsFindingIdRequestObject) (GetLandscapeFindingsFindingIdResponseObject, error)

	// (GET /landscape/system-instances)
	GetLandscapeSystemInstances(ctx context.Context, request GetLandscapeSystemInstancesRequestObject) (GetLandscapeSystemInstancesResponseObject, error)

	// (GET /landscape/system-instances/{systemInstanceId})
	GetLandscapeSystemInstancesSystemInstanceId(ctx context.Context, request GetLandscapeSystemInstancesSystemInstanceIdRequestObject) (GetLandscapeSystemInstancesSystemInstanceIdResponseObject, error)

	// (GET /landscape/systems)
	GetLandscapeSystems(ctx context.Context, request GetLandscapeSystemsRequestObject) (GetLandscapeSystemsResponseObject, error)

	// (GET /landscape/systems/{systemId})
	GetLandscapeSystemsSystemId(ctx context.Context, request GetLandscapeSystemsSystemIdRequestObject) (GetLandscapeSystemsSystemIdResponseObject, error)

	// (GET /test)
	GetTest(ctx context.Context, request GetTestRequestObject) (GetTestResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetEventsQuerySequenceId operation middleware
func (sh *strictHandler) GetEventsQuerySequenceId(w http.ResponseWriter, r *http.Request, sequenceId string) {
	var request GetEventsQuerySequenceIdRequestObject

	request.SequenceId = sequenceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEventsQuerySequenceId(ctx, request.(GetEventsQuerySequenceIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEventsQuerySequenceId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEventsQuerySequenceIdResponseObject); ok {
		if err := validResponse.VisitGetEventsQuerySequenceIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEventsRegister operation middleware
func (sh *strictHandler) PostEventsRegister(w http.ResponseWriter, r *http.Request) {
	var request PostEventsRegisterRequestObject

	var body PostEventsRegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEventsRegister(ctx, request.(PostEventsRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEventsRegister")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEventsRegisterResponseObject); ok {
		if err := validResponse.VisitPostEventsRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeApiInstances operation middleware
func (sh *strictHandler) GetLandscapeApiInstances(w http.ResponseWriter, r *http.Request) {
	var request GetLandscapeApiInstancesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeApiInstances(ctx, request.(GetLandscapeApiInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeApiInstances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeApiInstancesResponseObject); ok {
		if err := validResponse.VisitGetLandscapeApiInstancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeApiInstancesApiInstanceId operation middleware
func (sh *strictHandler) GetLandscapeApiInstancesApiInstanceId(w http.ResponseWriter, r *http.Request, apiInstanceId openapi_types.UUID) {
	var request GetLandscapeApiInstancesApiInstanceIdRequestObject

	request.ApiInstanceId = apiInstanceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeApiInstancesApiInstanceId(ctx, request.(GetLandscapeApiInstancesApiInstanceIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeApiInstancesApiInstanceId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeApiInstancesApiInstanceIdResponseObject); ok {
		if err := validResponse.VisitGetLandscapeApiInstancesApiInstanceIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeApis operation middleware
func (sh *strictHandler) GetLandscapeApis(w http.ResponseWriter, r *http.Request) {
	var request GetLandscapeApisRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeApis(ctx, request.(GetLandscapeApisRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeApis")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeApisResponseObject); ok {
		if err := validResponse.VisitGetLandscapeApisResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeApisApiId operation middleware
func (sh *strictHandler) GetLandscapeApisApiId(w http.ResponseWriter, r *http.Request, apiId openapi_types.UUID) {
	var request GetLandscapeApisApiIdRequestObject

	request.ApiId = apiId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeApisApiId(ctx, request.(GetLandscapeApisApiIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeApisApiId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeApisApiIdResponseObject); ok {
		if err := validResponse.VisitGetLandscapeApisApiIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeComponentInstances operation middleware
func (sh *strictHandler) GetLandscapeComponentInstances(w http.ResponseWriter, r *http.Request) {
	var request GetLandscapeComponentInstancesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeComponentInstances(ctx, request.(GetLandscapeComponentInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeComponentInstances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeComponentInstancesResponseObject); ok {
		if err := validResponse.VisitGetLandscapeComponentInstancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeComponentInstancesComponentInstanceId operation middleware
func (sh *strictHandler) GetLandscapeComponentInstancesComponentInstanceId(w http.ResponseWriter, r *http.Request, componentInstanceId openapi_types.UUID) {
	var request GetLandscapeComponentInstancesComponentInstanceIdRequestObject

	request.ComponentInstanceId = componentInstanceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeComponentInstancesComponentInstanceId(ctx, request.(GetLandscapeComponentInstancesComponentInstanceIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeComponentInstancesComponentInstanceId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeComponentInstancesComponentInstanceIdResponseObject); ok {
		if err := validResponse.VisitGetLandscapeComponentInstancesComponentInstanceIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeComponents operation middleware
func (sh *strictHandler) GetLandscapeComponents(w http.ResponseWriter, r *http.Request) {
	var request GetLandscapeComponentsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeComponents(ctx, request.(GetLandscapeComponentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeComponents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeComponentsResponseObject); ok {
		if err := validResponse.VisitGetLandscapeComponentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeComponentsComponentId operation middleware
func (sh *strictHandler) GetLandscapeComponentsComponentId(w http.ResponseWriter, r *http.Request, componentId openapi_types.UUID) {
	var request GetLandscapeComponentsComponentIdRequestObject

	request.ComponentId = componentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeComponentsComponentId(ctx, request.(GetLandscapeComponentsComponentIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeComponentsComponentId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeComponentsComponentIdResponseObject); ok {
		if err := validResponse.VisitGetLandscapeComponentsComponentIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeFindings operation middleware
func (sh *strictHandler) GetLandscapeFindings(w http.ResponseWriter, r *http.Request) {
	var request GetLandscapeFindingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeFindings(ctx, request.(GetLandscapeFindingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeFindings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeFindingsResponseObject); ok {
		if err := validResponse.VisitGetLandscapeFindingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeFindingsFindingId operation middleware
func (sh *strictHandler) GetLandscapeFindingsFindingId(w http.ResponseWriter, r *http.Request, findingId openapi_types.UUID) {
	var request GetLandscapeFindingsFindingIdRequestObject

	request.FindingId = findingId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeFindingsFindingId(ctx, request.(GetLandscapeFindingsFindingIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeFindingsFindingId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeFindingsFindingIdResponseObject); ok {
		if err := validResponse.VisitGetLandscapeFindingsFindingIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeSystemInstances operation middleware
func (sh *strictHandler) GetLandscapeSystemInstances(w http.ResponseWriter, r *http.Request) {
	var request GetLandscapeSystemInstancesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeSystemInstances(ctx, request.(GetLandscapeSystemInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeSystemInstances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeSystemInstancesResponseObject); ok {
		if err := validResponse.VisitGetLandscapeSystemInstancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeSystemInstancesSystemInstanceId operation middleware
func (sh *strictHandler) GetLandscapeSystemInstancesSystemInstanceId(w http.ResponseWriter, r *http.Request, systemInstanceId openapi_types.UUID) {
	var request GetLandscapeSystemInstancesSystemInstanceIdRequestObject

	request.SystemInstanceId = systemInstanceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeSystemInstancesSystemInstanceId(ctx, request.(GetLandscapeSystemInstancesSystemInstanceIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeSystemInstancesSystemInstanceId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeSystemInstancesSystemInstanceIdResponseObject); ok {
		if err := validResponse.VisitGetLandscapeSystemInstancesSystemInstanceIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeSystems operation middleware
func (sh *strictHandler) GetLandscapeSystems(w http.ResponseWriter, r *http.Request) {
	var request GetLandscapeSystemsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeSystems(ctx, request.(GetLandscapeSystemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeSystems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeSystemsResponseObject); ok {
		if err := validResponse.VisitGetLandscapeSystemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLandscapeSystemsSystemId operation middleware
func (sh *strictHandler) GetLandscapeSystemsSystemId(w http.ResponseWriter, r *http.Request, systemId openapi_types.UUID) {
	var request GetLandscapeSystemsSystemIdRequestObject

	request.SystemId = systemId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLandscapeSystemsSystemId(ctx, request.(GetLandscapeSystemsSystemIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLandscapeSystemsSystemId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLandscapeSystemsSystemIdResponseObject); ok {
		if err := validResponse.VisitGetLandscapeSystemsSystemIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTest operation middleware
func (sh *strictHandler) GetTest(w http.ResponseWriter, r *http.Request) {
	var request GetTestRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTest(ctx, request.(GetTestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTestResponseObject); ok {
		if err := validResponse.VisitGetTestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xca2/cttL+KwO9L9AG2OzaSXqBv/mkSbE4aevGTb80gcGVRivWEqmQ1Dp7DP/3gyGp",
	"u+zVrmUnOeinxhYvD2fmeWZ4ca+DUGa5FCiMDk6uAx0mmDH7z9OzJf0nVzJHZTjaXzIhpGGGS2F/jFCH",
	"iuf0c3ASnIJGAzKGS9w+3bC0QMgZVxpiqUAbqbhYA4siTu1ZChkaFjHDgK1kYcAkCKdnS+BCGyZCnAez",
	"gBvM7Ez/rzAOToL/W9R4Fx7s4rQCFdzMArPNMTgJmFJsSz+znC+jAbAC3r1b/gQmYQYKwT8WmG6BRygM",
	"jznqEs4clgZ0Ios0ghXCGgUqZjACJiJgWvO1wAiuEhT1AjSECqtGWaENKMwYFxBKuzharJLFOmms+xsN",
	"KY8x3IYpzuGPBCHmmEY0msy9xbgALTOkYQx+MnoGuggTYNoBsLNaI4PAK4vlKkGFdorlT5CxbXsNq639",
	"pLfaYAbcaExjMnssVcZMcBIUBY+CyqbakAvJqC1b9uNgpTjG0PgtRUW9zrxQudRorRMXInSr42Y7H5yL",
	"6zxl219Zhv25yE5JkTHxVCGL2CpFECzDxnyDY7oVDw9nw8L395axQZIrueGRjQyuy5F3Wsr9Ymge+tLA",
	"Cd/ifD2fwW85itOz5QzWb89ezuBnxfLk9zdP5rB0TW03rqEQl0JeiRnwZnwSA42E98E79/l90O4YSdQg",
	"pIGYG2BiC7nCCGNOQRwyg2upOOrbBv3NJKjskMJFXsg0tW6QOkLDeKo7nLZz1wN6U0YU0NSkGSk26sm0",
	"KIosOPmrXEkwC7xpglngrRLMArISfSJkwYebWbBBpX1Y3iUaf/pmNzezQOHHgiuMaLZmtHnvfajcKld/",
	"Y2jIrQ3N6Tn3LeYKNc0GrKOFUGiMrB6WSirWPsi0pYOkdQCJEEluaZ9X2as3VkpkhCnZpq3Kl7gdDrFL",
	"3JYRViu3UzRUG9SkHPSxkj1lsbXbExo1TE27sOGp3ZqZ1jLkVmuuuEm6I1/i1qKpqNUIJC4ct6x6qDpZ",
	"KEzteEba0WiIPrSOU8lAJdpBb+Z86bPO/0rO261tlpckbFbPSgSgkKX8P6gpB1EmY4IYm2JsALPcbIHX",
	"3RVqWagQIWFOVVZYpiGMYItmBqvCwBVPUzCKr9dIge8CqoztmIuIjJRybUYpKquddZ/EXtt8vwxfGeqA",
	"NF/2nT7XV6geKuHfLwm3AvyWbNxk4KisXK3ZuprsxLio03PDwXdH8nlr+s8R1B25akd42/hD8vWy1IfH",
	"F69KmiZSrqrDwdSuEe3H66rfIcSuOk/P7BrXA1Gb1lRkOBgfFL8UIEQnMr1uZIwaWDlCKwZGVsa16w/d",
	"UzRt/3g7i1bg90YuC5rDbVqOcD+bHrLPaQtpa50755+0+Pbg71S8z1e2NfRi2uItbKr53W6rMdxVyI0T",
	"gY5B76+//xRYD6HCFY7bpaNqMpEuT6GSdxeAY+Vyn8VPKaCTlqbDNtmvQhyi66wjn7WO9JbRCLeG8YeE",
	"9rUrZO885GgWvDIGBqpIETZcpv684W2RorZcQW7PN1YI5aGTFVzMmDA8hFAqhaERqHVpUHvkAdIdTNCS",
	"Uu5iO8HwUgNbk2EN4CeDilitcF24ed2BCq04YirS/WOTTsHRiwW/JqeEOyOn3DbYoUelgbe+x1uMB0Ov",
	"yDKmtgPQOsFQ46w7NfEM+bUMhTdcm9GAm52WlJoHUPfa9BJzR096huStDDTC7jEq9OSsWys+SKKeIZpO",
	"6EHdY+za4HvGyx+jDoirTWkFqXVG6rawwSxwx6MvG9Q/71K/edg1VEl96MZXY2Ed2EORdX5Lydk6Fa1k",
	"cuB4E06rz9Q04evkaYobTN2x6NZpqo8iamFVAT/BChO24VLZegNFyHJNUoAaNkxxWdhTAa8KMjZXTDUS",
	"1IA+sJU2ioUDddhSRDy0I18laBWtqf0ayp7wrVEFPgErXSJUaBC+jVmq8ckcTstG1fmvoqzFM6Z4unUn",
	"xUaCKu1Wa1zZoXkt4dbmZd3WIaye0yMrNfeKm8SbPmUi0iHLm3l5JWWKzNamD11EO2ATFc6HbiAdiPvu",
	"HvtFDVOjinjXzqOYAY+B5XnKQyqm/NFVv3i1dHHFp8y4odKTtyoQd3jlB3eM0IatUq4TdLRCxVSY8NAm",
	"TZ8yE57DCs0VoiijbFT16uuLQ/cMPgz22yecV3Tbd5dwXjp84j2CN/0D7RAm3VtX2na7hH++rXWniJ5K",
	"Hu6xjxlANMmd8j127O2S/p7U+2evPp6JHV71/DAbf4z1Z03ptuv8h9YlqL01TlNw3cfeDbMN4ynF82sl",
	"h4KTZ5QXshy4q2nIit69XIPXHFhhKDPKG+Voc3htgZGXnh0dff/06Pjp0bM5/OKMXF6DFKZQ2DRpxAw+",
	"Nby+XG+/KskVUl0V3Qssd3UQj1BhBPWgc3jpyiOlyxBnG8kjKDQN1BqDxcZWdVwDQd5nuXP4haJ/RcWV",
	"G4QJaLlhPtoiBlXGxcQWqQdtWsRSVkhDhedhtuivuu3Q8cve3MaLc6OKkIwcVehcr/L1zPvgeH40P3of",
	"PHFSQouRcX3C4HtRD65BUVhnKCK3m7qb6CWoPpFv7K41lgMSfLakGv5jgWoLNsuFMk0xNNInRCYAM1Rr",
	"AoTCoMoV192ynJuUpntVNnxVN3xTNgS386ssFxzNj+dHZEyZo7APAoLn86P5c1IIZhIrDgvc2ARq8S2u",
	"NX4s0IrYDX1doxnaxhnFcYMQJkysUYPm7pwLYc03VDb6QWD5E4EnLbL6RRkq+BnNKzvl7zTjeTWfBaVY",
	"hgaVDk7+ug44TUZAg1kgbMoOdLN57RnaYs38y8Whw5IPdtOaS6GdIj47Ouov67d/k6meH/3Y//RaFiLy",
	"hXhjcfVTKvzEtbFpj6xQKKqnTaFE/eiFehpmCqJhZJMltRT4yXe2J2cC4b3wSlLOM39vS5kXRy/6uH6V",
	"Biy2b9zJBluT5QLnUreLL/2rcM21QWVLOakH3epa+Axq+5W7SdX345nU3pFlR+8S1OZfMrKHVjZXuw2Q",
	"39BQ98Xf2hG7dlg7YYUsTVcsvHyn0kNOdNqspdi46fn/uL/+l654ud2SFSMXLOdPywpD7+YJpezm2XWV",
	"uFsc79GkInbjuEYHw6E82tJjD/ecGfsMaRinQk/UPb7QpTDfba7FdettwwiZKd8T2oNlnWPIYx62LwNW",
	"WyrebK073pSnnTcWu+Wn+yrjdgXaVUB+eEA3Nk/3bvHiLj052M/j2XAACb7W4Pcxf79Y3yfEbWiPD+kv",
	"OJTPlo8bwhWGffW9f6W3b4D3juG/ynAfMODieuCu8mAuDNzzjqZG38QvB29Rd9Nm+Pb1yyRR/37n81Bq",
	"XyYdTKB7E6c6auzUpe2Xifu+mJ363rJ9uvkAFG4xdwrG7k/UBkH3JeZXQMjHJaJ/JDCShmXrPUn4upzk",
	"YSi474OMPS7v73xsMSn5vrtQXF/e6p/FdbXKgzlXPsYZzbjSb68bL0l2s6357uTL5Fr5emlypt3iRHfU",
	"v2/12LmC2Zd07du6h+LehOls+O5q963Lo+XArhsX113AB1Oz+z5wNEU7Xj7v3zqNOEDtd/oyedu5gH7U",
	"ROmfPexD3cMY+zUx9ctkaE3MexNyTx6W/NuLd1863x6DZwbd7YN3Vc/Of9D3sRc2Nxaw/VNmb/xCpcFJ",
	"kBiT65PFAjMkOPNUhixdbI4DMqIH2h3PXdE179v9HxhXC4LYXgTVbq2XejPrDociyiWnbWwsFWCKmd3T",
	"th41E2cZt3eRRkKeMI1wXDZpXevbl3yoRP3X4lAZdgZcGFQxo8rBvm3slBMNxC2HTAf62U7Q7tGJsf9r",
	"ASVTj5SFIWoNGRNsbedqQn12wVk2IcjnO0HKOLb34yHL2Yqn7i/w7R/lqwiVpqH8jRiNo7HVsAn9+UXz",
	"y4RreLFzDaHUhuwqC+EexIgIVjxNuVg3Eb648L+cENx3O8FZR9M/qHh2sYphofwDyxKbr62nA/b9bs+v",
	"SEScx7YzSOV6XRovk4K7R2tNjN9ftLpMCPaH3S5mOQu52UKeMlHBHOTQDxdl4wkR/rgTIfNPHZhhqWzZ",
	"7ccL+nLhvwyAUtU9tIj8swmLbuMejtsnguXLg6Giy0/kr25vPtz8NwAA///UHLvd4kgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
