package oapi

import openapi_types "github.com/oapi-codegen/runtime/types"

// Finding is the wire/replication DTO for finding resources. It is defined in the
// OpenAPI spec but not generated by oapi-codegen because no HTTP operation uses it directly.
type Finding struct {
	FindingId   openapi_types.UUID  `json:"findingId"`
	DisplayName string              `json:"displayName"`
	Description *string             `json:"description,omitempty"`
	Type        *openapi_types.UUID `json:"type,omitempty"`
	Resources   []ResourceRef       `json:"resources"`
	Annotations *[]Annotation       `json:"annotations,omitempty"`
}
