// Code generated by tools/gen. DO NOT EDIT.

package capacity

import (
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/annotations"
	"go.emeland.io/modelsrv/pkg/model/context"
)

// ensure Capacity interface is implemented correctly
var _ Capacity = (*capacityData)(nil)

// ensure events.EventSink interface is implemented correctly
var _ events.EventSink = (*capacityData)(nil)

type Capacity interface {
	GetCapacityId() uuid.UUID
	GetResourceId() uuid.UUID
	GetResourceName() string

	GetDisplayName() string
	SetDisplayName(string)

	GetDescription() string
	SetDescription(string)

	GetCategory() Category
	SetCategory(Category)

	GetAmount() Amount
	SetAmount(Amount)

	GetAnnotations() annotations.Annotations
	SetAnnotations(annotations.Annotations)

	GetCapacityResourceType() (CapacityResourceType, error)
	GetCapacityResourceTypeId() uuid.UUID
	SetResourceTypeRef(*CapacityResourceTypeRef)
	SetCapacityResourceTypeByRef(capacityResourceType CapacityResourceType)
	SetCapacityResourceTypeById(capacityResourceTypeId uuid.UUID)
	GetContext() (context.Context, error)
	GetContextId() uuid.UUID
	SetContextRef(*context.ContextRef)
	SetContextByRef(ctx context.Context)
	SetContextById(contextId uuid.UUID)

	Register(sink events.EventSink)
}

type capacityData struct {
	sink         events.EventSink
	isRegistered bool

	CapacityId      uuid.UUID
	DisplayName     string
	Description     string
	ResourceTypeRef *CapacityResourceTypeRef
	ContextRef      *context.ContextRef
	Category        Category
	Amount          Amount
	Annotations     annotations.Annotations
}

// NewCapacity constructs an unregistered resource; call [Capacity.Register] after adding to the model.
func NewCapacity(id uuid.UUID) Capacity {
	retval := &capacityData{
		isRegistered: false,
		CapacityId:   id,
	}

	retval.Annotations = annotations.NewAnnotations(retval)

	return retval
}

// GetCapacityId implements [Capacity].
func (o *capacityData) GetCapacityId() uuid.UUID {
	return o.CapacityId
}

// GetResourceId implements the hasIdAndName interface.
func (o *capacityData) GetResourceId() uuid.UUID {
	return o.CapacityId
}

// GetResourceName implements the hasIdAndName interface.
func (o *capacityData) GetResourceName() string {
	return o.DisplayName
}

// GetDisplayName implements [DisplayName].
func (o *capacityData) GetDisplayName() string {
	return o.DisplayName
}

// SetDisplayName implements [Capacity].
func (o *capacityData) SetDisplayName(val string) {
	o.DisplayName = val

	if o.isRegistered {
		o.sink.Receive(events.CapacityResource, events.UpdateOperation, o.CapacityId, o)
	}
}

// GetDescription implements [Description].
func (o *capacityData) GetDescription() string {
	return o.Description
}

// SetDescription implements [Capacity].
func (o *capacityData) SetDescription(val string) {
	o.Description = val

	if o.isRegistered {
		o.sink.Receive(events.CapacityResource, events.UpdateOperation, o.CapacityId, o)
	}
}

// GetCategory implements [Category].
func (o *capacityData) GetCategory() Category {
	return o.Category
}

// SetCategory implements [Capacity].
func (o *capacityData) SetCategory(val Category) {
	o.Category = val

	if o.isRegistered {
		o.sink.Receive(events.CapacityResource, events.UpdateOperation, o.CapacityId, o)
	}
}

// GetAmount implements [Amount].
func (o *capacityData) GetAmount() Amount {
	return o.Amount
}

// SetAmount implements [Capacity].
func (o *capacityData) SetAmount(val Amount) {
	o.Amount = val

	if o.isRegistered {
		o.sink.Receive(events.CapacityResource, events.UpdateOperation, o.CapacityId, o)
	}
}

// GetAnnotations implements [Annotations].
func (o *capacityData) GetAnnotations() annotations.Annotations {
	return o.Annotations
}

// SetAnnotations implements [Capacity].
func (o *capacityData) SetAnnotations(val annotations.Annotations) {
	o.Annotations = val

	if o.isRegistered {
		o.sink.Receive(events.CapacityResource, events.UpdateOperation, o.CapacityId, o)
	}
}

// GetCapacityResourceType returns the embedded [CapacityResourceType] when present (otherwise nil). Resolve by id via [Model.GetCapacityResourceTypeById].
func (o *capacityData) GetCapacityResourceType() (CapacityResourceType, error) {
	if o.ResourceTypeRef == nil {
		return nil, nil
	}
	return o.ResourceTypeRef.ResolvedCapacityResourceType(), nil
}

// SetResourceTypeRef sets the low-level type reference and emits when registered.
func (o *capacityData) SetResourceTypeRef(val *CapacityResourceTypeRef) {
	o.ResourceTypeRef = val

	if o.isRegistered {
		o.sink.Receive(events.CapacityResource, events.UpdateOperation, o.CapacityId, o)
	}
}

// SetCapacityResourceTypeByRef sets the type from a [CapacityResourceType] by building a [CapacityResourceTypeRef].
func (o *capacityData) SetCapacityResourceTypeByRef(res CapacityResourceType) {
	if res == nil {
		o.SetResourceTypeRef(nil)
		return
	}
	o.SetResourceTypeRef(&CapacityResourceTypeRef{
		CapacityResourceType:   res,
		CapacityResourceTypeId: res.GetCapacityResourceTypeId(),
	})
}

// GetCapacityResourceTypeId returns the type id when set.
func (o *capacityData) GetCapacityResourceTypeId() uuid.UUID {
	if o.ResourceTypeRef == nil {
		return uuid.Nil
	}
	return o.ResourceTypeRef.EffectiveCapacityResourceTypeID()
}

// SetCapacityResourceTypeById records only the type id (resolved object may be nil).
func (o *capacityData) SetCapacityResourceTypeById(capacityResourceTypeId uuid.UUID) {
	if capacityResourceTypeId == uuid.Nil {
		o.SetResourceTypeRef(nil)
		return
	}
	o.SetResourceTypeRef(&CapacityResourceTypeRef{CapacityResourceTypeId: capacityResourceTypeId})
}

// SetContextByRef sets the reference from the given [Context].
func (o *capacityData) SetContextByRef(ctx context.Context) {

	if ctx == nil {
		o.SetContextRef(nil)
		return
	}

	o.SetContextRef(&context.ContextRef{
		Context:   ctx,
		ContextId: ctx.GetContextId(),
	})
}

// Register implements [Capacity].
func (o *capacityData) Register(sink events.EventSink) {
	o.sink = sink
	o.isRegistered = true
}

// Receive implements [events.EventSink].
func (o *capacityData) Receive(resType events.ResourceType, op events.Operation, resourceId uuid.UUID, object ...any) error {
	if resType != events.AnnotationsResource {
		return fmt.Errorf("unsupported resource type %v in Capacity event sink. Only Annotations are supported", resType)
	}

	if o.isRegistered {
		return o.sink.Receive(events.CapacityResource, events.UpdateOperation, o.CapacityId, o)
	}

	return nil
}
