// Code generated by generate_events.go. DO NOT EDIT.

package finding

import (
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/annotations"
)

// ensure FindingType interface is implemented correctly
var _ FindingType = (*findingtypeData)(nil)

// ensure events.EventSink interface is implemented correctly
var _ events.EventSink = (*findingtypeData)(nil)

type FindingType interface {
	GetFindingTypeId() uuid.UUID
	GetResourceId() uuid.UUID
	GetResourceName() string

	GetDisplayName() string
	SetDisplayName(string)

	GetDescription() string
	SetDescription(string)

	GetAnnotations() annotations.Annotations
	SetAnnotations(annotations.Annotations)

	Register()
}

type findingtypeData struct {
	sink         events.EventSink
	isRegistered bool

	FindingTypeId uuid.UUID
	DisplayName   string
	Description   string
	Annotations   annotations.Annotations
}

// NewFindingType constructs a resource that forwards model changes through sink via [events.EventSink.Receive].
func NewFindingType(sink events.EventSink, id uuid.UUID) FindingType {
	retval := &findingtypeData{
		sink:          sink,
		isRegistered:  false,
		FindingTypeId: id,
	}

	retval.Annotations = annotations.NewAnnotations(retval)

	return retval
}

// GetFindingTypeId implements [FindingType].
func (o *findingtypeData) GetFindingTypeId() uuid.UUID {
	return o.FindingTypeId
}

// GetResourceId implements the hasIdAndName interface.
func (o *findingtypeData) GetResourceId() uuid.UUID {
	return o.FindingTypeId
}

// GetResourceName implements the hasIdAndName interface.
func (o *findingtypeData) GetResourceName() string {
	return o.DisplayName
}

// GetDisplayName implements [DisplayName].
func (o *findingtypeData) GetDisplayName() string {
	return o.DisplayName
}

// SetDisplayName implements [FindingType].
func (o *findingtypeData) SetDisplayName(val string) {
	o.DisplayName = val

	if o.isRegistered {
		o.sink.Receive(events.FindingTypeResource, events.UpdateOperation, o.FindingTypeId, o)
	}
}

// GetDescription implements [Description].
func (o *findingtypeData) GetDescription() string {
	return o.Description
}

// SetDescription implements [FindingType].
func (o *findingtypeData) SetDescription(val string) {
	o.Description = val

	if o.isRegistered {
		o.sink.Receive(events.FindingTypeResource, events.UpdateOperation, o.FindingTypeId, o)
	}
}

// GetAnnotations implements [Annotations].
func (o *findingtypeData) GetAnnotations() annotations.Annotations {
	return o.Annotations
}

// SetAnnotations implements [FindingType].
func (o *findingtypeData) SetAnnotations(val annotations.Annotations) {
	o.Annotations = val

	if o.isRegistered {
		o.sink.Receive(events.FindingTypeResource, events.UpdateOperation, o.FindingTypeId, o)
	}
}

// Register implements [FindingType].
func (o *findingtypeData) Register() {
	o.isRegistered = true
}

// Receive implements [events.EventSink].
func (o *findingtypeData) Receive(resType events.ResourceType, op events.Operation, resourceId uuid.UUID, object ...any) error {
	if resType != events.AnnotationsResource {
		return fmt.Errorf("unsupported resource type %v in FindingType event sink. Only Annotations are supported", resType)
	}

	if o.isRegistered {
		return o.sink.Receive(events.FindingTypeResource, events.UpdateOperation, o.FindingTypeId, o)
	}

	return nil
}
