// Code generated by tools/gen. DO NOT EDIT.

package context

import (
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/annotations"
)

// ensure Context interface is implemented correctly
var _ Context = (*contextData)(nil)

// ensure events.EventSink interface is implemented correctly
var _ events.EventSink = (*contextData)(nil)

type Context interface {
	GetContextId() uuid.UUID
	GetResourceId() uuid.UUID
	GetResourceName() string

	GetDisplayName() string
	SetDisplayName(string)

	GetDescription() string
	SetDescription(string)

	GetAnnotations() annotations.Annotations
	SetAnnotations(annotations.Annotations)

	GetContextType() (ContextType, error)
	GetContextTypeId() uuid.UUID
	SetTypeRef(*ContextTypeRef)
	SetContextTypeByRef(contextType ContextType)
	SetContextTypeById(contextTypeId uuid.UUID)
	GetParent() (Context, error)
	GetParentId() uuid.UUID
	SetParent(*ContextRef)
	SetParentByRef(parent Context)
	SetParentById(parentId uuid.UUID)

	Register()
}

type contextData struct {
	sink         events.EventSink
	isRegistered bool

	ContextId   uuid.UUID
	DisplayName string
	Description string
	TypeRef     *ContextTypeRef
	Parent      *ContextRef
	Annotations annotations.Annotations
}

// NewContext constructs a resource that forwards model changes through sink via [events.EventSink.Receive].
func NewContext(sink events.EventSink, id uuid.UUID) Context {
	retval := &contextData{
		sink:         sink,
		isRegistered: false,
		ContextId:    id,
	}

	retval.Annotations = annotations.NewAnnotations(retval)

	return retval
}

// GetContextId implements [Context].
func (o *contextData) GetContextId() uuid.UUID {
	return o.ContextId
}

// GetResourceId implements the hasIdAndName interface.
func (o *contextData) GetResourceId() uuid.UUID {
	return o.ContextId
}

// GetResourceName implements the hasIdAndName interface.
func (o *contextData) GetResourceName() string {
	return o.DisplayName
}

// GetDisplayName implements [DisplayName].
func (o *contextData) GetDisplayName() string {
	return o.DisplayName
}

// SetDisplayName implements [Context].
func (o *contextData) SetDisplayName(val string) {
	o.DisplayName = val

	if o.isRegistered {
		o.sink.Receive(events.ContextResource, events.UpdateOperation, o.ContextId, o)
	}
}

// GetDescription implements [Description].
func (o *contextData) GetDescription() string {
	return o.Description
}

// SetDescription implements [Context].
func (o *contextData) SetDescription(val string) {
	o.Description = val

	if o.isRegistered {
		o.sink.Receive(events.ContextResource, events.UpdateOperation, o.ContextId, o)
	}
}

// GetAnnotations implements [Annotations].
func (o *contextData) GetAnnotations() annotations.Annotations {
	return o.Annotations
}

// SetAnnotations implements [Context].
func (o *contextData) SetAnnotations(val annotations.Annotations) {
	o.Annotations = val

	if o.isRegistered {
		o.sink.Receive(events.ContextResource, events.UpdateOperation, o.ContextId, o)
	}
}

// GetParent returns the embedded parent [Context] when present (otherwise nil). Resolve by id via [Model.GetContextById].
func (o *contextData) GetParent() (Context, error) {
	if o.Parent == nil {
		return nil, nil
	}
	return o.Parent.ResolvedContext(), nil
}

// GetParentId returns the parent id when set.
func (o *contextData) GetParentId() uuid.UUID {
	if o.Parent == nil {
		return uuid.Nil
	}
	return o.Parent.EffectiveParentContextID()
}

// SetParent sets the low-level parent reference and emits when registered.
func (o *contextData) SetParent(val *ContextRef) {
	o.Parent = val

	if o.isRegistered {
		o.sink.Receive(events.ContextResource, events.UpdateOperation, o.ContextId, o)
	}
}

// SetParentByRef sets the parent from a [Context] by building a [ContextRef].
func (o *contextData) SetParentByRef(parent Context) {
	if parent == nil {
		o.SetParent(nil)
		return
	}
	o.SetParent(&ContextRef{
		Context:   parent,
		ContextId: parent.GetContextId(),
	})
}

// SetParentById records only the parent id (resolved object may be nil).
func (o *contextData) SetParentById(parentId uuid.UUID) {
	if parentId == uuid.Nil {
		o.SetParent(nil)
		return
	}
	o.SetParent(&ContextRef{ContextId: parentId})
}

// GetContextType returns the embedded [ContextType] when present (otherwise nil). Resolve by id via [Model.GetContextTypeById].
func (o *contextData) GetContextType() (ContextType, error) {
	if o.TypeRef == nil {
		return nil, nil
	}
	return o.TypeRef.ResolvedContextType(), nil
}

// SetTypeRef sets the low-level type reference and emits when registered.
func (o *contextData) SetTypeRef(val *ContextTypeRef) {
	o.TypeRef = val

	if o.isRegistered {
		o.sink.Receive(events.ContextResource, events.UpdateOperation, o.ContextId, o)
	}
}

// SetContextTypeByRef sets the type from a [ContextType] by building a [ContextTypeRef].
func (o *contextData) SetContextTypeByRef(res ContextType) {
	if res == nil {
		o.SetTypeRef(nil)
		return
	}
	o.SetTypeRef(&ContextTypeRef{
		ContextType:   res,
		ContextTypeId: res.GetContextTypeId(),
	})
}

// GetContextTypeId returns the type id when set.
func (o *contextData) GetContextTypeId() uuid.UUID {
	if o.TypeRef == nil {
		return uuid.Nil
	}
	return o.TypeRef.EffectiveContextTypeID()
}

// SetContextTypeById records only the type id (resolved object may be nil).
func (o *contextData) SetContextTypeById(contextTypeId uuid.UUID) {
	if contextTypeId == uuid.Nil {
		o.SetTypeRef(nil)
		return
	}
	o.SetTypeRef(&ContextTypeRef{ContextTypeId: contextTypeId})
}

// Register implements [Context].
func (o *contextData) Register() {
	o.isRegistered = true
}

// Receive implements [events.EventSink].
func (o *contextData) Receive(resType events.ResourceType, op events.Operation, resourceId uuid.UUID, object ...any) error {
	if resType != events.AnnotationsResource {
		return fmt.Errorf("unsupported resource type %v in Context event sink. Only Annotations are supported", resType)
	}

	if o.isRegistered {
		return o.sink.Receive(events.ContextResource, events.UpdateOperation, o.ContextId, o)
	}

	return nil
}
