// Code generated by tools/gen. DO NOT EDIT.

package order

import (
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/annotations"
	"go.emeland.io/modelsrv/pkg/model/iam"
)

// ensure Order interface is implemented correctly
var _ Order = (*orderData)(nil)

// ensure events.EventSink interface is implemented correctly
var _ events.EventSink = (*orderData)(nil)

type Order interface {
	GetOrderId() uuid.UUID
	GetResourceId() uuid.UUID
	GetResourceName() string

	GetDisplayName() string
	SetDisplayName(string)

	GetItems() []OrderItemRef
	SetItems([]OrderItemRef)

	GetAnnotations() annotations.Annotations
	SetAnnotations(annotations.Annotations)

	GetOrgUnit() (iam.OrgUnit, error)
	GetOrgUnitId() uuid.UUID
	SetOrgUnitRef(*iam.OrgUnitRef)
	SetOrgUnitByRef(orgUnit iam.OrgUnit)
	SetOrgUnitById(orgUnitId uuid.UUID)

	Register(sink events.EventSink)
}

type orderData struct {
	sink         events.EventSink
	isRegistered bool

	OrderId     uuid.UUID
	DisplayName string
	OrgUnitRef  *iam.OrgUnitRef
	Items       []OrderItemRef
	Annotations annotations.Annotations
}

// NewOrder constructs an unregistered resource; call [Order.Register] after adding to the model.
func NewOrder(id uuid.UUID) Order {
	retval := &orderData{
		isRegistered: false,
		OrderId:      id,
	}

	retval.Annotations = annotations.NewAnnotations(retval)

	return retval
}

// GetOrderId implements [Order].
func (o *orderData) GetOrderId() uuid.UUID {
	return o.OrderId
}

// GetResourceId implements the hasIdAndName interface.
func (o *orderData) GetResourceId() uuid.UUID {
	return o.OrderId
}

// GetResourceName implements the hasIdAndName interface.
func (o *orderData) GetResourceName() string {
	return o.DisplayName
}

// GetDisplayName implements [DisplayName].
func (o *orderData) GetDisplayName() string {
	return o.DisplayName
}

// SetDisplayName implements [Order].
func (o *orderData) SetDisplayName(val string) {
	o.DisplayName = val

	if o.isRegistered {
		o.sink.Receive(events.OrderResource, events.UpdateOperation, o.OrderId, o)
	}
}

// GetItems implements [Items].
func (o *orderData) GetItems() []OrderItemRef {
	return o.Items
}

// SetItems implements [Order].
func (o *orderData) SetItems(val []OrderItemRef) {
	o.Items = val

	if o.isRegistered {
		o.sink.Receive(events.OrderResource, events.UpdateOperation, o.OrderId, o)
	}
}

// GetAnnotations implements [Annotations].
func (o *orderData) GetAnnotations() annotations.Annotations {
	return o.Annotations
}

// SetAnnotations implements [Order].
func (o *orderData) SetAnnotations(val annotations.Annotations) {
	o.Annotations = val

	if o.isRegistered {
		o.sink.Receive(events.OrderResource, events.UpdateOperation, o.OrderId, o)
	}
}

// SetOrgUnitByRef sets the reference from the given [OrgUnit].
func (o *orderData) SetOrgUnitByRef(orgUnit iam.OrgUnit) {

	if orgUnit == nil {
		o.SetOrgUnitRef(nil)
		return
	}

	o.SetOrgUnitRef(&iam.OrgUnitRef{
		OrgUnit:   orgUnit,
		OrgUnitId: orgUnit.GetOrgUnitId(),
	})
}

// Register implements [Order].
func (o *orderData) Register(sink events.EventSink) {
	o.sink = sink
	o.isRegistered = true
}

// Receive implements [events.EventSink].
func (o *orderData) Receive(resType events.ResourceType, op events.Operation, resourceId uuid.UUID, object ...any) error {
	if resType != events.AnnotationsResource {
		return fmt.Errorf("unsupported resource type %v in Order event sink. Only Annotations are supported", resType)
	}

	if o.isRegistered {
		return o.sink.Receive(events.OrderResource, events.UpdateOperation, o.OrderId, o)
	}

	return nil
}
