// Code generated by MockGen. DO NOT EDIT.
// Source: go.emeland.io/modelsrv/pkg/model (interfaces: Model)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_model.go -package=mocks . Model
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	events "go.emeland.io/modelsrv/pkg/events"
	api "go.emeland.io/modelsrv/pkg/model/api"
	component "go.emeland.io/modelsrv/pkg/model/component"
	context "go.emeland.io/modelsrv/pkg/model/context"
	finding "go.emeland.io/modelsrv/pkg/model/finding"
	node "go.emeland.io/modelsrv/pkg/model/node"
	system "go.emeland.io/modelsrv/pkg/model/system"
	gomock "go.uber.org/mock/gomock"
)

// MockModel is a mock of Model interface.
type MockModel struct {
	ctrl     *gomock.Controller
	recorder *MockModelMockRecorder
	isgomock struct{}
}

// MockModelMockRecorder is the mock recorder for MockModel.
type MockModelMockRecorder struct {
	mock *MockModel
}

// NewMockModel creates a new mock instance.
func NewMockModel(ctrl *gomock.Controller) *MockModel {
	mock := &MockModel{ctrl: ctrl}
	mock.recorder = &MockModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModel) EXPECT() *MockModelMockRecorder {
	return m.recorder
}

// AddApi mocks base method.
func (m *MockModel) AddApi(a api.API) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddApi", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddApi indicates an expected call of AddApi.
func (mr *MockModelMockRecorder) AddApi(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddApi", reflect.TypeOf((*MockModel)(nil).AddApi), a)
}

// AddApiInstance mocks base method.
func (m *MockModel) AddApiInstance(instance api.ApiInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddApiInstance", instance)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddApiInstance indicates an expected call of AddApiInstance.
func (mr *MockModelMockRecorder) AddApiInstance(instance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddApiInstance", reflect.TypeOf((*MockModel)(nil).AddApiInstance), instance)
}

// AddComponent mocks base method.
func (m *MockModel) AddComponent(comp component.Component) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComponent", comp)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddComponent indicates an expected call of AddComponent.
func (mr *MockModelMockRecorder) AddComponent(comp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComponent", reflect.TypeOf((*MockModel)(nil).AddComponent), comp)
}

// AddComponentInstance mocks base method.
func (m *MockModel) AddComponentInstance(instance component.ComponentInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComponentInstance", instance)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddComponentInstance indicates an expected call of AddComponentInstance.
func (mr *MockModelMockRecorder) AddComponentInstance(instance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComponentInstance", reflect.TypeOf((*MockModel)(nil).AddComponentInstance), instance)
}

// AddContext mocks base method.
func (m *MockModel) AddContext(c context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContext", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddContext indicates an expected call of AddContext.
func (mr *MockModelMockRecorder) AddContext(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContext", reflect.TypeOf((*MockModel)(nil).AddContext), c)
}

// AddContextType mocks base method.
func (m *MockModel) AddContextType(contextType context.ContextType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContextType", contextType)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddContextType indicates an expected call of AddContextType.
func (mr *MockModelMockRecorder) AddContextType(contextType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContextType", reflect.TypeOf((*MockModel)(nil).AddContextType), contextType)
}

// AddFinding mocks base method.
func (m *MockModel) AddFinding(f finding.Finding, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFinding", f, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFinding indicates an expected call of AddFinding.
func (mr *MockModelMockRecorder) AddFinding(f, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFinding", reflect.TypeOf((*MockModel)(nil).AddFinding), f, name)
}

// AddFindingType mocks base method.
func (m *MockModel) AddFindingType(findingType finding.FindingType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFindingType", findingType)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFindingType indicates an expected call of AddFindingType.
func (mr *MockModelMockRecorder) AddFindingType(findingType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFindingType", reflect.TypeOf((*MockModel)(nil).AddFindingType), findingType)
}

// AddNode mocks base method.
func (m *MockModel) AddNode(n node.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNode", n)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNode indicates an expected call of AddNode.
func (mr *MockModelMockRecorder) AddNode(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNode", reflect.TypeOf((*MockModel)(nil).AddNode), n)
}

// AddNodeType mocks base method.
func (m *MockModel) AddNodeType(nodeType node.NodeType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNodeType", nodeType)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNodeType indicates an expected call of AddNodeType.
func (mr *MockModelMockRecorder) AddNodeType(nodeType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNodeType", reflect.TypeOf((*MockModel)(nil).AddNodeType), nodeType)
}

// AddSystem mocks base method.
func (m *MockModel) AddSystem(sys system.System) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSystem", sys)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSystem indicates an expected call of AddSystem.
func (mr *MockModelMockRecorder) AddSystem(sys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSystem", reflect.TypeOf((*MockModel)(nil).AddSystem), sys)
}

// AddSystemInstance mocks base method.
func (m *MockModel) AddSystemInstance(instance system.SystemInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSystemInstance", instance)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSystemInstance indicates an expected call of AddSystemInstance.
func (mr *MockModelMockRecorder) AddSystemInstance(instance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSystemInstance", reflect.TypeOf((*MockModel)(nil).AddSystemInstance), instance)
}

// ApiRefByID mocks base method.
func (m *MockModel) ApiRefByID(apiId uuid.UUID) *api.ApiRef {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApiRefByID", apiId)
	ret0, _ := ret[0].(*api.ApiRef)
	return ret0
}

// ApiRefByID indicates an expected call of ApiRefByID.
func (mr *MockModelMockRecorder) ApiRefByID(apiId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApiRefByID", reflect.TypeOf((*MockModel)(nil).ApiRefByID), apiId)
}

// Apply mocks base method.
func (m *MockModel) Apply(ev events.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockModelMockRecorder) Apply(ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockModel)(nil).Apply), ev)
}

// DeleteApiById mocks base method.
func (m *MockModel) DeleteApiById(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApiById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApiById indicates an expected call of DeleteApiById.
func (mr *MockModelMockRecorder) DeleteApiById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiById", reflect.TypeOf((*MockModel)(nil).DeleteApiById), id)
}

// DeleteApiInstanceById mocks base method.
func (m *MockModel) DeleteApiInstanceById(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApiInstanceById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApiInstanceById indicates an expected call of DeleteApiInstanceById.
func (mr *MockModelMockRecorder) DeleteApiInstanceById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiInstanceById", reflect.TypeOf((*MockModel)(nil).DeleteApiInstanceById), id)
}

// DeleteComponentById mocks base method.
func (m *MockModel) DeleteComponentById(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComponentById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComponentById indicates an expected call of DeleteComponentById.
func (mr *MockModelMockRecorder) DeleteComponentById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComponentById", reflect.TypeOf((*MockModel)(nil).DeleteComponentById), id)
}

// DeleteComponentInstanceById mocks base method.
func (m *MockModel) DeleteComponentInstanceById(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComponentInstanceById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComponentInstanceById indicates an expected call of DeleteComponentInstanceById.
func (mr *MockModelMockRecorder) DeleteComponentInstanceById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComponentInstanceById", reflect.TypeOf((*MockModel)(nil).DeleteComponentInstanceById), id)
}

// DeleteContextById mocks base method.
func (m *MockModel) DeleteContextById(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContextById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContextById indicates an expected call of DeleteContextById.
func (mr *MockModelMockRecorder) DeleteContextById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContextById", reflect.TypeOf((*MockModel)(nil).DeleteContextById), id)
}

// DeleteContextTypeById mocks base method.
func (m *MockModel) DeleteContextTypeById(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContextTypeById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContextTypeById indicates an expected call of DeleteContextTypeById.
func (mr *MockModelMockRecorder) DeleteContextTypeById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContextTypeById", reflect.TypeOf((*MockModel)(nil).DeleteContextTypeById), id)
}

// DeleteFindingById mocks base method.
func (m *MockModel) DeleteFindingById(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFindingById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFindingById indicates an expected call of DeleteFindingById.
func (mr *MockModelMockRecorder) DeleteFindingById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFindingById", reflect.TypeOf((*MockModel)(nil).DeleteFindingById), id)
}

// DeleteFindingTypeById mocks base method.
func (m *MockModel) DeleteFindingTypeById(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFindingTypeById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFindingTypeById indicates an expected call of DeleteFindingTypeById.
func (mr *MockModelMockRecorder) DeleteFindingTypeById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFindingTypeById", reflect.TypeOf((*MockModel)(nil).DeleteFindingTypeById), id)
}

// DeleteNodeById mocks base method.
func (m *MockModel) DeleteNodeById(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNodeById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNodeById indicates an expected call of DeleteNodeById.
func (mr *MockModelMockRecorder) DeleteNodeById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNodeById", reflect.TypeOf((*MockModel)(nil).DeleteNodeById), id)
}

// DeleteNodeTypeById mocks base method.
func (m *MockModel) DeleteNodeTypeById(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNodeTypeById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNodeTypeById indicates an expected call of DeleteNodeTypeById.
func (mr *MockModelMockRecorder) DeleteNodeTypeById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNodeTypeById", reflect.TypeOf((*MockModel)(nil).DeleteNodeTypeById), id)
}

// DeleteSystemById mocks base method.
func (m *MockModel) DeleteSystemById(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSystemById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSystemById indicates an expected call of DeleteSystemById.
func (mr *MockModelMockRecorder) DeleteSystemById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSystemById", reflect.TypeOf((*MockModel)(nil).DeleteSystemById), id)
}

// DeleteSystemInstanceById mocks base method.
func (m *MockModel) DeleteSystemInstanceById(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSystemInstanceById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSystemInstanceById indicates an expected call of DeleteSystemInstanceById.
func (mr *MockModelMockRecorder) DeleteSystemInstanceById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSystemInstanceById", reflect.TypeOf((*MockModel)(nil).DeleteSystemInstanceById), id)
}

// GetApiById mocks base method.
func (m *MockModel) GetApiById(id uuid.UUID) api.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiById", id)
	ret0, _ := ret[0].(api.API)
	return ret0
}

// GetApiById indicates an expected call of GetApiById.
func (mr *MockModelMockRecorder) GetApiById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiById", reflect.TypeOf((*MockModel)(nil).GetApiById), id)
}

// GetApiInstanceById mocks base method.
func (m *MockModel) GetApiInstanceById(id uuid.UUID) api.ApiInstance {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiInstanceById", id)
	ret0, _ := ret[0].(api.ApiInstance)
	return ret0
}

// GetApiInstanceById indicates an expected call of GetApiInstanceById.
func (mr *MockModelMockRecorder) GetApiInstanceById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiInstanceById", reflect.TypeOf((*MockModel)(nil).GetApiInstanceById), id)
}

// GetApiInstances mocks base method.
func (m *MockModel) GetApiInstances() ([]api.ApiInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiInstances")
	ret0, _ := ret[0].([]api.ApiInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiInstances indicates an expected call of GetApiInstances.
func (mr *MockModelMockRecorder) GetApiInstances() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiInstances", reflect.TypeOf((*MockModel)(nil).GetApiInstances))
}

// GetApis mocks base method.
func (m *MockModel) GetApis() ([]api.API, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApis")
	ret0, _ := ret[0].([]api.API)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApis indicates an expected call of GetApis.
func (mr *MockModelMockRecorder) GetApis() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApis", reflect.TypeOf((*MockModel)(nil).GetApis))
}

// GetComponentById mocks base method.
func (m *MockModel) GetComponentById(id uuid.UUID) component.Component {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponentById", id)
	ret0, _ := ret[0].(component.Component)
	return ret0
}

// GetComponentById indicates an expected call of GetComponentById.
func (mr *MockModelMockRecorder) GetComponentById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponentById", reflect.TypeOf((*MockModel)(nil).GetComponentById), id)
}

// GetComponentInstanceById mocks base method.
func (m *MockModel) GetComponentInstanceById(id uuid.UUID) component.ComponentInstance {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponentInstanceById", id)
	ret0, _ := ret[0].(component.ComponentInstance)
	return ret0
}

// GetComponentInstanceById indicates an expected call of GetComponentInstanceById.
func (mr *MockModelMockRecorder) GetComponentInstanceById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponentInstanceById", reflect.TypeOf((*MockModel)(nil).GetComponentInstanceById), id)
}

// GetComponentInstances mocks base method.
func (m *MockModel) GetComponentInstances() ([]component.ComponentInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponentInstances")
	ret0, _ := ret[0].([]component.ComponentInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComponentInstances indicates an expected call of GetComponentInstances.
func (mr *MockModelMockRecorder) GetComponentInstances() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponentInstances", reflect.TypeOf((*MockModel)(nil).GetComponentInstances))
}

// GetComponents mocks base method.
func (m *MockModel) GetComponents() ([]component.Component, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponents")
	ret0, _ := ret[0].([]component.Component)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComponents indicates an expected call of GetComponents.
func (mr *MockModelMockRecorder) GetComponents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponents", reflect.TypeOf((*MockModel)(nil).GetComponents))
}

// GetContextById mocks base method.
func (m *MockModel) GetContextById(id uuid.UUID) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContextById", id)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// GetContextById indicates an expected call of GetContextById.
func (mr *MockModelMockRecorder) GetContextById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContextById", reflect.TypeOf((*MockModel)(nil).GetContextById), id)
}

// GetContextTypeById mocks base method.
func (m *MockModel) GetContextTypeById(id uuid.UUID) context.ContextType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContextTypeById", id)
	ret0, _ := ret[0].(context.ContextType)
	return ret0
}

// GetContextTypeById indicates an expected call of GetContextTypeById.
func (mr *MockModelMockRecorder) GetContextTypeById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContextTypeById", reflect.TypeOf((*MockModel)(nil).GetContextTypeById), id)
}

// GetContextTypes mocks base method.
func (m *MockModel) GetContextTypes() ([]context.ContextType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContextTypes")
	ret0, _ := ret[0].([]context.ContextType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContextTypes indicates an expected call of GetContextTypes.
func (mr *MockModelMockRecorder) GetContextTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContextTypes", reflect.TypeOf((*MockModel)(nil).GetContextTypes))
}

// GetContexts mocks base method.
func (m *MockModel) GetContexts() ([]context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContexts")
	ret0, _ := ret[0].([]context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContexts indicates an expected call of GetContexts.
func (mr *MockModelMockRecorder) GetContexts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContexts", reflect.TypeOf((*MockModel)(nil).GetContexts))
}

// GetFindingById mocks base method.
func (m *MockModel) GetFindingById(id uuid.UUID) finding.Finding {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFindingById", id)
	ret0, _ := ret[0].(finding.Finding)
	return ret0
}

// GetFindingById indicates an expected call of GetFindingById.
func (mr *MockModelMockRecorder) GetFindingById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFindingById", reflect.TypeOf((*MockModel)(nil).GetFindingById), id)
}

// GetFindingTypeById mocks base method.
func (m *MockModel) GetFindingTypeById(id uuid.UUID) finding.FindingType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFindingTypeById", id)
	ret0, _ := ret[0].(finding.FindingType)
	return ret0
}

// GetFindingTypeById indicates an expected call of GetFindingTypeById.
func (mr *MockModelMockRecorder) GetFindingTypeById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFindingTypeById", reflect.TypeOf((*MockModel)(nil).GetFindingTypeById), id)
}

// GetFindingTypes mocks base method.
func (m *MockModel) GetFindingTypes() ([]finding.FindingType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFindingTypes")
	ret0, _ := ret[0].([]finding.FindingType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFindingTypes indicates an expected call of GetFindingTypes.
func (mr *MockModelMockRecorder) GetFindingTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFindingTypes", reflect.TypeOf((*MockModel)(nil).GetFindingTypes))
}

// GetFindings mocks base method.
func (m *MockModel) GetFindings() ([]finding.Finding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFindings")
	ret0, _ := ret[0].([]finding.Finding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFindings indicates an expected call of GetFindings.
func (mr *MockModelMockRecorder) GetFindings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFindings", reflect.TypeOf((*MockModel)(nil).GetFindings))
}

// GetNodeById mocks base method.
func (m *MockModel) GetNodeById(id uuid.UUID) node.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeById", id)
	ret0, _ := ret[0].(node.Node)
	return ret0
}

// GetNodeById indicates an expected call of GetNodeById.
func (mr *MockModelMockRecorder) GetNodeById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeById", reflect.TypeOf((*MockModel)(nil).GetNodeById), id)
}

// GetNodeTypeById mocks base method.
func (m *MockModel) GetNodeTypeById(id uuid.UUID) node.NodeType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeTypeById", id)
	ret0, _ := ret[0].(node.NodeType)
	return ret0
}

// GetNodeTypeById indicates an expected call of GetNodeTypeById.
func (mr *MockModelMockRecorder) GetNodeTypeById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeTypeById", reflect.TypeOf((*MockModel)(nil).GetNodeTypeById), id)
}

// GetNodeTypes mocks base method.
func (m *MockModel) GetNodeTypes() ([]node.NodeType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeTypes")
	ret0, _ := ret[0].([]node.NodeType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeTypes indicates an expected call of GetNodeTypes.
func (mr *MockModelMockRecorder) GetNodeTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeTypes", reflect.TypeOf((*MockModel)(nil).GetNodeTypes))
}

// GetNodes mocks base method.
func (m *MockModel) GetNodes() ([]node.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodes")
	ret0, _ := ret[0].([]node.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodes indicates an expected call of GetNodes.
func (mr *MockModelMockRecorder) GetNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodes", reflect.TypeOf((*MockModel)(nil).GetNodes))
}

// GetSink mocks base method.
func (m *MockModel) GetSink() events.EventSink {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSink")
	ret0, _ := ret[0].(events.EventSink)
	return ret0
}

// GetSink indicates an expected call of GetSink.
func (mr *MockModelMockRecorder) GetSink() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSink", reflect.TypeOf((*MockModel)(nil).GetSink))
}

// GetSystemById mocks base method.
func (m *MockModel) GetSystemById(id uuid.UUID) system.System {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemById", id)
	ret0, _ := ret[0].(system.System)
	return ret0
}

// GetSystemById indicates an expected call of GetSystemById.
func (mr *MockModelMockRecorder) GetSystemById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemById", reflect.TypeOf((*MockModel)(nil).GetSystemById), id)
}

// GetSystemInstanceById mocks base method.
func (m *MockModel) GetSystemInstanceById(id uuid.UUID) system.SystemInstance {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemInstanceById", id)
	ret0, _ := ret[0].(system.SystemInstance)
	return ret0
}

// GetSystemInstanceById indicates an expected call of GetSystemInstanceById.
func (mr *MockModelMockRecorder) GetSystemInstanceById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemInstanceById", reflect.TypeOf((*MockModel)(nil).GetSystemInstanceById), id)
}

// GetSystemInstances mocks base method.
func (m *MockModel) GetSystemInstances() ([]system.SystemInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemInstances")
	ret0, _ := ret[0].([]system.SystemInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemInstances indicates an expected call of GetSystemInstances.
func (mr *MockModelMockRecorder) GetSystemInstances() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemInstances", reflect.TypeOf((*MockModel)(nil).GetSystemInstances))
}

// GetSystems mocks base method.
func (m *MockModel) GetSystems() ([]system.System, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystems")
	ret0, _ := ret[0].([]system.System)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystems indicates an expected call of GetSystems.
func (mr *MockModelMockRecorder) GetSystems() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystems", reflect.TypeOf((*MockModel)(nil).GetSystems))
}

// SystemInstanceRefByID mocks base method.
func (m *MockModel) SystemInstanceRefByID(instanceId uuid.UUID) *system.SystemInstanceRef {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemInstanceRefByID", instanceId)
	ret0, _ := ret[0].(*system.SystemInstanceRef)
	return ret0
}

// SystemInstanceRefByID indicates an expected call of SystemInstanceRefByID.
func (mr *MockModelMockRecorder) SystemInstanceRefByID(instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemInstanceRefByID", reflect.TypeOf((*MockModel)(nil).SystemInstanceRefByID), instanceId)
}
