// Code generated by MockGen. DO NOT EDIT.
// Source: go.emeland.io/modelsrv/pkg/model (interfaces: ContextType)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_context_type.go -package=mocks . ContextType
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "go.emeland.io/modelsrv/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockContextType is a mock of ContextType interface.
type MockContextType struct {
	ctrl     *gomock.Controller
	recorder *MockContextTypeMockRecorder
	isgomock struct{}
}

// MockContextTypeMockRecorder is the mock recorder for MockContextType.
type MockContextTypeMockRecorder struct {
	mock *MockContextType
}

// NewMockContextType creates a new mock instance.
func NewMockContextType(ctrl *gomock.Controller) *MockContextType {
	mock := &MockContextType{ctrl: ctrl}
	mock.recorder = &MockContextTypeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextType) EXPECT() *MockContextTypeMockRecorder {
	return m.recorder
}

// GetAnnotations mocks base method.
func (m *MockContextType) GetAnnotations() model.Annotations {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnnotations")
	ret0, _ := ret[0].(model.Annotations)
	return ret0
}

// GetAnnotations indicates an expected call of GetAnnotations.
func (mr *MockContextTypeMockRecorder) GetAnnotations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnnotations", reflect.TypeOf((*MockContextType)(nil).GetAnnotations))
}

// GetContextTypeId mocks base method.
func (m *MockContextType) GetContextTypeId() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContextTypeId")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// GetContextTypeId indicates an expected call of GetContextTypeId.
func (mr *MockContextTypeMockRecorder) GetContextTypeId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContextTypeId", reflect.TypeOf((*MockContextType)(nil).GetContextTypeId))
}

// GetDescription mocks base method.
func (m *MockContextType) GetDescription() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDescription")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDescription indicates an expected call of GetDescription.
func (mr *MockContextTypeMockRecorder) GetDescription() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDescription", reflect.TypeOf((*MockContextType)(nil).GetDescription))
}

// GetDisplayName mocks base method.
func (m *MockContextType) GetDisplayName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDisplayName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDisplayName indicates an expected call of GetDisplayName.
func (mr *MockContextTypeMockRecorder) GetDisplayName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDisplayName", reflect.TypeOf((*MockContextType)(nil).GetDisplayName))
}

// Register mocks base method.
func (m *MockContextType) Register() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockContextTypeMockRecorder) Register() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockContextType)(nil).Register))
}

// SetDescription mocks base method.
func (m *MockContextType) SetDescription(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDescription", s)
}

// SetDescription indicates an expected call of SetDescription.
func (mr *MockContextTypeMockRecorder) SetDescription(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDescription", reflect.TypeOf((*MockContextType)(nil).SetDescription), s)
}

// SetDisplayName mocks base method.
func (m *MockContextType) SetDisplayName(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDisplayName", arg0)
}

// SetDisplayName indicates an expected call of SetDisplayName.
func (mr *MockContextTypeMockRecorder) SetDisplayName(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDisplayName", reflect.TypeOf((*MockContextType)(nil).SetDisplayName), arg0)
}
