// Code generated by MockGen. DO NOT EDIT.
// Source: go.emeland.io/modelsrv/pkg/model/component (interfaces: ComponentInstance)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_component_instance.go -package=mocks . ComponentInstance
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	annotations "go.emeland.io/modelsrv/pkg/model/annotations"
	component "go.emeland.io/modelsrv/pkg/model/component"
	system "go.emeland.io/modelsrv/pkg/model/system"
	gomock "go.uber.org/mock/gomock"
)

// MockComponentInstance is a mock of ComponentInstance interface.
type MockComponentInstance struct {
	ctrl     *gomock.Controller
	recorder *MockComponentInstanceMockRecorder
	isgomock struct{}
}

// MockComponentInstanceMockRecorder is the mock recorder for MockComponentInstance.
type MockComponentInstanceMockRecorder struct {
	mock *MockComponentInstance
}

// NewMockComponentInstance creates a new mock instance.
func NewMockComponentInstance(ctrl *gomock.Controller) *MockComponentInstance {
	mock := &MockComponentInstance{ctrl: ctrl}
	mock.recorder = &MockComponentInstanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponentInstance) EXPECT() *MockComponentInstanceMockRecorder {
	return m.recorder
}

// GetAnnotations mocks base method.
func (m *MockComponentInstance) GetAnnotations() annotations.Annotations {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnnotations")
	ret0, _ := ret[0].(annotations.Annotations)
	return ret0
}

// GetAnnotations indicates an expected call of GetAnnotations.
func (mr *MockComponentInstanceMockRecorder) GetAnnotations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnnotations", reflect.TypeOf((*MockComponentInstance)(nil).GetAnnotations))
}

// GetComponentRef mocks base method.
func (m *MockComponentInstance) GetComponentRef() *component.ComponentRef {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponentRef")
	ret0, _ := ret[0].(*component.ComponentRef)
	return ret0
}

// GetComponentRef indicates an expected call of GetComponentRef.
func (mr *MockComponentInstanceMockRecorder) GetComponentRef() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponentRef", reflect.TypeOf((*MockComponentInstance)(nil).GetComponentRef))
}

// GetDisplayName mocks base method.
func (m *MockComponentInstance) GetDisplayName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDisplayName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDisplayName indicates an expected call of GetDisplayName.
func (mr *MockComponentInstanceMockRecorder) GetDisplayName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDisplayName", reflect.TypeOf((*MockComponentInstance)(nil).GetDisplayName))
}

// GetInstanceId mocks base method.
func (m *MockComponentInstance) GetInstanceId() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceId")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// GetInstanceId indicates an expected call of GetInstanceId.
func (mr *MockComponentInstanceMockRecorder) GetInstanceId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceId", reflect.TypeOf((*MockComponentInstance)(nil).GetInstanceId))
}

// GetResourceId mocks base method.
func (m *MockComponentInstance) GetResourceId() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceId")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// GetResourceId indicates an expected call of GetResourceId.
func (mr *MockComponentInstanceMockRecorder) GetResourceId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceId", reflect.TypeOf((*MockComponentInstance)(nil).GetResourceId))
}

// GetResourceName mocks base method.
func (m *MockComponentInstance) GetResourceName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetResourceName indicates an expected call of GetResourceName.
func (mr *MockComponentInstanceMockRecorder) GetResourceName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceName", reflect.TypeOf((*MockComponentInstance)(nil).GetResourceName))
}

// GetSystemInstance mocks base method.
func (m *MockComponentInstance) GetSystemInstance() *system.SystemInstanceRef {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemInstance")
	ret0, _ := ret[0].(*system.SystemInstanceRef)
	return ret0
}

// GetSystemInstance indicates an expected call of GetSystemInstance.
func (mr *MockComponentInstanceMockRecorder) GetSystemInstance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemInstance", reflect.TypeOf((*MockComponentInstance)(nil).GetSystemInstance))
}

// Register mocks base method.
func (m *MockComponentInstance) Register() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register")
}

// Register indicates an expected call of Register.
func (mr *MockComponentInstanceMockRecorder) Register() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockComponentInstance)(nil).Register))
}

// SetAnnotations mocks base method.
func (m *MockComponentInstance) SetAnnotations(arg0 annotations.Annotations) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAnnotations", arg0)
}

// SetAnnotations indicates an expected call of SetAnnotations.
func (mr *MockComponentInstanceMockRecorder) SetAnnotations(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAnnotations", reflect.TypeOf((*MockComponentInstance)(nil).SetAnnotations), arg0)
}

// SetComponentRef mocks base method.
func (m *MockComponentInstance) SetComponentRef(arg0 *component.ComponentRef) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetComponentRef", arg0)
}

// SetComponentRef indicates an expected call of SetComponentRef.
func (mr *MockComponentInstanceMockRecorder) SetComponentRef(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetComponentRef", reflect.TypeOf((*MockComponentInstance)(nil).SetComponentRef), arg0)
}

// SetDisplayName mocks base method.
func (m *MockComponentInstance) SetDisplayName(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDisplayName", arg0)
}

// SetDisplayName indicates an expected call of SetDisplayName.
func (mr *MockComponentInstanceMockRecorder) SetDisplayName(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDisplayName", reflect.TypeOf((*MockComponentInstance)(nil).SetDisplayName), arg0)
}

// SetSystemInstance mocks base method.
func (m *MockComponentInstance) SetSystemInstance(arg0 *system.SystemInstanceRef) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSystemInstance", arg0)
}

// SetSystemInstance indicates an expected call of SetSystemInstance.
func (mr *MockComponentInstanceMockRecorder) SetSystemInstance(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSystemInstance", reflect.TypeOf((*MockComponentInstance)(nil).SetSystemInstance), arg0)
}
