// Code generated by MockGen. DO NOT EDIT.
// Source: go.emeland.io/modelsrv/pkg/model (interfaces: Node)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_node.go -package=mocks . Node
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "go.emeland.io/modelsrv/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockNode is a mock of Node interface.
type MockNode struct {
	ctrl     *gomock.Controller
	recorder *MockNodeMockRecorder
	isgomock struct{}
}

// MockNodeMockRecorder is the mock recorder for MockNode.
type MockNodeMockRecorder struct {
	mock *MockNode
}

// NewMockNode creates a new mock instance.
func NewMockNode(ctrl *gomock.Controller) *MockNode {
	mock := &MockNode{ctrl: ctrl}
	mock.recorder = &MockNodeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNode) EXPECT() *MockNodeMockRecorder {
	return m.recorder
}

// GetAnnotations mocks base method.
func (m *MockNode) GetAnnotations() model.Annotations {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnnotations")
	ret0, _ := ret[0].(model.Annotations)
	return ret0
}

// GetAnnotations indicates an expected call of GetAnnotations.
func (mr *MockNodeMockRecorder) GetAnnotations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnnotations", reflect.TypeOf((*MockNode)(nil).GetAnnotations))
}

// GetDescription mocks base method.
func (m *MockNode) GetDescription() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDescription")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDescription indicates an expected call of GetDescription.
func (mr *MockNodeMockRecorder) GetDescription() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDescription", reflect.TypeOf((*MockNode)(nil).GetDescription))
}

// GetDisplayName mocks base method.
func (m *MockNode) GetDisplayName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDisplayName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDisplayName indicates an expected call of GetDisplayName.
func (mr *MockNodeMockRecorder) GetDisplayName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDisplayName", reflect.TypeOf((*MockNode)(nil).GetDisplayName))
}

// GetNodeId mocks base method.
func (m *MockNode) GetNodeId() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeId")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// GetNodeId indicates an expected call of GetNodeId.
func (mr *MockNodeMockRecorder) GetNodeId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeId", reflect.TypeOf((*MockNode)(nil).GetNodeId))
}

// GetNodeType mocks base method.
func (m *MockNode) GetNodeType() (model.NodeType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeType")
	ret0, _ := ret[0].(model.NodeType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeType indicates an expected call of GetNodeType.
func (mr *MockNodeMockRecorder) GetNodeType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeType", reflect.TypeOf((*MockNode)(nil).GetNodeType))
}

// Register mocks base method.
func (m *MockNode) Register() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockNodeMockRecorder) Register() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockNode)(nil).Register))
}

// SetDescription mocks base method.
func (m *MockNode) SetDescription(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDescription", s)
}

// SetDescription indicates an expected call of SetDescription.
func (mr *MockNodeMockRecorder) SetDescription(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDescription", reflect.TypeOf((*MockNode)(nil).SetDescription), s)
}

// SetDisplayName mocks base method.
func (m *MockNode) SetDisplayName(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDisplayName", arg0)
}

// SetDisplayName indicates an expected call of SetDisplayName.
func (mr *MockNodeMockRecorder) SetDisplayName(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDisplayName", reflect.TypeOf((*MockNode)(nil).SetDisplayName), arg0)
}

// SetNodeTypeByRef mocks base method.
func (m *MockNode) SetNodeTypeByRef(nodeType model.NodeType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetNodeTypeByRef", nodeType)
}

// SetNodeTypeByRef indicates an expected call of SetNodeTypeByRef.
func (mr *MockNodeMockRecorder) SetNodeTypeByRef(nodeType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNodeTypeByRef", reflect.TypeOf((*MockNode)(nil).SetNodeTypeByRef), nodeType)
}
