package common

import "fmt"

var (
	ErrNodeNotFound                 = fmt.Errorf("node not found")
	ErrNodeTypeNotFound             = fmt.Errorf("node Type not found")
	ErrContextNotFound              = fmt.Errorf("context not found")
	ErrContextTypeNotFound          = fmt.Errorf("context Type not found")
	ErrSystemNotFound               = fmt.Errorf("system not found")
	ErrSystemInstanceNotFound       = fmt.Errorf("system Instance not found")
	ErrApiNotFound                  = fmt.Errorf("api not found")
	ErrApiInstanceNotFound          = fmt.Errorf("api Instance not found")
	ErrComponentNotFound            = fmt.Errorf("component not found")
	ErrComponentInstanceNotFound    = fmt.Errorf("component Instance not found")
	ErrFindingNotFound              = fmt.Errorf("finding not found")
	ErrFindingTypeNotFound          = fmt.Errorf("finding Type not found")
	ErrOrgUnitNotFound              = fmt.Errorf("organizational unit not found")
	ErrIdentityNotFound             = fmt.Errorf("identity not found")
	ErrGroupNotFound                = fmt.Errorf("group not found")
	ErrPermissionSpecNotFound       = fmt.Errorf("permission specification not found")
	ErrRoleSpecNotFound             = fmt.Errorf("role specification not found")
	ErrPermissionNotFound           = fmt.Errorf("permission not found")
	ErrRoleNotFound                 = fmt.Errorf("role not found")
	ErrBindingNotFound              = fmt.Errorf("binding not found")
	ErrArtifactNotFound             = fmt.Errorf("artifact not found")
	ErrArtifactInstanceNotFound     = fmt.Errorf("artifact instance not found")
	ErrProductNotFound              = fmt.Errorf("product not found")
	ErrFilterRuleNotFound           = fmt.Errorf("filter rule not found")
	ErrMergeRuleNotFound            = fmt.Errorf("merge rule not found")
	ErrCapabilityNotFound           = fmt.Errorf("capability not found")
	ErrParameterNotFound            = fmt.Errorf("parameter not found")
	ErrValidValueNotFound           = fmt.Errorf("valid value not found")
	ErrValidValueConflict           = fmt.Errorf("valid value already exists with a different validValueId")
	ErrCapabilityVersionNotFound    = fmt.Errorf("capability version not found")
	ErrVariantNotFound              = fmt.Errorf("variant not found")
	ErrVariantDependencyUnsatisfied = fmt.Errorf("variant dependency unsatisfied")
	ErrVariantDependencyCycle       = fmt.Errorf("variant dependency cycle")
	ErrOrderNotFound                = fmt.Errorf("order not found")
	ErrOrderItemNotFound            = fmt.Errorf("order item not found")
	ErrBoundValueNotFound           = fmt.Errorf("bound value not found")
	ErrBoundValueConflict           = fmt.Errorf("bound value already exists for order item and parameter")
	ErrCapacityResourceTypeNotFound = fmt.Errorf("capacity resource type not found")
	ErrCapacityNotFound             = fmt.Errorf("capacity not found")
	ErrCapacityTupleConflict        = fmt.Errorf("capacity tuple already exists with a different capacityId")
	ErrMetricNotFound               = fmt.Errorf("metric not found")
	ErrThresholdNotFound            = fmt.Errorf("threshold not found")
	ErrMetricInstanceNotFound       = fmt.Errorf("metric instance not found")
	ErrMetricValueNotFound          = fmt.Errorf("metric value not found")

	ErrUUIDNotSet = fmt.Errorf("resource identifier UUID not set")
)
