package common

import "fmt"

var (
	ErrNodeNotFound              = fmt.Errorf("node not found")
	ErrNodeTypeNotFound          = fmt.Errorf("node Type not found")
	ErrContextNotFound           = fmt.Errorf("context not found")
	ErrContextTypeNotFound       = fmt.Errorf("context Type not found")
	ErrSystemNotFound            = fmt.Errorf("system not found")
	ErrSystemInstanceNotFound    = fmt.Errorf("system Instance not found")
	ErrApiNotFound               = fmt.Errorf("api not found")
	ErrApiInstanceNotFound       = fmt.Errorf("api Instance not found")
	ErrComponentNotFound         = fmt.Errorf("component not found")
	ErrComponentInstanceNotFound = fmt.Errorf("component Instance not found")
	ErrFindingNotFound           = fmt.Errorf("finding not found")
	ErrFindingTypeNotFound       = fmt.Errorf("finding Type not found")
	ErrOrgUnitNotFound           = fmt.Errorf("organizational unit not found")
	ErrIdentityNotFound          = fmt.Errorf("identity not found")
	ErrGroupNotFound             = fmt.Errorf("group not found")
	ErrPermissionSpecNotFound    = fmt.Errorf("permission specification not found")
	ErrRoleSpecNotFound          = fmt.Errorf("role specification not found")
	ErrPermissionNotFound        = fmt.Errorf("permission not found")
	ErrRoleNotFound              = fmt.Errorf("role not found")
	ErrBindingNotFound           = fmt.Errorf("binding not found")
	ErrArtifactNotFound          = fmt.Errorf("artifact not found")
	ErrArtifactInstanceNotFound  = fmt.Errorf("artifact instance not found")
	ErrProductNotFound           = fmt.Errorf("product not found")
	ErrFilterRuleNotFound        = fmt.Errorf("filter rule not found")
	ErrMergeRuleNotFound         = fmt.Errorf("merge rule not found")
	ErrCapabilityNotFound        = fmt.Errorf("capability not found")
	ErrParameterNotFound         = fmt.Errorf("parameter not found")

	ErrUUIDNotSet = fmt.Errorf("resource identifier UUID not set")
)
