// Code generated by tools/gen. DO NOT EDIT.

package observability

import (
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/annotations"
)

// ensure Threshold interface is implemented correctly
var _ Threshold = (*thresholdData)(nil)

// ensure events.EventSink interface is implemented correctly
var _ events.EventSink = (*thresholdData)(nil)

type Threshold interface {
	GetThresholdId() uuid.UUID
	GetResourceId() uuid.UUID
	GetResourceName() string

	GetDisplayName() string
	SetDisplayName(string)

	GetDescription() string
	SetDescription(string)

	GetAnnotations() annotations.Annotations
	SetAnnotations(annotations.Annotations)

	GetMetricInstance() (MetricInstance, error)
	GetMetricInstanceId() uuid.UUID
	SetMetricInstanceRef(*MetricInstanceRef)
	SetMetricInstanceByRef(mi MetricInstance)
	SetMetricInstanceById(id uuid.UUID)

	Register(sink events.EventSink)
}

type thresholdData struct {
	sink         events.EventSink
	isRegistered bool

	ThresholdId       uuid.UUID
	DisplayName       string
	Description       string
	MetricInstanceRef *MetricInstanceRef
	Annotations       annotations.Annotations
}

// NewThreshold constructs an unregistered resource; call [Threshold.Register] after adding to the model.
func NewThreshold(id uuid.UUID) Threshold {
	retval := &thresholdData{
		isRegistered: false,
		ThresholdId:  id,
	}

	retval.Annotations = annotations.NewAnnotations(retval)

	return retval
}

// GetThresholdId implements [Threshold].
func (o *thresholdData) GetThresholdId() uuid.UUID {
	return o.ThresholdId
}

// GetResourceId implements the hasIdAndName interface.
func (o *thresholdData) GetResourceId() uuid.UUID {
	return o.ThresholdId
}

// GetResourceName implements the hasIdAndName interface.
func (o *thresholdData) GetResourceName() string {
	return o.DisplayName
}

// GetDisplayName implements [DisplayName].
func (o *thresholdData) GetDisplayName() string {
	return o.DisplayName
}

// SetDisplayName implements [Threshold].
func (o *thresholdData) SetDisplayName(val string) {
	o.DisplayName = val

	if o.isRegistered {
		o.sink.Receive(events.ThresholdResource, events.UpdateOperation, o.ThresholdId, o)
	}
}

// GetDescription implements [Description].
func (o *thresholdData) GetDescription() string {
	return o.Description
}

// SetDescription implements [Threshold].
func (o *thresholdData) SetDescription(val string) {
	o.Description = val

	if o.isRegistered {
		o.sink.Receive(events.ThresholdResource, events.UpdateOperation, o.ThresholdId, o)
	}
}

// GetAnnotations implements [Annotations].
func (o *thresholdData) GetAnnotations() annotations.Annotations {
	return o.Annotations
}

// SetAnnotations implements [Threshold].
func (o *thresholdData) SetAnnotations(val annotations.Annotations) {
	o.Annotations = val

	if o.isRegistered {
		o.sink.Receive(events.ThresholdResource, events.UpdateOperation, o.ThresholdId, o)
	}
}

// GetMetricInstance returns the embedded [MetricInstance] when present (otherwise nil). Resolve by id via [Model.GetMetricInstanceById].
func (o *thresholdData) GetMetricInstance() (MetricInstance, error) {
	if o.MetricInstanceRef == nil {
		return nil, nil
	}
	return o.MetricInstanceRef.ResolvedMetricInstance(), nil
}

// SetMetricInstanceRef sets the low-level type reference and emits when registered.
func (o *thresholdData) SetMetricInstanceRef(val *MetricInstanceRef) {
	o.MetricInstanceRef = val

	if o.isRegistered {
		o.sink.Receive(events.ThresholdResource, events.UpdateOperation, o.ThresholdId, o)
	}
}

// SetMetricInstanceByRef sets the type from a [MetricInstance] by building a [MetricInstanceRef].
func (o *thresholdData) SetMetricInstanceByRef(res MetricInstance) {
	if res == nil {
		o.SetMetricInstanceRef(nil)
		return
	}
	o.SetMetricInstanceRef(&MetricInstanceRef{
		MetricInstance:   res,
		MetricInstanceId: res.GetMetricInstanceId(),
	})
}

// GetMetricInstanceId returns the type id when set.
func (o *thresholdData) GetMetricInstanceId() uuid.UUID {
	if o.MetricInstanceRef == nil {
		return uuid.Nil
	}
	return o.MetricInstanceRef.EffectiveMetricInstanceID()
}

// SetMetricInstanceById records only the type id (resolved object may be nil).
func (o *thresholdData) SetMetricInstanceById(id uuid.UUID) {
	if id == uuid.Nil {
		o.SetMetricInstanceRef(nil)
		return
	}
	o.SetMetricInstanceRef(&MetricInstanceRef{MetricInstanceId: id})
}

// Register implements [Threshold].
func (o *thresholdData) Register(sink events.EventSink) {
	o.sink = sink
	o.isRegistered = true
}

// Receive implements [events.EventSink].
func (o *thresholdData) Receive(resType events.ResourceType, op events.Operation, resourceId uuid.UUID, object ...any) error {
	if resType != events.AnnotationsResource {
		return fmt.Errorf("unsupported resource type %v in Threshold event sink. Only Annotations are supported", resType)
	}

	if o.isRegistered {
		return o.sink.Receive(events.ThresholdResource, events.UpdateOperation, o.ThresholdId, o)
	}

	return nil
}
