// Code generated by generate_events.go. DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
)

// ensure API interface is implemented correctly
var _ API = (*apiData)(nil)

// ensure events.EventSink interface is implemented correctly
var _ events.EventSink = (*apiData)(nil)

type API interface {
	GetApiId() uuid.UUID
	GetResourceId() uuid.UUID
	GetResourceName() string

	GetDisplayName() string
	SetDisplayName(string)

	GetDescription() string
	SetDescription(string)

	GetVersion() Version
	SetVersion(Version)

	GetType() ApiType
	SetType(ApiType)

	GetSystem() *SystemRef
	SetSystem(*SystemRef)

	GetAnnotations() Annotations
	SetAnnotations(Annotations)

	getData() *apiData
}

type apiData struct {
	model        *modelData
	isRegistered bool

	ApiId       uuid.UUID
	DisplayName string
	Description string
	Version     Version
	Type        ApiType
	System      *SystemRef
	Annotations Annotations
}

func NewAPI(model Model, id uuid.UUID) API {
	retval := &apiData{
		model:        model.getData(),
		isRegistered: false,
		ApiId:        id,
	}

	retval.Annotations = NewAnnotations(model.getData(), retval)

	return retval
}

func (o *apiData) getData() *apiData {
	return o
}

// GetApiId implements [API].
func (o *apiData) GetApiId() uuid.UUID {
	return o.ApiId
}

// GetResourceId implements the hasIdAndName interface.
func (o *apiData) GetResourceId() uuid.UUID {
	return o.ApiId
}

// GetResourceName implements the hasIdAndName interface.
func (o *apiData) GetResourceName() string {
	return o.DisplayName
}

// GetDisplayName implements [DisplayName].
func (o *apiData) GetDisplayName() string {
	return o.DisplayName
}

// SetDisplayName implements [API].
func (o *apiData) SetDisplayName(val string) {
	o.DisplayName = val

	if o.isRegistered {
		o.model.sink.Receive(events.APIResource, events.UpdateOperation, o.ApiId, o)
	}
}

// GetDescription implements [Description].
func (o *apiData) GetDescription() string {
	return o.Description
}

// SetDescription implements [API].
func (o *apiData) SetDescription(val string) {
	o.Description = val

	if o.isRegistered {
		o.model.sink.Receive(events.APIResource, events.UpdateOperation, o.ApiId, o)
	}
}

// GetVersion implements [Version].
func (o *apiData) GetVersion() Version {
	return o.Version
}

// SetVersion implements [API].
func (o *apiData) SetVersion(val Version) {
	o.Version = val

	if o.isRegistered {
		o.model.sink.Receive(events.APIResource, events.UpdateOperation, o.ApiId, o)
	}
}

// GetType implements [Type].
func (o *apiData) GetType() ApiType {
	return o.Type
}

// SetType implements [API].
func (o *apiData) SetType(val ApiType) {
	o.Type = val

	if o.isRegistered {
		o.model.sink.Receive(events.APIResource, events.UpdateOperation, o.ApiId, o)
	}
}

// GetSystem implements [System].
func (o *apiData) GetSystem() *SystemRef {
	return o.System
}

// SetSystem implements [API].
func (o *apiData) SetSystem(val *SystemRef) {
	o.System = val

	if o.isRegistered {
		o.model.sink.Receive(events.APIResource, events.UpdateOperation, o.ApiId, o)
	}
}

// GetAnnotations implements [Annotations].
func (o *apiData) GetAnnotations() Annotations {
	return o.Annotations
}

// SetAnnotations implements [API].
func (o *apiData) SetAnnotations(val Annotations) {
	o.Annotations = val

	if o.isRegistered {
		o.model.sink.Receive(events.APIResource, events.UpdateOperation, o.ApiId, o)
	}
}

// Receive implements [events.EventSink].
func (o *apiData) Receive(resType events.ResourceType, op events.Operation, resourceId uuid.UUID, object ...any) error {
	if resType != events.AnnotationsResource {
		return fmt.Errorf("unsupported resource type %v in API event sink. Only Annotations are supported", resType)
	}

	// all changes to annotations are automatically reflected in the parent object as updates
	if o.isRegistered {
		return o.model.sink.Receive(events.APIResource, events.UpdateOperation, o.ApiId, o)
	}

	return nil
}
