// Code generated by generate_events.go. DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
)

// ensure ApiInstance interface is implemented correctly
var _ ApiInstance = (*apiinstanceData)(nil)

// ensure events.EventSink interface is implemented correctly
var _ events.EventSink = (*apiinstanceData)(nil)

type ApiInstance interface {
	GetInstanceId() uuid.UUID

	GetDisplayName() string
	SetDisplayName(string)

	GetApiRef() *ApiRef
	SetApiRef(*ApiRef)
	SetApiRefById(apiId uuid.UUID)
	SetApiRefByRef(api API)

	GetSystemInstance() *SystemInstanceRef
	SetSystemInstance(*SystemInstanceRef)
	SetSystemInstanceById(instanceId uuid.UUID)
	SetSystemInstanceByRef(instance SystemInstance)

	GetAnnotations() Annotations
	SetAnnotations(Annotations)

	getData() *apiinstanceData
}

type apiinstanceData struct {
	model        *modelData
	isRegistered bool

	InstanceId     uuid.UUID
	DisplayName    string
	ApiRef         *ApiRef
	SystemInstance *SystemInstanceRef
	Annotations    Annotations
}

func NewApiInstance(model Model, id uuid.UUID) ApiInstance {
	retval := &apiinstanceData{
		model:        model.getData(),
		isRegistered: false,
		InstanceId:   id,
	}

	retval.Annotations = NewAnnotations(model.getData(), retval)

	return retval
}

func (o *apiinstanceData) getData() *apiinstanceData {
	return o
}

// GetInstanceId implements [ApiInstance].
func (o *apiinstanceData) GetInstanceId() uuid.UUID {
	return o.InstanceId
}

// GetDisplayName implements [DisplayName].
func (o *apiinstanceData) GetDisplayName() string {
	return o.DisplayName
}

// SetDisplayName implements [ApiInstance].
func (o *apiinstanceData) SetDisplayName(val string) {
	o.DisplayName = val

	if o.isRegistered {
		o.model.sink.Receive(events.APIInstanceResource, events.UpdateOperation, o.InstanceId, o)
	}
}

// GetApiRef implements [ApiRef].
func (o *apiinstanceData) GetApiRef() *ApiRef {
	return o.ApiRef
}

// SetApiRef implements [ApiInstance].
func (o *apiinstanceData) SetApiRef(val *ApiRef) {
	o.ApiRef = val

	if o.isRegistered {
		o.model.sink.Receive(events.APIInstanceResource, events.UpdateOperation, o.InstanceId, o)
	}
}

// GetSystemInstance implements [SystemInstance].
func (o *apiinstanceData) GetSystemInstance() *SystemInstanceRef {
	return o.SystemInstance
}

// SetSystemInstance implements [ApiInstance].
func (o *apiinstanceData) SetSystemInstance(val *SystemInstanceRef) {
	o.SystemInstance = val

	if o.isRegistered {
		o.model.sink.Receive(events.APIInstanceResource, events.UpdateOperation, o.InstanceId, o)
	}
}

// GetAnnotations implements [Annotations].
func (o *apiinstanceData) GetAnnotations() Annotations {
	return o.Annotations
}

// SetAnnotations implements [ApiInstance].
func (o *apiinstanceData) SetAnnotations(val Annotations) {
	o.Annotations = val

	if o.isRegistered {
		o.model.sink.Receive(events.APIInstanceResource, events.UpdateOperation, o.InstanceId, o)
	}
}

// Receive implements [events.EventSink].
func (o *apiinstanceData) Receive(resType events.ResourceType, op events.Operation, resourceId uuid.UUID, object ...any) error {
	if resType != events.AnnotationsResource {
		return fmt.Errorf("unsupported resource type %v in ApiInstance event sink. Only Annotations are supported", resType)
	}

	// all changes to annotations are automatically reflected in the parent object as updates
	if o.isRegistered {
		return o.model.sink.Receive(events.APIInstanceResource, events.UpdateOperation, o.InstanceId, o)
	}

	return nil
}
