// Code generated by generate_events.go. DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
)

// ensure ComponentInstance interface is implemented correctly
var _ ComponentInstance = (*componentinstanceData)(nil)

// ensure events.EventSink interface is implemented correctly
var _ events.EventSink = (*componentinstanceData)(nil)

type ComponentInstance interface {
	GetInstanceId() uuid.UUID

	GetDisplayName() string
	SetDisplayName(string)

	GetComponentRef() *ComponentRef
	SetComponentRef(*ComponentRef)

	GetSystemInstance() *SystemInstanceRef
	SetSystemInstance(*SystemInstanceRef)

	GetAnnotations() Annotations
	SetAnnotations(Annotations)

	getData() *componentinstanceData
}

type componentinstanceData struct {
	model        *modelData
	isRegistered bool

	InstanceId     uuid.UUID
	DisplayName    string
	ComponentRef   *ComponentRef
	SystemInstance *SystemInstanceRef
	Annotations    Annotations
}

func NewComponentInstance(model Model, id uuid.UUID) ComponentInstance {
	retval := &componentinstanceData{
		model:        model.getData(),
		isRegistered: false,
		InstanceId:   id,
	}

	retval.Annotations = NewAnnotations(model.getData(), retval)

	return retval
}

func (o *componentinstanceData) getData() *componentinstanceData {
	return o
}

// GetInstanceId implements [ComponentInstance].
func (o *componentinstanceData) GetInstanceId() uuid.UUID {
	return o.InstanceId
}

// GetDisplayName implements [DisplayName].
func (o *componentinstanceData) GetDisplayName() string {
	return o.DisplayName
}

// SetDisplayName implements [ComponentInstance].
func (o *componentinstanceData) SetDisplayName(val string) {
	o.DisplayName = val

	if o.isRegistered {
		o.model.sink.Receive(events.ComponentInstanceResource, events.UpdateOperation, o.InstanceId, o)
	}
}

// GetComponentRef implements [ComponentRef].
func (o *componentinstanceData) GetComponentRef() *ComponentRef {
	return o.ComponentRef
}

// SetComponentRef implements [ComponentInstance].
func (o *componentinstanceData) SetComponentRef(val *ComponentRef) {
	o.ComponentRef = val

	if o.isRegistered {
		o.model.sink.Receive(events.ComponentInstanceResource, events.UpdateOperation, o.InstanceId, o)
	}
}

// GetSystemInstance implements [SystemInstance].
func (o *componentinstanceData) GetSystemInstance() *SystemInstanceRef {
	return o.SystemInstance
}

// SetSystemInstance implements [ComponentInstance].
func (o *componentinstanceData) SetSystemInstance(val *SystemInstanceRef) {
	o.SystemInstance = val

	if o.isRegistered {
		o.model.sink.Receive(events.ComponentInstanceResource, events.UpdateOperation, o.InstanceId, o)
	}
}

// GetAnnotations implements [Annotations].
func (o *componentinstanceData) GetAnnotations() Annotations {
	return o.Annotations
}

// SetAnnotations implements [ComponentInstance].
func (o *componentinstanceData) SetAnnotations(val Annotations) {
	o.Annotations = val

	if o.isRegistered {
		o.model.sink.Receive(events.ComponentInstanceResource, events.UpdateOperation, o.InstanceId, o)
	}
}

// Receive implements [events.EventSink].
func (o *componentinstanceData) Receive(resType events.ResourceType, op events.Operation, resourceId uuid.UUID, object ...any) error {
	if resType != events.AnnotationsResource {
		return fmt.Errorf("unsupported resource type %v in ComponentInstance event sink. Only Annotations are supported", resType)
	}

	// all changes to annotations are automatically reflected in the parent object as updates
	if o.isRegistered {
		return o.model.sink.Receive(events.ComponentInstanceResource, events.UpdateOperation, o.InstanceId, o)
	}

	return nil
}
