// Code generated by generate_events.go. DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
)

// ensure Component interface is implemented correctly
var _ Component = (*componentData)(nil)

// ensure events.EventSink interface is implemented correctly
var _ events.EventSink = (*componentData)(nil)

type Component interface {
	GetComponentId() uuid.UUID
	GetResourceId() uuid.UUID
	GetResourceName() string

	GetDisplayName() string
	SetDisplayName(string)

	GetDescription() string
	SetDescription(string)

	GetVersion() Version
	SetVersion(Version)

	GetSystem() *SystemRef
	SetSystem(*SystemRef)

	GetConsumes() []ApiRef
	SetConsumes([]ApiRef)

	GetProvides() []ApiRef
	SetProvides([]ApiRef)

	GetAnnotations() Annotations
	SetAnnotations(Annotations)

	Register()
}

type componentData struct {
	model        Model
	sink         events.EventSink
	isRegistered bool

	ComponentId uuid.UUID
	DisplayName string
	Description string
	Version     Version
	System      *SystemRef
	Consumes    []ApiRef
	Provides    []ApiRef
	Annotations Annotations
}

// NewComponent constructs a resource bound to the given [Model] and its sink.
func NewComponent(m Model, id uuid.UUID) Component {
	retval := &componentData{
		model:        m,
		sink:         m.GetSink(),
		isRegistered: false,
		ComponentId:  id,
	}

	retval.Annotations = NewAnnotations(retval)

	return retval
}

// GetComponentId implements [Component].
func (o *componentData) GetComponentId() uuid.UUID {
	return o.ComponentId
}

// GetResourceId implements the hasIdAndName interface.
func (o *componentData) GetResourceId() uuid.UUID {
	return o.ComponentId
}

// GetResourceName implements the hasIdAndName interface.
func (o *componentData) GetResourceName() string {
	return o.DisplayName
}

// GetDisplayName implements [DisplayName].
func (o *componentData) GetDisplayName() string {
	return o.DisplayName
}

// SetDisplayName implements [Component].
func (o *componentData) SetDisplayName(val string) {
	o.DisplayName = val

	if o.isRegistered {
		o.sink.Receive(events.ComponentResource, events.UpdateOperation, o.ComponentId, o)
	}
}

// GetDescription implements [Description].
func (o *componentData) GetDescription() string {
	return o.Description
}

// SetDescription implements [Component].
func (o *componentData) SetDescription(val string) {
	o.Description = val

	if o.isRegistered {
		o.sink.Receive(events.ComponentResource, events.UpdateOperation, o.ComponentId, o)
	}
}

// GetVersion implements [Version].
func (o *componentData) GetVersion() Version {
	return o.Version
}

// SetVersion implements [Component].
func (o *componentData) SetVersion(val Version) {
	o.Version = val

	if o.isRegistered {
		o.sink.Receive(events.ComponentResource, events.UpdateOperation, o.ComponentId, o)
	}
}

// GetSystem implements [System].
func (o *componentData) GetSystem() *SystemRef {
	return o.System
}

// SetSystem implements [Component].
func (o *componentData) SetSystem(val *SystemRef) {
	o.System = val

	if o.isRegistered {
		o.sink.Receive(events.ComponentResource, events.UpdateOperation, o.ComponentId, o)
	}
}

// GetConsumes implements [Consumes].
func (o *componentData) GetConsumes() []ApiRef {
	return o.Consumes
}

// SetConsumes implements [Component].
func (o *componentData) SetConsumes(val []ApiRef) {
	o.Consumes = val

	if o.isRegistered {
		o.sink.Receive(events.ComponentResource, events.UpdateOperation, o.ComponentId, o)
	}
}

// GetProvides implements [Provides].
func (o *componentData) GetProvides() []ApiRef {
	return o.Provides
}

// SetProvides implements [Component].
func (o *componentData) SetProvides(val []ApiRef) {
	o.Provides = val

	if o.isRegistered {
		o.sink.Receive(events.ComponentResource, events.UpdateOperation, o.ComponentId, o)
	}
}

// GetAnnotations implements [Annotations].
func (o *componentData) GetAnnotations() Annotations {
	return o.Annotations
}

// SetAnnotations implements [Component].
func (o *componentData) SetAnnotations(val Annotations) {
	o.Annotations = val

	if o.isRegistered {
		o.sink.Receive(events.ComponentResource, events.UpdateOperation, o.ComponentId, o)
	}
}

// Register implements [Component].
func (o *componentData) Register() {
	o.isRegistered = true
}

// Receive implements [events.EventSink].
func (o *componentData) Receive(resType events.ResourceType, op events.Operation, resourceId uuid.UUID, object ...any) error {
	if resType != events.AnnotationsResource {
		return fmt.Errorf("unsupported resource type %v in Component event sink. Only Annotations are supported", resType)
	}

	// all changes to annotations are automatically reflected in the parent object as updates
	if o.isRegistered {
		return o.sink.Receive(events.ComponentResource, events.UpdateOperation, o.ComponentId, o)
	}

	return nil
}
