//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"
)

type Field struct {
	Name       string
	Type       string
	IsRef      bool
	RefType    string // for reference types
	MapKey     string // for looking up in model maps
	HasAnnotations bool
}

type TypeSpec struct {
	Name           string
	EventType      string
	IDField        string
	NameField      string // field used for GetResourceName(); defaults to "DisplayName"
	Fields         []Field
	CustomMethods  []string // additional method signatures to include in the interface
}

const typeTemplate = `// Code generated by generate_events.go. DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
)

// ensure {{.Name}} interface is implemented correctly
var _ {{.Name}} = (*{{.Name | lower}}Data)(nil)

// ensure events.EventSink interface is implemented correctly
var _ events.EventSink = (*{{.Name | lower}}Data)(nil)

type {{.Name}} interface {
	Get{{.IDField}}() uuid.UUID
	GetResourceId() uuid.UUID
	GetResourceName() string
{{range .Fields}}
	Get{{.Name}}() {{.Type}}
	Set{{.Name}}({{.Type}})
{{end}}
{{range .CustomMethods}}	{{.}}
{{end}}
	getData() *{{.Name | lower}}Data
}

type {{.Name | lower}}Data struct {
	model        *modelData
	isRegistered bool

	{{.IDField}}     uuid.UUID
{{range .Fields}}	{{.Name}}    {{.Type}}
{{end}}
}

func New{{.Name}}(model Model, id uuid.UUID) {{.Name}} {
	retval := &{{.Name | lower}}Data{
		model:        model.getData(),
		isRegistered: false,
		{{.IDField}}:   id,
	}
{{range .Fields}}{{if .HasAnnotations}}
	retval.{{.Name}} = NewAnnotations(model.getData(), retval)
{{end}}{{end}}
	return retval
}

func (o *{{.Name | lower}}Data) getData() *{{.Name | lower}}Data {
	return o
}

// Get{{.IDField}} implements [{{.Name}}].
func (o *{{.Name | lower}}Data) Get{{.IDField}}() uuid.UUID {
	return o.{{.IDField}}
}

// GetResourceId implements the hasIdAndName interface.
func (o *{{.Name | lower}}Data) GetResourceId() uuid.UUID {
	return o.{{.IDField}}
}

// GetResourceName implements the hasIdAndName interface.
func (o *{{.Name | lower}}Data) GetResourceName() string {
	return o.{{.NameField}}
}

{{range .Fields}}
// Get{{.Name}} implements [{{.Name}}].
func (o *{{$.Name | lower}}Data) Get{{.Name}}() {{.Type}} {
	return o.{{.Name}}
}

// Set{{.Name}} implements [{{$.Name}}].
func (o *{{$.Name | lower}}Data) Set{{.Name}}(val {{.Type}}) {
	o.{{.Name}} = val

	if o.isRegistered {
		o.model.sink.Receive(events.{{$.EventType}}Resource, events.UpdateOperation, o.{{$.IDField}}, o)
	}
}
{{end}}

// Receive implements [events.EventSink].
func (o *{{.Name | lower}}Data) Receive(resType events.ResourceType, op events.Operation, resourceId uuid.UUID, object ...any) error {
	if resType != events.AnnotationsResource {
		return fmt.Errorf("unsupported resource type %v in {{.Name}} event sink. Only Annotations are supported", resType)
	}

	// all changes to annotations are automatically reflected in the parent object as updates
	if o.isRegistered {
		return o.model.sink.Receive(events.{{.EventType}}Resource, events.UpdateOperation, o.{{.IDField}}, o)
	}

	return nil
}
`

func main() {
	funcMap := template.FuncMap{
		"lower": strings.ToLower,
	}

	tmpl := template.Must(template.New("type").Funcs(funcMap).Parse(typeTemplate))

	types := []TypeSpec{
		{
			Name:      "ApiInstance",
			EventType: "APIInstance",
			IDField:   "InstanceId",
			NameField: "DisplayName",
			Fields: []Field{
				{Name: "DisplayName", Type: "string"},
				{Name: "ApiRef", Type: "*ApiRef"},
				{Name: "SystemInstance", Type: "*SystemInstanceRef"},
				{Name: "Annotations", Type: "Annotations", HasAnnotations: true},
			},
			CustomMethods: []string{
				"SetApiRefById(apiId uuid.UUID)",
				"SetApiRefByRef(api API)",
				"SetSystemInstanceById(instanceId uuid.UUID)",
				"SetSystemInstanceByRef(instance SystemInstance)",
			},
		},
		{
			Name:      "API",
			EventType: "API",
			IDField:   "ApiId",
			NameField: "DisplayName",
			Fields: []Field{
				{Name: "DisplayName", Type: "string"},
				{Name: "Description", Type: "string"},
				{Name: "Version", Type: "Version"},
				{Name: "Type", Type: "ApiType"},
				{Name: "System", Type: "*SystemRef"},
				{Name: "Annotations", Type: "Annotations", HasAnnotations: true},
			},
		},
		{
			Name:      "Component",
			EventType: "Component",
			IDField:   "ComponentId",
			NameField: "DisplayName",
			Fields: []Field{
				{Name: "DisplayName", Type: "string"},
				{Name: "Description", Type: "string"},
				{Name: "Version", Type: "Version"},
				{Name: "System", Type: "*SystemRef"},
				{Name: "Consumes", Type: "[]ApiRef"},
				{Name: "Provides", Type: "[]ApiRef"},
				{Name: "Annotations", Type: "Annotations", HasAnnotations: true},
			},
		},
		{
			Name:      "SystemInstance",
			EventType: "SystemInstance",
			IDField:   "InstanceId",
			NameField: "DisplayName",
			Fields: []Field{
				{Name: "DisplayName", Type: "string"},
				{Name: "SystemRef", Type: "*SystemRef"},
				{Name: "ContextRef", Type: "*ContextRef"},
				{Name: "Annotations", Type: "Annotations", HasAnnotations: true},
			},
		},
		{
			Name:      "ComponentInstance",
			EventType: "ComponentInstance",
			IDField:   "InstanceId",
			NameField: "DisplayName",
			Fields: []Field{
				{Name: "DisplayName", Type: "string"},
				{Name: "ComponentRef", Type: "*ComponentRef"},
				{Name: "SystemInstance", Type: "*SystemInstanceRef"},
				{Name: "Annotations", Type: "Annotations", HasAnnotations: true},
			},
		},
		{
			Name:      "Finding",
			EventType: "Finding",
			IDField:   "FindingId",
			NameField: "Summary",
			Fields: []Field{
				{Name: "Summary", Type: "string"},
				{Name: "Description", Type: "string"},
				{Name: "Resources", Type: "[]*ResourceRef"},
				{Name: "Annotations", Type: "Annotations", HasAnnotations: true},
			},
		},
	}

	for _, spec := range types {
		var buf bytes.Buffer
		if err := tmpl.Execute(&buf, spec); err != nil {
			fmt.Fprintf(os.Stderr, "Error executing template for %s: %v\n", spec.Name, err)
			os.Exit(1)
		}

		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error formatting code for %s: %v\n", spec.Name, err)
			os.Exit(1)
		}

		filename := fmt.Sprintf("%s_gen.go", strings.ToLower(spec.Name))
		if err := os.WriteFile(filename, formatted, 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing file %s: %v\n", filename, err)
			os.Exit(1)
		}

		fmt.Printf("Generated %s\n", filename)
	}
}
