// Code generated by tools/gen. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	mdlapi "go.emeland.io/modelsrv/pkg/model/api"
	"go.emeland.io/modelsrv/pkg/model/common"
)

func init() {
	registerHandler(events.APIResource, resourceHandler{
		upsert: func(m Model, obj any) error {
			v, ok := obj.(mdlapi.API)
			if !ok {
				return fmt.Errorf("replication object for API is %T, want API", obj)
			}
			return m.AddApi(v)
		},
		delete: func(m Model, id uuid.UUID) error {
			return m.DeleteApiById(id)
		},
		notFound: func(err error) bool {
			return errors.Is(err, common.ErrApiNotFound)
		},
		exists: func(m Model, id uuid.UUID) bool {
			return any(m.GetApiById(id)) != nil
		},
		displayName: func(m Model, id uuid.UUID) string {
			v := m.GetApiById(id)
			if any(v) == nil {
				return ""
			}
			return v.GetDisplayName()
		},
	})
}
