// Code generated by tools/gen. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/common"
	"go.emeland.io/modelsrv/pkg/model/system"
)

func init() {
	registerHandler(events.SystemInstanceResource, resourceHandler{
		upsert: func(m Model, obj any) error {
			v, ok := obj.(system.SystemInstance)
			if !ok {
				return fmt.Errorf("replication object for SystemInstance is %T, want SystemInstance", obj)
			}
			return m.AddSystemInstance(v)
		},
		delete: func(m Model, id uuid.UUID) error {
			return m.DeleteSystemInstanceById(id)
		},
		notFound: func(err error) bool {
			return errors.Is(err, common.ErrSystemInstanceNotFound)
		},
	})
}
