// Code generated by tools/gen. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/common"
	mdlobs "go.emeland.io/modelsrv/pkg/model/observability"
)

func init() {
	registerHandler(events.ThresholdResource, resourceHandler{
		upsert: func(m Model, obj any) error {
			v, ok := obj.(mdlobs.Threshold)
			if !ok {
				return fmt.Errorf("replication object for Threshold is %T, want Threshold", obj)
			}
			return m.AddThreshold(v)
		},
		delete: func(m Model, id uuid.UUID) error {
			return m.DeleteThresholdById(id)
		},
		notFound: func(err error) bool {
			return errors.Is(err, common.ErrThresholdNotFound)
		},
		exists: func(m Model, id uuid.UUID) bool {
			return any(m.GetThresholdById(id)) != nil
		},
		displayName: func(m Model, id uuid.UUID) string {
			v := m.GetThresholdById(id)
			if any(v) == nil {
				return ""
			}
			return v.GetDisplayName()
		},
	})
}
