// Code generated by tools/gen. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/common"
	mdlorder "go.emeland.io/modelsrv/pkg/model/order"
)

func init() {
	registerHandler(events.OrderResource, resourceHandler{
		upsert: func(m Model, obj any) error {
			v, ok := obj.(mdlorder.Order)
			if !ok {
				return fmt.Errorf("replication object for Order is %T, want Order", obj)
			}
			return m.AddOrder(v)
		},
		delete: func(m Model, id uuid.UUID) error {
			return m.DeleteOrderById(id)
		},
		notFound: func(err error) bool {
			return errors.Is(err, common.ErrOrderNotFound)
		},
		exists: func(m Model, id uuid.UUID) bool {
			return any(m.GetOrderById(id)) != nil
		},
		displayName: func(m Model, id uuid.UUID) string {
			v := m.GetOrderById(id)
			if any(v) == nil {
				return ""
			}
			return v.GetDisplayName()
		},
	})
}
