// Code generated by tools/gen. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/common"
	mdlobs "go.emeland.io/modelsrv/pkg/model/observability"
)

func init() {
	registerHandler(events.MetricResource, resourceHandler{
		upsert: func(m Model, obj any) error {
			v, ok := obj.(mdlobs.Metric)
			if !ok {
				return fmt.Errorf("replication object for Metric is %T, want Metric", obj)
			}
			return m.AddMetric(v)
		},
		delete: func(m Model, id uuid.UUID) error {
			return m.DeleteMetricById(id)
		},
		notFound: func(err error) bool {
			return errors.Is(err, common.ErrMetricNotFound)
		},
		exists: func(m Model, id uuid.UUID) bool {
			return any(m.GetMetricById(id)) != nil
		},
		displayName: func(m Model, id uuid.UUID) string {
			v := m.GetMetricById(id)
			if any(v) == nil {
				return ""
			}
			return v.GetDisplayName()
		},
	})
}
