// Code generated by tools/gen. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/common"
	"go.emeland.io/modelsrv/pkg/model/system"
)

func init() {
	registerHandler(events.SystemResource, resourceHandler{
		upsert: func(m Model, obj any) error {
			v, ok := obj.(system.System)
			if !ok {
				return fmt.Errorf("replication object for System is %T, want System", obj)
			}
			return m.AddSystem(v)
		},
		delete: func(m Model, id uuid.UUID) error {
			return m.DeleteSystemById(id)
		},
		notFound: func(err error) bool {
			return errors.Is(err, common.ErrSystemNotFound)
		},
	})
}
