// Code generated by tools/gen. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/common"
	"go.emeland.io/modelsrv/pkg/model/component"
)

func init() {
	registerHandler(events.ComponentResource, resourceHandler{
		upsert: func(m Model, obj any) error {
			v, ok := obj.(component.Component)
			if !ok {
				return fmt.Errorf("replication object for Component is %T, want Component", obj)
			}
			return m.AddComponent(v)
		},
		delete: func(m Model, id uuid.UUID) error {
			return m.DeleteComponentById(id)
		},
		notFound: func(err error) bool {
			return errors.Is(err, common.ErrComponentNotFound)
		},
	})
}
