// Code generated by tools/gen. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/common"
	mdlparameter "go.emeland.io/modelsrv/pkg/model/parameter"
)

func init() {
	registerHandler(events.ParameterResource, resourceHandler{
		upsert: func(m Model, obj any) error {
			v, ok := obj.(mdlparameter.Parameter)
			if !ok {
				return fmt.Errorf("replication object for Parameter is %T, want Parameter", obj)
			}
			return m.AddParameter(v)
		},
		delete: func(m Model, id uuid.UUID) error {
			return m.DeleteParameterById(id)
		},
		notFound: func(err error) bool {
			return errors.Is(err, common.ErrParameterNotFound)
		},
	})
}
