// Code generated by tools/gen. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	mdlapi "go.emeland.io/modelsrv/pkg/model/api"
	"go.emeland.io/modelsrv/pkg/model/common"
)

func init() {
	registerHandler(events.APIInstanceResource, resourceHandler{
		upsert: func(m Model, obj any) error {
			v, ok := obj.(mdlapi.ApiInstance)
			if !ok {
				return fmt.Errorf("replication object for ApiInstance is %T, want ApiInstance", obj)
			}
			return m.AddApiInstance(v)
		},
		delete: func(m Model, id uuid.UUID) error {
			return m.DeleteApiInstanceById(id)
		},
		notFound: func(err error) bool {
			return errors.Is(err, common.ErrApiInstanceNotFound)
		},
	})
}
