// Code generated by tools/gen. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/artifact"
	"go.emeland.io/modelsrv/pkg/model/common"
)

func init() {
	registerHandler(events.ArtifactResource, resourceHandler{
		upsert: func(m Model, obj any) error {
			v, ok := obj.(artifact.Artifact)
			if !ok {
				return fmt.Errorf("replication object for Artifact is %T, want Artifact", obj)
			}
			return m.AddArtifact(v)
		},
		delete: func(m Model, id uuid.UUID) error {
			return m.DeleteArtifactById(id)
		},
		notFound: func(err error) bool {
			return errors.Is(err, common.ErrArtifactNotFound)
		},
	})
}
