// Code generated by tools/gen. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	mdlcapability "go.emeland.io/modelsrv/pkg/model/capability"
	"go.emeland.io/modelsrv/pkg/model/common"
)

func init() {
	registerHandler(events.VariantResource, resourceHandler{
		upsert: func(m Model, obj any) error {
			v, ok := obj.(mdlcapability.Variant)
			if !ok {
				return fmt.Errorf("replication object for Variant is %T, want Variant", obj)
			}
			return m.AddVariant(v)
		},
		delete: func(m Model, id uuid.UUID) error {
			return m.DeleteVariantById(id)
		},
		notFound: func(err error) bool {
			return errors.Is(err, common.ErrVariantNotFound)
		},
		exists: func(m Model, id uuid.UUID) bool {
			return any(m.GetVariantById(id)) != nil
		},
		displayName: func(m Model, id uuid.UUID) string {
			v := m.GetVariantById(id)
			if any(v) == nil {
				return ""
			}
			return v.GetDisplayName()
		},
	})
}
