// Code generated by tools/gen. DO NOT EDIT.

package model_test

import (
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model"
	mdlapi "go.emeland.io/modelsrv/pkg/model/api"
	"go.emeland.io/modelsrv/pkg/model/artifact"
	mdlcapability "go.emeland.io/modelsrv/pkg/model/capability"
	"go.emeland.io/modelsrv/pkg/model/common"
	"go.emeland.io/modelsrv/pkg/model/component"
	mdlctx "go.emeland.io/modelsrv/pkg/model/context"
	mdlfilterrule "go.emeland.io/modelsrv/pkg/model/filterrule"
	"go.emeland.io/modelsrv/pkg/model/finding"
	"go.emeland.io/modelsrv/pkg/model/iam"
	mdlmergerule "go.emeland.io/modelsrv/pkg/model/mergerule"
	"go.emeland.io/modelsrv/pkg/model/node"
	mdlparameter "go.emeland.io/modelsrv/pkg/model/parameter"
	mdlproduct "go.emeland.io/modelsrv/pkg/model/product"
	"go.emeland.io/modelsrv/pkg/model/system"
)

// Ensure imports are used.
var (
	_ = mdlapi.NewAPI
	_ = artifact.NewArtifact
	_ = common.ErrContextNotFound
	_ = component.NewComponent
	_ = mdlctx.NewContext
	_ = mdlcapability.NewCapability
	_ = mdlfilterrule.NewFilterRule
	_ = finding.NewFinding
	_ = iam.NewOrgUnit
	_ = mdlmergerule.NewMergeRule
	_ = node.NewNode
	_ = mdlparameter.NewParameter
	_ = mdlproduct.NewProduct
	_ = system.NewSystem
)

var testIDs = map[string]uuid.UUID{
	"ContextType":       uuid.New(),
	"Context":           uuid.New(),
	"System":            uuid.New(),
	"NodeType":          uuid.New(),
	"FindingType":       uuid.New(),
	"Node":              uuid.New(),
	"ApiInstance":       uuid.New(),
	"API":               uuid.New(),
	"Component":         uuid.New(),
	"SystemInstance":    uuid.New(),
	"ComponentInstance": uuid.New(),
	"Finding":           uuid.New(),
	"OrgUnit":           uuid.New(),
	"Group":             uuid.New(),
	"Identity":          uuid.New(),
	"PermissionSpec":    uuid.New(),
	"RoleSpec":          uuid.New(),
	"Permission":        uuid.New(),
	"Role":              uuid.New(),
	"Binding":           uuid.New(),
	"Artifact":          uuid.New(),
	"ArtifactInstance":  uuid.New(),
	"Product":           uuid.New(),
	"FilterRule":        uuid.New(),
	"MergeRule":         uuid.New(),
	"Capability":        uuid.New(),
	"Parameter":         uuid.New(),
}

func newStoreModel(t *testing.T) (model.Model, events.EventSink) {
	t.Helper()
	sink := events.NewListSink()
	m, err := model.NewModel(sink)
	require.NoError(t, err)
	return m, sink
}

func loadStoreTestModel(t *testing.T, m model.Model) {
	t.Helper()
	// --- ContextType ---
	{
		ct := mdlctx.NewContextType(testIDs["ContextType"])
		ct.SetDisplayName("Test ContextType")
		require.NoError(t, m.AddContextType(ct))
	}
	// --- Context ---
	{
		c := mdlctx.NewContext(testIDs["Context"])
		c.SetDisplayName("Test Context")
		c.SetContextTypeById(testIDs["ContextType"])
		require.NoError(t, m.AddContext(c))
	}
	// --- System ---
	{
		sys := system.NewSystem(testIDs["System"])
		sys.SetDisplayName("Test System")
		require.NoError(t, m.AddSystem(sys))
	}
	// --- NodeType ---
	{
		nt := node.NewNodeType(testIDs["NodeType"])
		nt.SetDisplayName("Test NodeType")
		require.NoError(t, m.AddNodeType(nt))
	}
	// --- FindingType ---
	{
		ft := finding.NewFindingType(testIDs["FindingType"])
		ft.SetDisplayName("Test FindingType")
		require.NoError(t, m.AddFindingType(ft))
	}
	// --- Node ---
	{
		n := node.NewNode(testIDs["Node"])
		n.SetDisplayName("Test Node")
		n.SetTypeRef(&node.NodeTypeRef{NodeTypeId: testIDs["NodeType"]})
		require.NoError(t, m.AddNode(n))
	}
	// --- ApiInstance ---
	{
		ai := mdlapi.NewApiInstance(testIDs["ApiInstance"])
		ai.SetDisplayName("Test ApiInstance")
		ai.SetApiRef(&mdlapi.ApiRef{ApiID: testIDs["API"]})
		require.NoError(t, m.AddApiInstance(ai))
	}
	// --- API ---
	{
		a := mdlapi.NewAPI(testIDs["API"])
		a.SetDisplayName("Test API")
		a.SetSystem(&system.SystemRef{SystemId: testIDs["System"]})
		require.NoError(t, m.AddApi(a))
	}
	// --- Component ---
	{
		comp := component.NewComponent(testIDs["Component"])
		comp.SetDisplayName("Test Component")
		comp.SetSystem(&system.SystemRef{SystemId: testIDs["System"]})
		require.NoError(t, m.AddComponent(comp))
	}
	// --- SystemInstance ---
	{
		si := system.NewSystemInstance(testIDs["SystemInstance"])
		si.SetDisplayName("Test SystemInstance")
		si.SetSystemRef(&system.SystemRef{SystemId: testIDs["System"]})
		require.NoError(t, m.AddSystemInstance(si))
	}
	// --- ComponentInstance ---
	{
		ci := component.NewComponentInstance(testIDs["ComponentInstance"])
		ci.SetDisplayName("Test ComponentInstance")
		ci.SetComponentRef(&component.ComponentRef{ComponentId: testIDs["Component"]})
		require.NoError(t, m.AddComponentInstance(ci))
	}
	// --- Finding ---
	{
		f := finding.NewFinding(testIDs["Finding"])
		f.SetDisplayName("Test Finding")
		f.SetFindingTypeById(testIDs["FindingType"])
		require.NoError(t, m.AddFinding(f))
	}
	// --- OrgUnit ---
	{
		ou := iam.NewOrgUnit(testIDs["OrgUnit"])
		ou.SetDisplayName("Test OrgUnit")
		require.NoError(t, m.AddOrgUnit(ou))
	}
	// --- Group ---
	{
		g := iam.NewGroup(testIDs["Group"])
		g.SetDisplayName("Test Group")
		require.NoError(t, m.AddGroup(g))
	}
	// --- Identity ---
	{
		id := iam.NewIdentity(testIDs["Identity"])
		id.SetDisplayName("Test Identity")
		require.NoError(t, m.AddIdentity(id))
	}
	// --- PermissionSpec ---
	{
		ps := iam.NewPermissionSpec(testIDs["PermissionSpec"])
		ps.SetDisplayName("Test PermissionSpec")
		require.NoError(t, m.AddPermissionSpec(ps))
	}
	// --- RoleSpec ---
	{
		rs := iam.NewRoleSpec(testIDs["RoleSpec"])
		rs.SetDisplayName("Test RoleSpec")
		rs.SetPermissions([]*iam.PermissionSpecRef{&iam.PermissionSpecRef{PermissionSpecId: testIDs["PermissionSpec"]}})
		require.NoError(t, m.AddRoleSpec(rs))
	}
	// --- Permission ---
	{
		p := iam.NewPermission(testIDs["Permission"])
		p.SetDisplayName("Test Permission")
		p.SetPermissionSpecById(testIDs["PermissionSpec"])
		require.NoError(t, m.AddPermission(p))
	}
	// --- Role ---
	{
		r := iam.NewRole(testIDs["Role"])
		r.SetDisplayName("Test Role")
		r.SetRoleSpecById(testIDs["RoleSpec"])
		r.SetContextRef(&mdlctx.ContextRef{ContextId: testIDs["Context"]})
		r.SetPermissions([]*iam.PermissionRef{&iam.PermissionRef{PermissionId: testIDs["Permission"]}})
		require.NoError(t, m.AddRole(r))
	}
	// --- Binding ---
	{
		b := iam.NewBinding(testIDs["Binding"])
		b.SetDisplayName("Test Binding")
		b.SetRole(&iam.RoleRef{RoleId: testIDs["Role"]})
		b.SetSubject(&iam.SubjectRef{Group: &iam.GroupRef{GroupId: testIDs["Group"]}})
		require.NoError(t, m.AddBinding(b))
	}
	// --- Artifact ---
	{
		a := artifact.NewArtifact(testIDs["Artifact"])
		a.SetDisplayName("Test Artifact")
		require.NoError(t, m.AddArtifact(a))
	}
	// --- ArtifactInstance ---
	{
		ai := artifact.NewArtifactInstance(testIDs["ArtifactInstance"])
		ai.SetDisplayName("Test ArtifactInstance")
		require.NoError(t, m.AddArtifactInstance(ai))
	}
	// --- Product ---
	{
		p := mdlproduct.NewProduct(testIDs["Product"])
		p.SetDisplayName("Test Product")
		p.SetVendor(&iam.OrgUnitRef{OrgUnitId: testIDs["OrgUnit"]})
		require.NoError(t, m.AddProduct(p))
	}
	// --- FilterRule ---
	{
		fr := mdlfilterrule.NewFilterRule(testIDs["FilterRule"])
		fr.SetDisplayName("Test FilterRule")
		require.NoError(t, m.AddFilterRule(fr))
	}
	// --- MergeRule ---
	{
		mr := mdlmergerule.NewMergeRule(testIDs["MergeRule"])
		mr.SetDisplayName("Test MergeRule")
		require.NoError(t, m.AddMergeRule(mr))
	}
	// --- Capability ---
	{
		cap := mdlcapability.NewCapability(testIDs["Capability"])
		cap.SetDisplayName("Test Capability")
		require.NoError(t, m.AddCapability(cap))
	}
	// --- Parameter ---
	{
		param := mdlparameter.NewParameter(testIDs["Parameter"])
		param.SetDisplayName("Test Parameter")
		param.SetValues([]string{"val1", "val2"})
		require.NoError(t, m.AddParameter(param))
	}
}

func TestStoreContextTypeCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["ContextType"]
	got := m.GetContextTypeById(id)
	require.NotNil(t, got, "expected ContextType to be stored")
	assert.Equal(t, id, got.GetContextTypeId())

	list, err := m.GetContextTypes()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteContextTypeById(testIDs["ContextType"])
	require.NoError(t, err)
	assert.Nil(t, m.GetContextTypeById(id))

	err = m.DeleteContextTypeById(testIDs["ContextType"])
	assert.ErrorIs(t, err, common.ErrContextTypeNotFound)
}

func TestStoreContextTypeApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	ct := mdlctx.NewContextType(resourceID)
	ct.SetDisplayName("Test ContextType")
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.ContextTypeResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{ct},
	}))

	got := m.GetContextTypeById(resourceID)
	require.NotNil(t, got, "expected replicated ContextType")
	assert.Equal(t, resourceID, got.GetContextTypeId())

	err := m.Apply(events.Event{
		ResourceType: events.ContextTypeResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetContextTypeById(resourceID))
}

func TestStoreContextCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["Context"]
	got := m.GetContextById(id)
	require.NotNil(t, got, "expected Context to be stored")
	assert.Equal(t, id, got.GetContextId())

	list, err := m.GetContexts()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteContextById(testIDs["Context"])
	require.NoError(t, err)
	assert.Nil(t, m.GetContextById(id))

	err = m.DeleteContextById(testIDs["Context"])
	assert.ErrorIs(t, err, common.ErrContextNotFound)
}

func TestStoreContextApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	c := mdlctx.NewContext(resourceID)
	c.SetDisplayName("Test Context")
	c.SetContextTypeById(testIDs["ContextType"])
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.ContextResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{c},
	}))

	got := m.GetContextById(resourceID)
	require.NotNil(t, got, "expected replicated Context")
	assert.Equal(t, resourceID, got.GetContextId())

	err := m.Apply(events.Event{
		ResourceType: events.ContextResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetContextById(resourceID))
}

func TestStoreSystemCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["System"]
	got := m.GetSystemById(id)
	require.NotNil(t, got, "expected System to be stored")
	assert.Equal(t, id, got.GetSystemId())

	list, err := m.GetSystems()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteSystemById(testIDs["System"])
	require.NoError(t, err)
	assert.Nil(t, m.GetSystemById(id))

	err = m.DeleteSystemById(testIDs["System"])
	assert.ErrorIs(t, err, common.ErrSystemNotFound)
}

func TestStoreSystemApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	sys := system.NewSystem(resourceID)
	sys.SetDisplayName("Test System")
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.SystemResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{sys},
	}))

	got := m.GetSystemById(resourceID)
	require.NotNil(t, got, "expected replicated System")
	assert.Equal(t, resourceID, got.GetSystemId())

	err := m.Apply(events.Event{
		ResourceType: events.SystemResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetSystemById(resourceID))
}

func TestStoreNodeTypeCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["NodeType"]
	got := m.GetNodeTypeById(id)
	require.NotNil(t, got, "expected NodeType to be stored")
	assert.Equal(t, id, got.GetNodeTypeId())

	list, err := m.GetNodeTypes()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteNodeTypeById(testIDs["NodeType"])
	require.NoError(t, err)
	assert.Nil(t, m.GetNodeTypeById(id))

	err = m.DeleteNodeTypeById(testIDs["NodeType"])
	assert.ErrorIs(t, err, common.ErrNodeTypeNotFound)
}

func TestStoreNodeTypeApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	nt := node.NewNodeType(resourceID)
	nt.SetDisplayName("Test NodeType")
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.NodeTypeResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{nt},
	}))

	got := m.GetNodeTypeById(resourceID)
	require.NotNil(t, got, "expected replicated NodeType")
	assert.Equal(t, resourceID, got.GetNodeTypeId())

	err := m.Apply(events.Event{
		ResourceType: events.NodeTypeResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetNodeTypeById(resourceID))
}

func TestStoreFindingTypeCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["FindingType"]
	got := m.GetFindingTypeById(id)
	require.NotNil(t, got, "expected FindingType to be stored")
	assert.Equal(t, id, got.GetFindingTypeId())

	list, err := m.GetFindingTypes()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteFindingTypeById(testIDs["FindingType"])
	require.NoError(t, err)
	assert.Nil(t, m.GetFindingTypeById(id))

	err = m.DeleteFindingTypeById(testIDs["FindingType"])
	assert.ErrorIs(t, err, common.ErrFindingTypeNotFound)
}

func TestStoreFindingTypeApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	ft := finding.NewFindingType(resourceID)
	ft.SetDisplayName("Test FindingType")
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.FindingTypeResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{ft},
	}))

	got := m.GetFindingTypeById(resourceID)
	require.NotNil(t, got, "expected replicated FindingType")
	assert.Equal(t, resourceID, got.GetFindingTypeId())

	err := m.Apply(events.Event{
		ResourceType: events.FindingTypeResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetFindingTypeById(resourceID))
}

func TestStoreNodeCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["Node"]
	got := m.GetNodeById(id)
	require.NotNil(t, got, "expected Node to be stored")
	assert.Equal(t, id, got.GetNodeId())

	list, err := m.GetNodes()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteNodeById(testIDs["Node"])
	require.NoError(t, err)
	assert.Nil(t, m.GetNodeById(id))

	err = m.DeleteNodeById(testIDs["Node"])
	assert.ErrorIs(t, err, common.ErrNodeNotFound)
}

func TestStoreNodeApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	n := node.NewNode(resourceID)
	n.SetDisplayName("Test Node")
	n.SetTypeRef(&node.NodeTypeRef{NodeTypeId: testIDs["NodeType"]})
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.NodeResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{n},
	}))

	got := m.GetNodeById(resourceID)
	require.NotNil(t, got, "expected replicated Node")
	assert.Equal(t, resourceID, got.GetNodeId())

	err := m.Apply(events.Event{
		ResourceType: events.NodeResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetNodeById(resourceID))
}

func TestStoreApiInstanceCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["ApiInstance"]
	got := m.GetApiInstanceById(id)
	require.NotNil(t, got, "expected ApiInstance to be stored")
	assert.Equal(t, id, got.GetInstanceId())

	list, err := m.GetApiInstances()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteApiInstanceById(testIDs["ApiInstance"])
	require.NoError(t, err)
	assert.Nil(t, m.GetApiInstanceById(id))

	err = m.DeleteApiInstanceById(testIDs["ApiInstance"])
	assert.ErrorIs(t, err, common.ErrApiInstanceNotFound)
}

func TestStoreApiInstanceApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	ai := mdlapi.NewApiInstance(resourceID)
	ai.SetDisplayName("Test ApiInstance")
	ai.SetApiRef(&mdlapi.ApiRef{ApiID: testIDs["API"]})
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.APIInstanceResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{ai},
	}))

	got := m.GetApiInstanceById(resourceID)
	require.NotNil(t, got, "expected replicated ApiInstance")
	assert.Equal(t, resourceID, got.GetInstanceId())

	err := m.Apply(events.Event{
		ResourceType: events.APIInstanceResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetApiInstanceById(resourceID))
}

func TestStoreAPICRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["API"]
	got := m.GetApiById(id)
	require.NotNil(t, got, "expected API to be stored")
	assert.Equal(t, id, got.GetApiId())

	list, err := m.GetApis()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteApiById(testIDs["API"])
	require.NoError(t, err)
	assert.Nil(t, m.GetApiById(id))

	err = m.DeleteApiById(testIDs["API"])
	assert.ErrorIs(t, err, common.ErrApiNotFound)
}

func TestStoreAPIApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	a := mdlapi.NewAPI(resourceID)
	a.SetDisplayName("Test API")
	a.SetSystem(&system.SystemRef{SystemId: testIDs["System"]})
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.APIResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{a},
	}))

	got := m.GetApiById(resourceID)
	require.NotNil(t, got, "expected replicated API")
	assert.Equal(t, resourceID, got.GetApiId())

	err := m.Apply(events.Event{
		ResourceType: events.APIResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetApiById(resourceID))
}

func TestStoreComponentCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["Component"]
	got := m.GetComponentById(id)
	require.NotNil(t, got, "expected Component to be stored")
	assert.Equal(t, id, got.GetComponentId())

	list, err := m.GetComponents()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteComponentById(testIDs["Component"])
	require.NoError(t, err)
	assert.Nil(t, m.GetComponentById(id))

	err = m.DeleteComponentById(testIDs["Component"])
	assert.ErrorIs(t, err, common.ErrComponentNotFound)
}

func TestStoreComponentApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	comp := component.NewComponent(resourceID)
	comp.SetDisplayName("Test Component")
	comp.SetSystem(&system.SystemRef{SystemId: testIDs["System"]})
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.ComponentResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{comp},
	}))

	got := m.GetComponentById(resourceID)
	require.NotNil(t, got, "expected replicated Component")
	assert.Equal(t, resourceID, got.GetComponentId())

	err := m.Apply(events.Event{
		ResourceType: events.ComponentResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetComponentById(resourceID))
}

func TestStoreSystemInstanceCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["SystemInstance"]
	got := m.GetSystemInstanceById(id)
	require.NotNil(t, got, "expected SystemInstance to be stored")
	assert.Equal(t, id, got.GetInstanceId())

	list, err := m.GetSystemInstances()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteSystemInstanceById(testIDs["SystemInstance"])
	require.NoError(t, err)
	assert.Nil(t, m.GetSystemInstanceById(id))

	err = m.DeleteSystemInstanceById(testIDs["SystemInstance"])
	assert.ErrorIs(t, err, common.ErrSystemInstanceNotFound)
}

func TestStoreSystemInstanceApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	si := system.NewSystemInstance(resourceID)
	si.SetDisplayName("Test SystemInstance")
	si.SetSystemRef(&system.SystemRef{SystemId: testIDs["System"]})
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.SystemInstanceResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{si},
	}))

	got := m.GetSystemInstanceById(resourceID)
	require.NotNil(t, got, "expected replicated SystemInstance")
	assert.Equal(t, resourceID, got.GetInstanceId())

	err := m.Apply(events.Event{
		ResourceType: events.SystemInstanceResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetSystemInstanceById(resourceID))
}

func TestStoreComponentInstanceCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["ComponentInstance"]
	got := m.GetComponentInstanceById(id)
	require.NotNil(t, got, "expected ComponentInstance to be stored")
	assert.Equal(t, id, got.GetInstanceId())

	list, err := m.GetComponentInstances()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteComponentInstanceById(testIDs["ComponentInstance"])
	require.NoError(t, err)
	assert.Nil(t, m.GetComponentInstanceById(id))

	err = m.DeleteComponentInstanceById(testIDs["ComponentInstance"])
	assert.ErrorIs(t, err, common.ErrComponentInstanceNotFound)
}

func TestStoreComponentInstanceApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	ci := component.NewComponentInstance(resourceID)
	ci.SetDisplayName("Test ComponentInstance")
	ci.SetComponentRef(&component.ComponentRef{ComponentId: testIDs["Component"]})
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.ComponentInstanceResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{ci},
	}))

	got := m.GetComponentInstanceById(resourceID)
	require.NotNil(t, got, "expected replicated ComponentInstance")
	assert.Equal(t, resourceID, got.GetInstanceId())

	err := m.Apply(events.Event{
		ResourceType: events.ComponentInstanceResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetComponentInstanceById(resourceID))
}

func TestStoreFindingCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["Finding"]
	got := m.GetFindingById(id)
	require.NotNil(t, got, "expected Finding to be stored")
	assert.Equal(t, id, got.GetFindingId())

	list, err := m.GetFindings()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteFindingById(testIDs["Finding"])
	require.NoError(t, err)
	assert.Nil(t, m.GetFindingById(id))

	err = m.DeleteFindingById(testIDs["Finding"])
	assert.ErrorIs(t, err, common.ErrFindingNotFound)
}

func TestStoreFindingApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	f := finding.NewFinding(resourceID)
	f.SetDisplayName("Test Finding")
	f.SetFindingTypeById(testIDs["FindingType"])
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.FindingResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{f},
	}))

	got := m.GetFindingById(resourceID)
	require.NotNil(t, got, "expected replicated Finding")
	assert.Equal(t, resourceID, got.GetFindingId())

	err := m.Apply(events.Event{
		ResourceType: events.FindingResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetFindingById(resourceID))
}

func TestStoreOrgUnitCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["OrgUnit"]
	got := m.GetOrgUnitById(id)
	require.NotNil(t, got, "expected OrgUnit to be stored")
	assert.Equal(t, id, got.GetOrgUnitId())

	list, err := m.GetOrgUnits()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteOrgUnit(testIDs["OrgUnit"])
	require.NoError(t, err)
	assert.Nil(t, m.GetOrgUnitById(id))

	err = m.DeleteOrgUnit(testIDs["OrgUnit"])
	assert.ErrorIs(t, err, common.ErrOrgUnitNotFound)
}

func TestStoreOrgUnitApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	ou := iam.NewOrgUnit(resourceID)
	ou.SetDisplayName("Test OrgUnit")
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.OrgUnitResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{ou},
	}))

	got := m.GetOrgUnitById(resourceID)
	require.NotNil(t, got, "expected replicated OrgUnit")
	assert.Equal(t, resourceID, got.GetOrgUnitId())

	err := m.Apply(events.Event{
		ResourceType: events.OrgUnitResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetOrgUnitById(resourceID))
}

func TestStoreGroupCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["Group"]
	got := m.GetGroupById(id)
	require.NotNil(t, got, "expected Group to be stored")
	assert.Equal(t, id, got.GetGroupId())

	list, err := m.GetGroups()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteGroup(testIDs["Group"])
	require.NoError(t, err)
	assert.Nil(t, m.GetGroupById(id))

	err = m.DeleteGroup(testIDs["Group"])
	assert.ErrorIs(t, err, common.ErrGroupNotFound)
}

func TestStoreGroupApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	g := iam.NewGroup(resourceID)
	g.SetDisplayName("Test Group")
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.GroupResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{g},
	}))

	got := m.GetGroupById(resourceID)
	require.NotNil(t, got, "expected replicated Group")
	assert.Equal(t, resourceID, got.GetGroupId())

	err := m.Apply(events.Event{
		ResourceType: events.GroupResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetGroupById(resourceID))
}

func TestStoreIdentityCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["Identity"]
	got := m.GetIdentityById(id)
	require.NotNil(t, got, "expected Identity to be stored")
	assert.Equal(t, id, got.GetIdentityId())

	list, err := m.GetIdentities()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteIdentity(testIDs["Identity"])
	require.NoError(t, err)
	assert.Nil(t, m.GetIdentityById(id))

	err = m.DeleteIdentity(testIDs["Identity"])
	assert.ErrorIs(t, err, common.ErrIdentityNotFound)
}

func TestStoreIdentityApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	id := iam.NewIdentity(resourceID)
	id.SetDisplayName("Test Identity")
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.IdentityResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{id},
	}))

	got := m.GetIdentityById(resourceID)
	require.NotNil(t, got, "expected replicated Identity")
	assert.Equal(t, resourceID, got.GetIdentityId())

	err := m.Apply(events.Event{
		ResourceType: events.IdentityResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetIdentityById(resourceID))
}

func TestStorePermissionSpecCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["PermissionSpec"]
	got := m.GetPermissionSpecById(id)
	require.NotNil(t, got, "expected PermissionSpec to be stored")
	assert.Equal(t, id, got.GetPermissionSpecId())

	list, err := m.GetPermissionSpecs()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeletePermissionSpec(testIDs["PermissionSpec"])
	require.NoError(t, err)
	assert.Nil(t, m.GetPermissionSpecById(id))

	err = m.DeletePermissionSpec(testIDs["PermissionSpec"])
	assert.ErrorIs(t, err, common.ErrPermissionSpecNotFound)
}

func TestStorePermissionSpecApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	ps := iam.NewPermissionSpec(resourceID)
	ps.SetDisplayName("Test PermissionSpec")
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.PermissionSpecResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{ps},
	}))

	got := m.GetPermissionSpecById(resourceID)
	require.NotNil(t, got, "expected replicated PermissionSpec")
	assert.Equal(t, resourceID, got.GetPermissionSpecId())

	err := m.Apply(events.Event{
		ResourceType: events.PermissionSpecResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetPermissionSpecById(resourceID))
}

func TestStoreRoleSpecCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["RoleSpec"]
	got := m.GetRoleSpecById(id)
	require.NotNil(t, got, "expected RoleSpec to be stored")
	assert.Equal(t, id, got.GetRoleSpecId())

	list, err := m.GetRoleSpecs()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteRoleSpec(testIDs["RoleSpec"])
	require.NoError(t, err)
	assert.Nil(t, m.GetRoleSpecById(id))

	err = m.DeleteRoleSpec(testIDs["RoleSpec"])
	assert.ErrorIs(t, err, common.ErrRoleSpecNotFound)
}

func TestStoreRoleSpecApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	rs := iam.NewRoleSpec(resourceID)
	rs.SetDisplayName("Test RoleSpec")
	rs.SetPermissions([]*iam.PermissionSpecRef{&iam.PermissionSpecRef{PermissionSpecId: testIDs["PermissionSpec"]}})
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.RoleSpecResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{rs},
	}))

	got := m.GetRoleSpecById(resourceID)
	require.NotNil(t, got, "expected replicated RoleSpec")
	assert.Equal(t, resourceID, got.GetRoleSpecId())

	err := m.Apply(events.Event{
		ResourceType: events.RoleSpecResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetRoleSpecById(resourceID))
}

func TestStorePermissionCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["Permission"]
	got := m.GetPermissionById(id)
	require.NotNil(t, got, "expected Permission to be stored")
	assert.Equal(t, id, got.GetPermissionId())

	list, err := m.GetPermissions()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeletePermission(testIDs["Permission"])
	require.NoError(t, err)
	assert.Nil(t, m.GetPermissionById(id))

	err = m.DeletePermission(testIDs["Permission"])
	assert.ErrorIs(t, err, common.ErrPermissionNotFound)
}

func TestStorePermissionApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	p := iam.NewPermission(resourceID)
	p.SetDisplayName("Test Permission")
	p.SetPermissionSpecById(testIDs["PermissionSpec"])
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.PermissionResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{p},
	}))

	got := m.GetPermissionById(resourceID)
	require.NotNil(t, got, "expected replicated Permission")
	assert.Equal(t, resourceID, got.GetPermissionId())

	err := m.Apply(events.Event{
		ResourceType: events.PermissionResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetPermissionById(resourceID))
}

func TestStoreRoleCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["Role"]
	got := m.GetRoleById(id)
	require.NotNil(t, got, "expected Role to be stored")
	assert.Equal(t, id, got.GetRoleId())

	list, err := m.GetRoles()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteRole(testIDs["Role"])
	require.NoError(t, err)
	assert.Nil(t, m.GetRoleById(id))

	err = m.DeleteRole(testIDs["Role"])
	assert.ErrorIs(t, err, common.ErrRoleNotFound)
}

func TestStoreRoleApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	r := iam.NewRole(resourceID)
	r.SetDisplayName("Test Role")
	r.SetRoleSpecById(testIDs["RoleSpec"])
	r.SetContextRef(&mdlctx.ContextRef{ContextId: testIDs["Context"]})
	r.SetPermissions([]*iam.PermissionRef{&iam.PermissionRef{PermissionId: testIDs["Permission"]}})
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.RoleResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{r},
	}))

	got := m.GetRoleById(resourceID)
	require.NotNil(t, got, "expected replicated Role")
	assert.Equal(t, resourceID, got.GetRoleId())

	err := m.Apply(events.Event{
		ResourceType: events.RoleResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetRoleById(resourceID))
}

func TestStoreBindingCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["Binding"]
	got := m.GetBindingById(id)
	require.NotNil(t, got, "expected Binding to be stored")
	assert.Equal(t, id, got.GetBindingId())

	list, err := m.GetBindings()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteBinding(testIDs["Binding"])
	require.NoError(t, err)
	assert.Nil(t, m.GetBindingById(id))

	err = m.DeleteBinding(testIDs["Binding"])
	assert.ErrorIs(t, err, common.ErrBindingNotFound)
}

func TestStoreBindingApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	b := iam.NewBinding(resourceID)
	b.SetDisplayName("Test Binding")
	b.SetRole(&iam.RoleRef{RoleId: testIDs["Role"]})
	b.SetSubject(&iam.SubjectRef{Group: &iam.GroupRef{GroupId: testIDs["Group"]}})
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.BindingResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{b},
	}))

	got := m.GetBindingById(resourceID)
	require.NotNil(t, got, "expected replicated Binding")
	assert.Equal(t, resourceID, got.GetBindingId())

	err := m.Apply(events.Event{
		ResourceType: events.BindingResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetBindingById(resourceID))
}

func TestStoreArtifactCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["Artifact"]
	got := m.GetArtifactById(id)
	require.NotNil(t, got, "expected Artifact to be stored")
	assert.Equal(t, id, got.GetArtifactId())

	list, err := m.GetArtifacts()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteArtifactById(testIDs["Artifact"])
	require.NoError(t, err)
	assert.Nil(t, m.GetArtifactById(id))

	err = m.DeleteArtifactById(testIDs["Artifact"])
	assert.ErrorIs(t, err, common.ErrArtifactNotFound)
}

func TestStoreArtifactApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	a := artifact.NewArtifact(resourceID)
	a.SetDisplayName("Test Artifact")
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.ArtifactResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{a},
	}))

	got := m.GetArtifactById(resourceID)
	require.NotNil(t, got, "expected replicated Artifact")
	assert.Equal(t, resourceID, got.GetArtifactId())

	err := m.Apply(events.Event{
		ResourceType: events.ArtifactResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetArtifactById(resourceID))
}

func TestStoreArtifactInstanceCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["ArtifactInstance"]
	got := m.GetArtifactInstanceById(id)
	require.NotNil(t, got, "expected ArtifactInstance to be stored")
	assert.Equal(t, id, got.GetArtifactInstanceId())

	list, err := m.GetArtifactInstances()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteArtifactInstanceById(testIDs["ArtifactInstance"])
	require.NoError(t, err)
	assert.Nil(t, m.GetArtifactInstanceById(id))

	err = m.DeleteArtifactInstanceById(testIDs["ArtifactInstance"])
	assert.ErrorIs(t, err, common.ErrArtifactInstanceNotFound)
}

func TestStoreArtifactInstanceApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	ai := artifact.NewArtifactInstance(resourceID)
	ai.SetDisplayName("Test ArtifactInstance")
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.ArtifactInstanceResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{ai},
	}))

	got := m.GetArtifactInstanceById(resourceID)
	require.NotNil(t, got, "expected replicated ArtifactInstance")
	assert.Equal(t, resourceID, got.GetArtifactInstanceId())

	err := m.Apply(events.Event{
		ResourceType: events.ArtifactInstanceResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetArtifactInstanceById(resourceID))
}

func TestStoreProductCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["Product"]
	got := m.GetProductById(id)
	require.NotNil(t, got, "expected Product to be stored")
	assert.Equal(t, id, got.GetProductId())

	list, err := m.GetProducts()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteProductById(testIDs["Product"])
	require.NoError(t, err)
	assert.Nil(t, m.GetProductById(id))

	err = m.DeleteProductById(testIDs["Product"])
	assert.ErrorIs(t, err, common.ErrProductNotFound)
}

func TestStoreProductApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	p := mdlproduct.NewProduct(resourceID)
	p.SetDisplayName("Test Product")
	p.SetVendor(&iam.OrgUnitRef{OrgUnitId: testIDs["OrgUnit"]})
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.ProductResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{p},
	}))

	got := m.GetProductById(resourceID)
	require.NotNil(t, got, "expected replicated Product")
	assert.Equal(t, resourceID, got.GetProductId())

	err := m.Apply(events.Event{
		ResourceType: events.ProductResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetProductById(resourceID))
}

func TestStoreFilterRuleCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["FilterRule"]
	got := m.GetFilterRuleById(id)
	require.NotNil(t, got, "expected FilterRule to be stored")
	assert.Equal(t, id, got.GetRuleId())

	list, err := m.GetFilterRules()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteFilterRuleById(testIDs["FilterRule"])
	require.NoError(t, err)
	assert.Nil(t, m.GetFilterRuleById(id))

	err = m.DeleteFilterRuleById(testIDs["FilterRule"])
	assert.ErrorIs(t, err, common.ErrFilterRuleNotFound)
}

func TestStoreFilterRuleApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	fr := mdlfilterrule.NewFilterRule(resourceID)
	fr.SetDisplayName("Test FilterRule")
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.FilterRuleResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{fr},
	}))

	got := m.GetFilterRuleById(resourceID)
	require.NotNil(t, got, "expected replicated FilterRule")
	assert.Equal(t, resourceID, got.GetRuleId())

	err := m.Apply(events.Event{
		ResourceType: events.FilterRuleResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetFilterRuleById(resourceID))
}

func TestStoreMergeRuleCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["MergeRule"]
	got := m.GetMergeRuleById(id)
	require.NotNil(t, got, "expected MergeRule to be stored")
	assert.Equal(t, id, got.GetRuleId())

	list, err := m.GetMergeRules()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteMergeRuleById(testIDs["MergeRule"])
	require.NoError(t, err)
	assert.Nil(t, m.GetMergeRuleById(id))

	err = m.DeleteMergeRuleById(testIDs["MergeRule"])
	assert.ErrorIs(t, err, common.ErrMergeRuleNotFound)
}

func TestStoreMergeRuleApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	mr := mdlmergerule.NewMergeRule(resourceID)
	mr.SetDisplayName("Test MergeRule")
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.MergeRuleResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{mr},
	}))

	got := m.GetMergeRuleById(resourceID)
	require.NotNil(t, got, "expected replicated MergeRule")
	assert.Equal(t, resourceID, got.GetRuleId())

	err := m.Apply(events.Event{
		ResourceType: events.MergeRuleResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetMergeRuleById(resourceID))
}

func TestStoreCapabilityCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["Capability"]
	got := m.GetCapabilityById(id)
	require.NotNil(t, got, "expected Capability to be stored")
	assert.Equal(t, id, got.GetCapabilityId())

	list, err := m.GetCapabilities()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteCapabilityById(testIDs["Capability"])
	require.NoError(t, err)
	assert.Nil(t, m.GetCapabilityById(id))

	err = m.DeleteCapabilityById(testIDs["Capability"])
	assert.ErrorIs(t, err, common.ErrCapabilityNotFound)
}

func TestStoreCapabilityApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	cap := mdlcapability.NewCapability(resourceID)
	cap.SetDisplayName("Test Capability")
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.CapabilityResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{cap},
	}))

	got := m.GetCapabilityById(resourceID)
	require.NotNil(t, got, "expected replicated Capability")
	assert.Equal(t, resourceID, got.GetCapabilityId())

	err := m.Apply(events.Event{
		ResourceType: events.CapabilityResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetCapabilityById(resourceID))
}

func TestStoreParameterCRUD(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	id := testIDs["Parameter"]
	got := m.GetParameterById(id)
	require.NotNil(t, got, "expected Parameter to be stored")
	assert.Equal(t, id, got.GetParameterId())

	list, err := m.GetParameters()
	require.NoError(t, err)
	require.NotEmpty(t, list)

	err = m.DeleteParameterById(testIDs["Parameter"])
	require.NoError(t, err)
	assert.Nil(t, m.GetParameterById(id))

	err = m.DeleteParameterById(testIDs["Parameter"])
	assert.ErrorIs(t, err, common.ErrParameterNotFound)
}

func TestStoreParameterApplyReplication(t *testing.T) {
	m, _ := newStoreModel(t)
	loadStoreTestModel(t, m)

	resourceID := uuid.New()
	param := mdlparameter.NewParameter(resourceID)
	param.SetDisplayName("Test Parameter")
	param.SetValues([]string{"val1", "val2"})
	require.NoError(t, m.Apply(events.Event{
		ResourceType: events.ParameterResource,
		Operation:    events.CreateOperation,
		ResourceId:   resourceID,
		Objects:      []any{param},
	}))

	got := m.GetParameterById(resourceID)
	require.NotNil(t, got, "expected replicated Parameter")
	assert.Equal(t, resourceID, got.GetParameterId())

	err := m.Apply(events.Event{
		ResourceType: events.ParameterResource,
		Operation:    events.DeleteOperation,
		ResourceId:   resourceID,
	})
	require.NoError(t, err)
	assert.Nil(t, m.GetParameterById(resourceID))
}
