// Code generated by generate_events.go. DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
)

// ensure System interface is implemented correctly
var _ System = (*systemData)(nil)

// ensure events.EventSink interface is implemented correctly
var _ events.EventSink = (*systemData)(nil)

type System interface {
	GetSystemId() uuid.UUID
	GetResourceId() uuid.UUID
	GetResourceName() string

	GetDisplayName() string
	SetDisplayName(string)

	GetDescription() string
	SetDescription(string)

	GetVersion() Version
	SetVersion(Version)

	GetAbstract() bool
	SetAbstract(bool)

	GetAnnotations() Annotations
	SetAnnotations(Annotations)

	GetParent() (System, error)
	SetParent(*SystemRef)
	SetParentByRef(parent System)

	Register()
}

type systemData struct {
	sink         events.EventSink
	isRegistered bool

	SystemId    uuid.UUID
	DisplayName string
	Description string
	Version     Version
	Abstract    bool
	Parent      *SystemRef
	Annotations Annotations
}

// NewSystem constructs a resource that forwards model changes through sink via [events.EventSink.Receive].
func NewSystem(sink events.EventSink, id uuid.UUID) System {
	retval := &systemData{
		sink:         sink,
		isRegistered: false,
		SystemId:     id,
	}

	retval.Annotations = NewAnnotations(retval)

	return retval
}

// GetSystemId implements [System].
func (o *systemData) GetSystemId() uuid.UUID {
	return o.SystemId
}

// GetResourceId implements the hasIdAndName interface.
func (o *systemData) GetResourceId() uuid.UUID {
	return o.SystemId
}

// GetResourceName implements the hasIdAndName interface.
func (o *systemData) GetResourceName() string {
	return o.DisplayName
}

// GetDisplayName implements [DisplayName].
func (o *systemData) GetDisplayName() string {
	return o.DisplayName
}

// SetDisplayName implements [System].
func (o *systemData) SetDisplayName(val string) {
	o.DisplayName = val

	if o.isRegistered {
		o.sink.Receive(events.SystemResource, events.UpdateOperation, o.SystemId, o)
	}
}

// GetDescription implements [Description].
func (o *systemData) GetDescription() string {
	return o.Description
}

// SetDescription implements [System].
func (o *systemData) SetDescription(val string) {
	o.Description = val

	if o.isRegistered {
		o.sink.Receive(events.SystemResource, events.UpdateOperation, o.SystemId, o)
	}
}

// GetVersion implements [Version].
func (o *systemData) GetVersion() Version {
	return o.Version
}

// SetVersion implements [System].
func (o *systemData) SetVersion(val Version) {
	o.Version = val

	if o.isRegistered {
		o.sink.Receive(events.SystemResource, events.UpdateOperation, o.SystemId, o)
	}
}

// GetAbstract implements [Abstract].
func (o *systemData) GetAbstract() bool {
	return o.Abstract
}

// SetAbstract implements [System].
func (o *systemData) SetAbstract(val bool) {
	o.Abstract = val

	if o.isRegistered {
		o.sink.Receive(events.SystemResource, events.UpdateOperation, o.SystemId, o)
	}
}

// GetAnnotations implements [Annotations].
func (o *systemData) GetAnnotations() Annotations {
	return o.Annotations
}

// SetAnnotations implements [System].
func (o *systemData) SetAnnotations(val Annotations) {
	o.Annotations = val

	if o.isRegistered {
		o.sink.Receive(events.SystemResource, events.UpdateOperation, o.SystemId, o)
	}
}

// GetParent returns the embedded parent [System] when present (otherwise nil). Resolve by id via [Model.GetSystemById].
func (o *systemData) GetParent() (System, error) {
	if o.Parent == nil {
		return nil, nil
	}
	return o.Parent.ResolvedSystem(), nil
}

// SetParent sets the low-level parent reference and emits when registered.
func (o *systemData) SetParent(val *SystemRef) {
	o.Parent = val

	if o.isRegistered {
		o.sink.Receive(events.SystemResource, events.UpdateOperation, o.SystemId, o)
	}
}

// SetParentByRef sets the parent from a [System] by building a [SystemRef].
func (o *systemData) SetParentByRef(parent System) {
	if parent == nil {
		o.SetParent(nil)
		return
	}
	o.SetParent(&SystemRef{
		System:   parent,
		SystemId: parent.GetSystemId(),
	})
}

// Register implements [System].
func (o *systemData) Register() {
	o.isRegistered = true
}

// Receive implements [events.EventSink].
func (o *systemData) Receive(resType events.ResourceType, op events.Operation, resourceId uuid.UUID, object ...any) error {
	if resType != events.AnnotationsResource {
		return fmt.Errorf("unsupported resource type %v in System event sink. Only Annotations are supported", resType)
	}

	// all changes to annotations are automatically reflected in the parent object as updates
	if o.isRegistered {
		return o.sink.Receive(events.SystemResource, events.UpdateOperation, o.SystemId, o)
	}

	return nil
}
