// Code generated by tools/gen. DO NOT EDIT.

package iam

import (
	"fmt"

	"github.com/google/uuid"
	"go.emeland.io/modelsrv/pkg/events"
	"go.emeland.io/modelsrv/pkg/model/annotations"
)

// ensure PermissionSpec interface is implemented correctly
var _ PermissionSpec = (*permissionspecData)(nil)

// ensure events.EventSink interface is implemented correctly
var _ events.EventSink = (*permissionspecData)(nil)

type PermissionSpec interface {
	GetPermissionSpecId() uuid.UUID
	GetResourceId() uuid.UUID
	GetResourceName() string

	GetDisplayName() string
	SetDisplayName(string)

	GetDescription() string
	SetDescription(string)

	GetAnnotations() annotations.Annotations
	SetAnnotations(annotations.Annotations)

	Register(sink events.EventSink)
}

type permissionspecData struct {
	sink         events.EventSink
	isRegistered bool

	PermissionSpecId uuid.UUID
	DisplayName      string
	Description      string
	Annotations      annotations.Annotations
}

// NewPermissionSpec constructs an unregistered resource; call [PermissionSpec.Register] after adding to the model.
func NewPermissionSpec(id uuid.UUID) PermissionSpec {
	retval := &permissionspecData{
		isRegistered:     false,
		PermissionSpecId: id,
	}

	retval.Annotations = annotations.NewAnnotations(retval)

	return retval
}

// GetPermissionSpecId implements [PermissionSpec].
func (o *permissionspecData) GetPermissionSpecId() uuid.UUID {
	return o.PermissionSpecId
}

// GetResourceId implements the hasIdAndName interface.
func (o *permissionspecData) GetResourceId() uuid.UUID {
	return o.PermissionSpecId
}

// GetResourceName implements the hasIdAndName interface.
func (o *permissionspecData) GetResourceName() string {
	return o.DisplayName
}

// GetDisplayName implements [DisplayName].
func (o *permissionspecData) GetDisplayName() string {
	return o.DisplayName
}

// SetDisplayName implements [PermissionSpec].
func (o *permissionspecData) SetDisplayName(val string) {
	o.DisplayName = val

	if o.isRegistered {
		o.sink.Receive(events.PermissionSpecResource, events.UpdateOperation, o.PermissionSpecId, o)
	}
}

// GetDescription implements [Description].
func (o *permissionspecData) GetDescription() string {
	return o.Description
}

// SetDescription implements [PermissionSpec].
func (o *permissionspecData) SetDescription(val string) {
	o.Description = val

	if o.isRegistered {
		o.sink.Receive(events.PermissionSpecResource, events.UpdateOperation, o.PermissionSpecId, o)
	}
}

// GetAnnotations implements [Annotations].
func (o *permissionspecData) GetAnnotations() annotations.Annotations {
	return o.Annotations
}

// SetAnnotations implements [PermissionSpec].
func (o *permissionspecData) SetAnnotations(val annotations.Annotations) {
	o.Annotations = val

	if o.isRegistered {
		o.sink.Receive(events.PermissionSpecResource, events.UpdateOperation, o.PermissionSpecId, o)
	}
}

// Register implements [PermissionSpec].
func (o *permissionspecData) Register(sink events.EventSink) {
	o.sink = sink
	o.isRegistered = true
}

// Receive implements [events.EventSink].
func (o *permissionspecData) Receive(resType events.ResourceType, op events.Operation, resourceId uuid.UUID, object ...any) error {
	if resType != events.AnnotationsResource {
		return fmt.Errorf("unsupported resource type %v in PermissionSpec event sink. Only Annotations are supported", resType)
	}

	if o.isRegistered {
		return o.sink.Receive(events.PermissionSpecResource, events.UpdateOperation, o.PermissionSpecId, o)
	}

	return nil
}
