// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package client

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// API defines model for API.
type API struct {
	// Annotations A set of key-value pairs for storing additional metadata about the API instance.
	Annotations *[]Annotation `json:"annotations,omitempty"`

	// ApiId An UUID that uniquely identifies the API. It should be generated and assigned when the API is created and must remain constant throughout the API's lifecycle. The field is optional in some contexts, such as when creating a new API where the ID may be generated by the system itself.
	ApiId *openapi_types.UUID `json:"apiId,omitempty"`

	// Description A brief description of the API's purpose and functionality.
	Description *string `json:"description,omitempty"`

	// DisplayName The human-readable name of the API.
	DisplayName string `json:"displayName"`

	// System The UUID of the system that provides this API.
	System *openapi_types.UUID `json:"system,omitempty"`

	// Type The type of the API (e.g., OpenAPI, gRPC, GraphQL). If the type is unknown, it should be set to "Unknown". If the type does not fit any predefined categories, it should be set to "Other". In such cases, additional details about the API type should be provided in the description field.
	Type interface{} `json:"type"`

	// Version Version information for all objects in the EmELand model.
	Version *Version `json:"version,omitempty"`
}

// Annotation Represents a key-value pair used for annotating systems and other entities in the EmELand model.
type Annotation struct {
	// Key The key of the annotation. It serves as the identifier for the annotation entry.
	Key string `json:"key"`

	// Value The value associated with the annotation key. It provides additional information or metadata related to the key.
	Value string `json:"value"`
}

// ApiInstance defines model for ApiInstance.
type ApiInstance struct {
	// Annotations A set of key-value pairs for storing additional metadata about the API instance.
	Annotations *[]Annotation `json:"annotations,omitempty"`

	// Api The UUID of the API that this instance realizes. This can be left empty if the API resource has not been created yet, but will trigger an entry in the finding list.
	Api *openapi_types.UUID `json:"api,omitempty"`

	// ApiInstanceId An UUID that uniquely identifies the API instance. It should be generated and assigned when the instance is created and must remain constant throughout the instance's lifecycle. The field is optional in some contexts, such as when creating a new instance where the ID may be generated by the system itself.
	ApiInstanceId openapi_types.UUID `json:"apiInstanceId"`

	// DisplayName The human-readable name of the API instance.
	DisplayName string `json:"displayName"`

	// SystemInstance The UUID of the system instance that contains this API instance. This can be left empty if the SystemInstance resource has not been created yet, but will trigger an entry in the finding list.
	SystemInstance *openapi_types.UUID `json:"systemInstance,omitempty"`
}

// Component defines model for Component.
type Component struct {
	// Annotations A set of key-value pairs for storing additional metadata about the component.
	Annotations *[]Annotation `json:"annotations,omitempty"`

	// ComponentId An UUID that uniquely identifies the component. It should be generated and assigned when the component is created and must remain constant throughout the component's lifecycle. The field is optional in some contexts, such as when creating a new component where the ID may be generated by the system itself.
	ComponentId *openapi_types.UUID `json:"componentId,omitempty"`

	// Consumes A list of API UUIDs that this component consumes.
	Consumes *[]openapi_types.UUID `json:"consumes,omitempty"`

	// Description A brief description of the component's purpose and functionality.
	Description *string `json:"description,omitempty"`

	// DisplayName The human-readable name of the component.
	DisplayName string `json:"displayName"`

	// Provides A list of API UUIDs that this component provides.
	Provides *[]openapi_types.UUID `json:"provides,omitempty"`

	// System The UUID of the system that contains this component.
	System openapi_types.UUID `json:"system"`

	// Version Version information for all objects in the EmELand model.
	Version *Version `json:"version,omitempty"`
}

// ComponentInstance defines model for ComponentInstance.
type ComponentInstance struct {
	// Annotations A set of key-value pairs for storing additional metadata about the component instance.
	Annotations *[]Annotation `json:"annotations,omitempty"`

	// Component The UUID of the component that this instance realizes.
	Component openapi_types.UUID `json:"component"`

	// ComponentInstanceId An UUID that uniquely identifies the component instance. It should be generated and assigned when the instance is created and must remain constant throughout the instance's lifecycle. The field is optional in some contexts, such as when creating a new instance where the ID may be generated by the system itself.
	ComponentInstanceId openapi_types.UUID `json:"componentInstanceId"`

	// Consumes A list of API instance UUIDs that this component instance consumes.
	Consumes []openapi_types.UUID `json:"consumes"`

	// DisplayName The human-readable name of the component instance.
	DisplayName string `json:"displayName"`

	// Provides A list of API instance UUIDs that this component instance provides.
	Provides []openapi_types.UUID `json:"provides"`

	// SystemInstance The UUID of the system instance that contains this component instance.
	SystemInstance openapi_types.UUID `json:"systemInstance"`
}

// Context Represents a context in the EmELand model. A context is a high-level categorization or domain that groups systems and other entities based on shared characteristics or purposes.
type Context struct {
	// Annotations A set of key-value pairs for storing additional metadata about the context.
	Annotations *[]Annotation `json:"annotations,omitempty"`

	// ContextId An UUID that uniquely identifies the context. It should be generated and assigned when the context is created and must remain constant throughout the context's lifecycle. The field is optional in some contexts, such as when creating a new context where the ID may be generated by the system itself.
	ContextId openapi_types.UUID `json:"contextId"`

	// Description A brief description of the context's purpose and scope.
	Description *string `json:"description,omitempty"`

	// DisplayName The human-readable name of the context.
	DisplayName string `json:"displayName"`

	// Parent The UUID of the parent context, if applicable. This field is optional and may be omitted if the context has no parent. It establishes a hierarchical relationship between contexts.
	Parent *openapi_types.UUID `json:"parent,omitempty"`
}

// ErrorString defines model for ErrorString.
type ErrorString = string

// Finding Represents the finding of a rule violation. Rules may either be defined for semantic correctness of the model or for compliance checks against external regulations and standards.
type Finding struct {
	// Annotations A set of key-value pairs for storing additional metadata about the finding.
	Annotations *[]Annotation      `json:"annotations,omitempty"`
	Description *string            `json:"description,omitempty"`
	FindingId   openapi_types.UUID `json:"findingId"`
	Resources   []ResourceRef      `json:"resources"`
	Summary     string             `json:"summary"`
}

// InstanceList defines model for InstanceList.
type InstanceList = []InstanceListItem

// InstanceListItem defines model for InstanceListItem.
type InstanceListItem struct {
	DisplayName *string             `json:"displayName,omitempty"`
	InstanceId  *openapi_types.UUID `json:"instanceId,omitempty"`
	Reference   *string             `json:"reference,omitempty"`
}

// ResourceRef defines model for ResourceRef.
type ResourceRef struct {
	// Reference A URI reference to the resource.
	Reference *string `json:"reference,omitempty"`

	// ResourceId The UUID of the resource referenced.
	ResourceId openapi_types.UUID `json:"resourceId"`

	// ResourceType The type of the resource referenced.
	ResourceType interface{} `json:"resourceType"`
}

// System Represents a system in the EmELand model. A system is a high-level entity that displays a complex behavior. It encapsulates various APIs and software components.
type System struct {
	// Abstract Indicates whether the system is abstract (true) or concrete (false). Abstract systems are primarily used to represent external systems that provide APIs consumed by a concrete system defined within the landscape.
	Abstract bool `json:"abstract"`

	// Annotations A set of key-value pairs for storing additional metadata about the system.
	Annotations *[]Annotation `json:"annotations,omitempty"`

	// Description A brief description of the system's purpose and functionality.
	Description *string `json:"description,omitempty"`
	DisplayName string  `json:"displayName"`

	// Parent The UUID of the parent system, if applicable. This field is optional and may be omitted if the system has no parent. It establishes a hierarchical relationship between systems.
	Parent *openapi_types.UUID `json:"parent,omitempty"`

	// SystemId An UUID that uniquely identifies the system. It should be generated and assigned when the System is created and must remain constant throughout the System's lifecycle. The field is optional in some contexts, such as when creating a new system where the ID may be generated by the system itself.
	SystemId *openapi_types.UUID `json:"systemId,omitempty"`

	// Version Version information for all objects in the EmELand model.
	Version *Version `json:"version,omitempty"`
}

// SystemInstance defines model for SystemInstance.
type SystemInstance struct {
	// Annotations A set of key-value pairs for storing additional metadata about the system instance.
	Annotations *[]Annotation `json:"annotations,omitempty"`

	// Context The UUID of the context that contains this system instance. This can be left empty if the Context resource has not been created yet, but will trigger an entry in the finding list.
	Context *openapi_types.UUID `json:"context,omitempty"`

	// DisplayName The human-readable name of the system instance.
	DisplayName string `json:"displayName"`

	// System The UUID of the system that this instance realizes.
	System openapi_types.UUID `json:"system"`

	// SystemInstanceId An UUID that uniquely identifies the system instance. It should be generated and assigned when the instance is created and must remain constant throughout the instance's lifecycle. The field is optional in some contexts, such as when creating a new instance where the ID may be generated by the system itself.
	SystemInstanceId openapi_types.UUID `json:"systemInstanceId"`
}

// Version Version information for all objects in the EmELand model.
type Version struct {
	// AvailableFrom Timestamp indicating when this version becomes available. Format is 2006-01-02. May be in the future
	AvailableFrom *time.Time `json:"availableFrom,omitempty"`

	// DeprecatedFrom Timestamp indicating when this version is considered deprecated. Consumers should avoid using this version after this date. Format is 2006-01-02. May be in the future. Must be later than availableFrom.
	DeprecatedFrom *time.Time `json:"deprecatedFrom,omitempty"`

	// TerminatedFrom Timestamp indicating when this version is considered terminated. Consumers must not use this version after this date. Format is 2006-01-02. Must be later than deprecatedFrom.
	TerminatedFrom *time.Time `json:"terminatedFrom,omitempty"`

	// Version Structured version string (e.g., "1.0.0"). The use of semantic versioning is recommended.
	Version string `json:"version"`
}

// PostEventsRegisterJSONBody defines parameters for PostEventsRegister.
type PostEventsRegisterJSONBody struct {
	CallbackUrl string `json:"callbackUrl"`
}

// PostEventsUnregisterJSONBody defines parameters for PostEventsUnregister.
type PostEventsUnregisterJSONBody struct {
	CallbackUrl string `json:"callbackUrl"`
}

// PostEventsRegisterJSONRequestBody defines body for PostEventsRegister for application/json ContentType.
type PostEventsRegisterJSONRequestBody PostEventsRegisterJSONBody

// PostEventsUnregisterJSONRequestBody defines body for PostEventsUnregister for application/json ContentType.
type PostEventsUnregisterJSONRequestBody PostEventsUnregisterJSONBody
